import type { ClassroomLesson, ClassroomSlide } from "@/lib/content/classroom";

const ACCENT = "#c6922e";
const ACCENT_DEEP = "#8a6a1a";

const SLIDES: ClassroomSlide[] = [
  {
    id: "yellow-s1",
    number: 1,
    title: "Yellow City · Master Investor",
    subtitle: "From investment ideas to professional portfolio management",
    bullets: [
      "Master Investor",
      "From investment ideas to professional portfolio management",
      "You already know the",
      "foundations of investing.",
      "Yellow City shows how",
      "professionals connect",
      "research, risk and decisions.",
      "Build, manage and defend a",
      "simulated $10 million fund",
      "using a repeatable investment",
    ],
    footer: "Mandate Highlands · Yellow City Master Investor Teaching Deck",
    accent: ACCENT,
    thumbLabel: "Title",
  },
  {
    id: "yellow-s2",
    number: 2,
    title: "How to use this deck",
    subtitle: "The goal is not to memorize formulas. The goal is to understand what question each formula answers and",
    bullets: [
      "YELLOW CITY ORIENTATION",
      "The goal is not to memorize formulas. The goal is to understand what question each formula answers and",
      "how the answer changes an investment decision.",
      "Read the concept in plain language first.",
      "Identify the investment question before calculating.",
      "Write the formula and define the variables.",
      "Substitute values and show every step.",
      "Explain the result in ordinary language.",
      "Only then decide what the result means for the portfolio.",
    ],
    accent: ACCENT,
    thumbLabel: "How to use",
  },
  {
    id: "yellow-s3",
    number: 3,
    title: "The Yellow City journey",
    subtitle: "Nine portals move from a single investment idea to the management and defense of a professional fund.",
    bullets: [
      "PORTALS 28–36",
      "Nine portals move from a single investment idea to the management and defense of a professional fund.",
      "28–30: BUILD",
      "Thesis → behavior → portfolio",
      "optimization. Learn how to make",
      "and combine disciplined decisions.",
      "31–33: ADAPT",
      "Capital rotation → crisis simulation",
      "→ global strategy. Learn how to",
      "respond when conditions change.",
    ],
    accent: ACCENT,
    thumbLabel: "Journey",
  },
  {
    id: "yellow-s4",
    number: 4,
    title: "Portal 28 · Build an Investment Thesis",
    subtitle: "An investment thesis is a testable explanation of why an asset may produce an attractive return. It connects",
    bullets: [
      "Portal 28 — Build an Investment Thesis",
      "An investment thesis is a testable explanation of why an asset may produce an attractive return. It connects",
      "facts, valuation, catalysts, risks and the evidence that would prove the idea wrong.",
      "What exactly are we buying?",
      "What does the current price appear to assume?",
      "What return could reasonably occur?",
      "What could cause the market to change its view?",
      "What can go wrong?",
      "What evidence would make us reduce or exit the position?",
    ],
    accent: ACCENT,
    thumbLabel: "P28 · Build an Investment Thesis",
  },
  {
    id: "yellow-s5",
    number: 5,
    title: "Portal 28 · From research to portfolio action",
    subtitle: "A professional decision follows a sequence. Skipping a step makes it harder to know whether a later gain or",
    bullets: [
      "PORTAL 28",
      "A professional decision follows a sequence. Skipping a step makes it harder to know whether a later gain or",
      "loss came from skill or luck.",
      "1. RESEARCH",
      "Collect evidence about the",
      "business, asset, industry, balance",
      "sheet and economic environment.",
      "2. VALUE",
      "Estimate what the asset may be",
      "worth under more than one",
    ],
    accent: ACCENT,
    thumbLabel: "P28 · From research to",
  },
  {
    id: "yellow-s6",
    number: 6,
    title: "Portal 28 · Expected return — the question",
    subtitle: "Expected return asks: if several different outcomes are possible, what average return is implied after each",
    bullets: [
      "PORTAL 28",
      "Expected return asks: if several different outcomes are possible, what average return is implied after each",
      "outcome is weighted by its probability?",
      "It is forward-looking, not guaranteed.",
      "Probabilities must sum to 100%.",
      "Each scenario contributes probability × scenario return.",
      "The result is useful because competing investments can be compared on the same basis.",
      "E(R) = Σ pᵢRᵢ",
      "pᵢ = probability of scenario i; Rᵢ = return in scenario i",
    ],
    accent: ACCENT,
    thumbLabel: "P28 · Expected return — the",
  },
  {
    id: "yellow-s7",
    number: 7,
    title: "Portal 28 · Worked example — Scenario-weighted expected return",
    subtitle: "30% chance of +25%, 50% chance of +10%, 20% chance of −20%. What is expected return?",
    bullets: [
      "PORTAL 28 • WORKED EXAMPLE",
      "Scenario-weighted expected return",
      "30% chance of +25%, 50% chance of +10%, 20% chance of −20%. What is expected return?",
      "E(R) = Σ pᵢRᵢ",
      "0.30 × 25% = +7.5%",
      "0.50 × 10% = +5.0%",
      "0.20 × (−20%) = −4.0%",
      "7.5% + 5.0% − 4.0% = 8.5%",
      "Expected return = 8.5%",
      "The upside and base cases add 12.5 percentage points, while the",
    ],
    accent: ACCENT,
    thumbLabel: "P28 · Scenario-weighted",
  },
  {
    id: "yellow-s8",
    number: 8,
    title: "Portal 28 · Upside, downside and margin of safety",
    subtitle: "Expected return summarizes scenarios. Upside and downside ask a more concrete question: from today's",
    bullets: [
      "PORTAL 28",
      "Expected return summarizes scenarios. Upside and downside ask a more concrete question: from today's",
      "price, how far could the asset move if our valuation is right — or wrong?",
      "UPSIDE",
      "Potential gain from current price to",
      "estimated fair value.",
      "DOWNSIDE",
      "Potential loss from current price to a",
      "defensible bear-case value.",
      "MARGIN OF SAFETY",
    ],
    accent: ACCENT,
    thumbLabel: "P28 · Upside, downside and",
  },
  {
    id: "yellow-s9",
    number: 9,
    title: "Portal 28 · Worked example — Upside to estimated fair value",
    subtitle: "Current price = $42. Estimated fair value = $55. How much potential price upside is implied?",
    bullets: [
      "PORTAL 28 • WORKED EXAMPLE",
      "Upside to estimated fair value",
      "Current price = $42. Estimated fair value = $55. How much potential price upside is implied?",
      "Upside = (Value − Price) ÷ Price × 100%",
      "$55 − $42 = $13",
      "$13 ÷ $42 = 0.3095238",
      "0.3095238 × 100% = 30.95%",
      "Potential upside ≈ 30.95%",
      "The investor pays $42 for an asset estimated to be worth $55. If",
      "that estimate is correct and the market eventually reaches $55,",
    ],
    accent: ACCENT,
    thumbLabel: "P28 · Upside to estimated fair",
  },
  {
    id: "yellow-s10",
    number: 10,
    title: "Portal 28 · Variant perception",
    subtitle: "A good asset is not automatically a good investment. If everyone already expects strong performance, that",
    bullets: [
      "PORTAL 28",
      "A good asset is not automatically a good investment. If everyone already expects strong performance, that",
      "optimism may already be included in the price.",
      "State what the market or consensus appears to expect.",
      "State what you believe differently.",
      "Identify evidence supporting your different view.",
      "Explain why the market may not yet recognize it.",
      "Identify what event or evidence could close the disagreement.",
    ],
    accent: ACCENT,
    thumbLabel: "P28 · Variant perception",
  },
  {
    id: "yellow-s11",
    number: 11,
    title: "Portal 28 · Catalysts and falsification",
    subtitle: "A complete thesis looks in both directions: what could make the market recognize value, and what evidence",
    bullets: [
      "PORTAL 28",
      "A complete thesis looks in both directions: what could make the market recognize value, and what evidence",
      "would show that the thesis is failing?",
      "An event or process that can change",
      "expectations: earnings, product",
      "launch, refinancing, asset sale, rate",
      "change or regulatory decision.",
      "Evidence that a key assumption is",
      "no longer valid: weak revenue driver,",
      "rising balance-sheet risk, failed",
    ],
    accent: ACCENT,
    thumbLabel: "P28 · Catalysts and",
  },
  {
    id: "yellow-s12",
    number: 12,
    title: "Portal 29 · Behavioural Finance",
    subtitle: "YOUR PROCESS CAN BE CORRECT AND YOUR BEHAVIOR CAN STILL DAMAGE IT",
    bullets: [
      "YOUR PROCESS CAN BE CORRECT AND YOUR BEHAVIOR CAN STILL DAMAGE IT",
      "Portal 29 — Behavioural Finance",
      "Behavioral finance studies systematic ways investors can misread evidence or make inconsistent decisions",
      "under uncertainty.",
      "LOSS AVERSION",
      "Losses feel more painful than",
      "equivalent gains feel rewarding.",
      "ANCHORING / FOMO",
      "Purchase price or recent market",
      "excitement can replace fresh",
    ],
    accent: ACCENT,
    thumbLabel: "P29 · Behavioural Finance",
  },
  {
    id: "yellow-s13",
    number: 13,
    title: "Portal 29 · Why a 30% loss needs more than 30% to recover",
    subtitle: "Percentage losses and gains are calculated from different capital bases. After a loss, the remaining base is",
    bullets: [
      "PORTAL 29",
      "Percentage losses and gains are calculated from different capital bases. After a loss, the remaining base is",
      "smaller.",
      "Start with $100.",
      "Lose 30% → $100 × 0.70 = $70.",
      "To return to $100, the portfolio must regain $30.",
      "$30 is 42.86% of the new $70 base.",
      "Required recovery = 1 ÷ (1 − Loss rate) − 1",
      "A deeper loss creates a disproportionately larger recovery requirement.",
    ],
    accent: ACCENT,
    thumbLabel: "P29 · Why a 30% loss needs more",
  },
  {
    id: "yellow-s14",
    number: 14,
    title: "Portal 29 · Worked example — Recovery after a 30% loss",
    subtitle: "An investment falls 30%. What percentage gain is required to return to its original value?",
    bullets: [
      "PORTAL 29 • WORKED EXAMPLE",
      "Recovery after a 30% loss",
      "An investment falls 30%. What percentage gain is required to return to its original value?",
      "Required gain = 1 ÷ (1 − L) − 1",
      "L = 30% = 0.30",
      "1 ÷ (1 − 0.30) − 1",
      "1 ÷ 0.70 − 1 = 1.428571 − 1",
      "= 0.428571 = 42.86%",
      "Required recovery ≈ 42.86%",
      "If $100 falls to $70, the lost $30 must now be earned on a $70",
    ],
    accent: ACCENT,
    thumbLabel: "P29 · Recovery after a 30% loss",
  },
  {
    id: "yellow-s15",
    number: 15,
    title: "Portal 29 · Disposition effect",
    subtitle: "The disposition effect occurs when an investor realizes winners readily but avoids realizing losses. The",
    bullets: [
      "PORTAL 29",
      "The disposition effect occurs when an investor realizes winners readily but avoids realizing losses. The",
      "important question is whether winners and losers are being judged by different standards.",
      "PGR = proportion of available gains that were realized.",
      "PLR = proportion of available losses that were realized.",
      "PGR − PLR gives a simple indicator of asymmetry.",
      "The result is a signal for investigation, not proof that every trade was wrong.",
    ],
    accent: ACCENT,
    thumbLabel: "P29 · Disposition effect",
  },
  {
    id: "yellow-s16",
    number: 16,
    title: "Portal 29 · Worked example — Measuring the disposition effect",
    subtitle: "Realized gains 12, paper gains 8, realized losses 3, paper losses 9.",
    bullets: [
      "PORTAL 29 • WORKED EXAMPLE",
      "Measuring the disposition effect",
      "Realized gains 12, paper gains 8, realized losses 3, paper losses 9.",
      "PGR = RG/(RG+PG); PLR = RL/(RL+PL)",
      "PGR = 12 ÷ (12+8) = 12/20 = 0.60",
      "PLR = 3 ÷ (3+9) = 3/12 = 0.25",
      "Indicator = 0.60 − 0.25 = 0.35",
      "Disposition indicator = 0.35",
      "The investor realized 60% of available gains but only 25% of",
      "available losses. The 35-point gap suggests profitable positions",
    ],
    accent: ACCENT,
    thumbLabel: "P29 · Measuring the disposition",
  },
  {
    id: "yellow-s17",
    number: 17,
    title: "Portal 29 · Overconfidence — measure it, do not guess",
    subtitle: "A professional investor calibrates confidence by comparing forecasts with actual outcomes.",
    bullets: [
      "PORTAL 29",
      "A professional investor calibrates confidence by comparing forecasts with actual outcomes.",
      "Record the forecast before the outcome is known.",
      "Measure the forecast error.",
      "Look for repeated optimism or pessimism.",
      "Widen scenario ranges or reduce position sizes when forecast error remains large.",
      "Absolute percentage error = |Actual − Forecast| ÷ |Forecast| × 100%",
      "The sign is removed to measure the size of the miss.",
    ],
    accent: ACCENT,
    thumbLabel: "P29 · Overconfidence — measure",
  },
  {
    id: "yellow-s18",
    number: 18,
    title: "Portal 30 · Portfolio Optimization",
    subtitle: "MOVE FROM GOOD HOLDINGS TO A GOOD PORTFOLIO",
    bullets: [
      "MOVE FROM GOOD HOLDINGS TO A GOOD PORTFOLIO",
      "Portal 30 — Portfolio Optimization",
      "Optimization asks how assets should work together. The highest-return asset is not automatically the best",
      "portfolio because risk, correlation, concentration and liquidity also matter.",
      "Expected return: what is the portfolio trying to earn?",
      "Volatility: how much can results fluctuate?",
      "Correlation: do holdings fail at the same time?",
      "Risk contribution: which positions actually drive risk?",
      "Constraints: what must the portfolio never violate?",
    ],
    accent: ACCENT,
    thumbLabel: "P30 · Portfolio Optimization",
  },
  {
    id: "yellow-s19",
    number: 19,
    title: "Portal 30 · Worked example — Expected portfolio return",
    subtitle: "40% equities at 9%, 25% bonds at 4%, 20% real estate at 6%, 15% cash at 2%.",
    bullets: [
      "PORTAL 30 • WORKED EXAMPLE",
      "Expected portfolio return",
      "40% equities at 9%, 25% bonds at 4%, 20% real estate at 6%, 15% cash at 2%.",
      "E(Rp) = Σ wᵢE(Rᵢ)",
      "Equities: 0.40×0.09 = 3.60%",
      "Bonds: 0.25×0.04 = 1.00%",
      "Real estate: 0.20×0.06 = 1.20%",
      "Cash: 0.15×0.02 = 0.30%",
      "Total = 6.10%",
      "Expected portfolio return = 6.10%",
    ],
    accent: ACCENT,
    thumbLabel: "P30 · Expected portfolio return",
  },
  {
    id: "yellow-s20",
    number: 20,
    title: "Portal 30 · Correlation — the engine of diversification",
    subtitle: "Two assets can each be risky on their own but create a less risky combination if they do not move together.",
    bullets: [
      "PORTAL 30",
      "Two assets can each be risky on their own but create a less risky combination if they do not move together.",
      "ρ = +1",
      "Assets move perfectly together.",
      "Diversification benefit is minimal.",
      "ρ ≈ 0",
      "Movements are weakly related.",
      "Diversification can reduce",
      "combined volatility.",
      "ρ < 0",
    ],
    accent: ACCENT,
    thumbLabel: "P30 · Correlation — the engine",
  },
  {
    id: "yellow-s21",
    number: 21,
    title: "Portal 30 · Worked example — Two-asset portfolio volatility",
    subtitle: "60% Asset A, σA=16%; 40% Asset B, σB=10%; correlation = 0.25.",
    bullets: [
      "PORTAL 30 • WORKED EXAMPLE",
      "Two-asset portfolio volatility",
      "60% Asset A, σA=16%; 40% Asset B, σB=10%; correlation = 0.25.",
      "σp² = wA²σA² + wB²σB² + 2wAwBσAσBρ",
      "A term = 0.60²×0.16² = 0.009216",
      "B term = 0.40²×0.10² = 0.001600",
      "Cross term = 2×0.60×0.40×0.16×0.10×0.25 = 0.001920",
      "Variance = 0.012736",
      "σp = √0.012736 = 0.112854 = 11.29%",
      "Portfolio volatility ≈ 11.29%",
    ],
    accent: ACCENT,
    thumbLabel: "P30 · Two-asset portfolio",
  },
  {
    id: "yellow-s22",
    number: 22,
    title: "Portal 30 · Worked example — Sharpe ratio",
    subtitle: "Expected return 8%, risk-free rate 3%, volatility 10%.",
    bullets: [
      "PORTAL 30 • WORKED EXAMPLE",
      "Sharpe ratio",
      "Expected return 8%, risk-free rate 3%, volatility 10%.",
      "Sharpe = [E(Rp) − Rf] ÷ σp",
      "Excess return = 8% − 3% = 5%",
      "0.05 ÷ 0.10 = 0.50",
      "Sharpe ratio = 0.50",
      "The portfolio is expected to earn 0.50 units of return above the",
      "risk-free rate for each unit of total volatility.",
      "INVESTMENT CONNECTION",
    ],
    accent: ACCENT,
    thumbLabel: "P30 · Sharpe ratio",
  },
  {
    id: "yellow-s23",
    number: 23,
    title: "Portal 30 · Risk budgets and constraints",
    subtitle: "Capital weight tells you where the money is. Risk contribution tells you where the danger may be.",
    bullets: [
      "PORTAL 30",
      "Capital weight tells you where the money is. Risk contribution tells you where the danger may be.",
      "RISK BUDGET",
      "A smaller but highly volatile or highly",
      "correlated position can contribute",
      "more risk than its capital weight",
      "suggests.",
      "CONSTRAINTS",
      "Position limits, liquidity floors,",
      "sector/country limits and leverage",
    ],
    accent: ACCENT,
    thumbLabel: "P30 · Risk budgets and",
  },
  {
    id: "yellow-s24",
    number: 24,
    title: "Portal 31 · Capital Rotation",
    subtitle: "Holding an investment is an active decision. Capital rotation asks whether today's expected reward is still",
    bullets: [
      "EVERY DOLLAR HAS AN ALTERNATIVE USE",
      "Portal 31 — Capital Rotation",
      "Holding an investment is an active decision. Capital rotation asks whether today's expected reward is still",
      "superior to the best available alternative.",
      "Compare forward expected returns, not original purchase prices.",
      "Include downside, valuation and thesis confidence.",
      "Include taxes, spreads and transaction costs.",
      "Consider diversification and liquidity.",
      "Rotate only when the expected advantage is material.",
    ],
    accent: ACCENT,
    thumbLabel: "P31 · Capital Rotation",
  },
  {
    id: "yellow-s25",
    number: 25,
    title: "Portal 31 · Worked example — Is the new opportunity better?",
    subtitle: "Current holding expected return 5.5%; new opportunity 9.0%; similar estimated risk.",
    bullets: [
      "PORTAL 31 • WORKED EXAMPLE",
      "Is the new opportunity better?",
      "Current holding expected return 5.5%; new opportunity 9.0%; similar estimated risk.",
      "Relative advantage = E(Rnew) − E(Rcurrent)",
      "9.0% − 5.5% = 3.5 percentage points",
      "Gross expected advantage = 3.5%",
      "From today's prices and assumptions, the alternative offers 3.5",
      "percentage points more expected return.",
      "INVESTMENT CONNECTION",
      "This is only the first hurdle. The manager must subtract",
    ],
    accent: ACCENT,
    thumbLabel: "P31 · Is the new opportunity",
  },
  {
    id: "yellow-s26",
    number: 26,
    title: "Portal 31 · Worked example — Switching hurdle",
    subtitle: "Expected advantage 3.5%; trading cost 0.4%; tax/other cost 1.0%.",
    bullets: [
      "PORTAL 31 • WORKED EXAMPLE",
      "Switching hurdle",
      "Expected advantage 3.5%; trading cost 0.4%; tax/other cost 1.0%.",
      "Net benefit ≈ Advantage − Trading cost − Other cost",
      "3.5% − 0.4% − 1.0%",
      "= 2.1%",
      "Net expected advantage ≈ 2.1%",
      "After explicit switching costs, the alternative still appears better",
      "by about 2.1 percentage points.",
      "INVESTMENT CONNECTION",
    ],
    accent: ACCENT,
    thumbLabel: "P31 · Switching hurdle",
  },
  {
    id: "yellow-s27",
    number: 27,
    title: "Portal 32 · Historical Market Simulator",
    subtitle: "Historical simulation is a decision laboratory. The learner receives only information available at the time and",
    bullets: [
      "CAN YOUR PROCESS SURVIVE STRESS?",
      "Portal 32 — Historical Market Simulator",
      "Historical simulation is a decision laboratory. The learner receives only information available at the time and",
      "must act before the later outcome is revealed.",
      "1987 / CRASH",
      "Rapid decline and liquidity shock.",
      "DOT-COM / 2008",
      "Valuation extremes, leverage and",
      "systemic stress.",
      "COVID / 2022",
    ],
    accent: ACCENT,
    thumbLabel: "P32 · Historical Market",
  },
  {
    id: "yellow-s28",
    number: 28,
    title: "Portal 32 · Worked example — Drawdown",
    subtitle: "Fund peaks at $10.8m and later falls to $8.1m.",
    bullets: [
      "PORTAL 32 • WORKED EXAMPLE",
      "Drawdown",
      "Fund peaks at $10.8m and later falls to $8.1m.",
      "Drawdown = (Trough − Peak) ÷ Peak × 100%",
      "$8.1m − $10.8m = −$2.7m",
      "−$2.7m ÷ $10.8m = −0.25",
      "−0.25 × 100% = −25%",
      "Maximum drawdown = −25%",
      "The fund lost one quarter of its value from the previous high to the",
      "trough. Drawdown describes the loss experience the investor",
    ],
    accent: ACCENT,
    thumbLabel: "P32 · Drawdown",
  },
  {
    id: "yellow-s29",
    number: 29,
    title: "Portal 32 · Worked example — Recovery after drawdown",
    subtitle: "The fund fell from $10.8m to $8.1m. What return is required to recover the peak?",
    bullets: [
      "PORTAL 32 • WORKED EXAMPLE",
      "Recovery after drawdown",
      "The fund fell from $10.8m to $8.1m. What return is required to recover the peak?",
      "Recovery = Peak ÷ Trough − 1",
      "$10.8m ÷ $8.1m − 1",
      "= 1.333333 − 1",
      "= 0.333333 = 33.33%",
      "Required recovery ≈ 33.33%",
      "A 25% drawdown needs a 33.33% gain because the recovery is",
      "earned on the smaller $8.1m capital base.",
    ],
    accent: ACCENT,
    thumbLabel: "P32 · Recovery after drawdown",
  },
  {
    id: "yellow-s30",
    number: 30,
    title: "Portal 32 · Avoid hindsight bias",
    subtitle: "A good process can produce a bad outcome, and a poor process can occasionally produce a good one.",
    bullets: [
      "PORTAL 32",
      "A good process can produce a bad outcome, and a poor process can occasionally produce a good one.",
      "Record what information was known at the decision date.",
      "Record alternatives considered.",
      "State what would change the decision.",
      "Reveal the next historical event only after the decision is locked.",
      "Score both the quality of the process and the eventual result.",
    ],
    accent: ACCENT,
    thumbLabel: "P32 · Avoid hindsight bias",
  },
  {
    id: "yellow-s31",
    number: 31,
    title: "Portal 33 · Global Investment Strategy",
    subtitle: "Global investing can diversify economic exposure, but it also introduces currency, country, legal, political",
    bullets: [
      "Portal 33 — Global Investment Strategy",
      "Global investing can diversify economic exposure, but it also introduces currency, country, legal, political",
      "and liquidity risks.",
      "How did the investment perform in",
      "its local market?",
      "Did the foreign currency strengthen",
      "or weaken against the home",
      "currency?",
      "Could politics, capital controls,",
      "inflation or market structure change",
    ],
    accent: ACCENT,
    thumbLabel: "P33 · Global Investment Strategy",
  },
  {
    id: "yellow-s32",
    number: 32,
    title: "Portal 33 · Worked example — Currency-adjusted return",
    subtitle: "Foreign stock +12% in local currency; foreign currency −8% versus home currency.",
    bullets: [
      "PORTAL 33 • WORKED EXAMPLE",
      "Currency-adjusted return",
      "Foreign stock +12% in local currency; foreign currency −8% versus home currency.",
      "Home return = (1 + Local return)(1 + FX return) −",
      "(1.12)(0.92) − 1",
      "= 1.0304 − 1",
      "= 0.0304 = 3.04%",
      "Home-currency return = 3.04%",
      "The stock performed well locally, but most of that gain was offset",
      "because the foreign currency weakened. The home investor",
    ],
    accent: ACCENT,
    thumbLabel: "P33 · Currency-adjusted return",
  },
  {
    id: "yellow-s33",
    number: 33,
    title: "Portal 33 · Country exposure is more than a flag",
    subtitle: "A company's listing country, revenue sources, currency exposure and economic dependencies can all be",
    bullets: [
      "PORTAL 33",
      "A company's listing country, revenue sources, currency exposure and economic dependencies can all be",
      "different.",
      "Measure direct country weights.",
      "Look through multinational revenue exposure.",
      "Assess political stability and rule of law.",
      "Review inflation, monetary credibility and sovereign debt.",
      "Consider capital controls, sanctions and market liquidity.",
    ],
    accent: ACCENT,
    thumbLabel: "P33 · Country exposure is more",
  },
  {
    id: "yellow-s34",
    number: 34,
    title: "Portal 34 · The Fund Mandate",
    subtitle: "GRADUATE FROM PERSONAL INVESTING TO PROFESSIONAL RESPONSIBILITY",
    bullets: [
      "GRADUATE FROM PERSONAL INVESTING TO PROFESSIONAL RESPONSIBILITY",
      "Portal 34 — The Fund Mandate",
      "The $10 million simulated fund is governed by an Investment Policy Statement (IPS). The IPS defines success",
      "and prevents the manager from changing the rules after seeing the outcome.",
      "Objective and return target.",
      "Benchmark.",
      "Maximum drawdown / risk limits.",
      "Minimum liquidity.",
      "Maximum single-name, sector and country exposure.",
      "Currency and leverage rules.",
    ],
    accent: ACCENT,
    thumbLabel: "P34 · The Fund Mandate",
  },
  {
    id: "yellow-s35",
    number: 35,
    title: "Portal 34 · Worked example — Scaling a target allocation",
    subtitle: "$10m fund with a 35% strategic equity target.",
    bullets: [
      "PORTAL 34 • WORKED EXAMPLE",
      "Scaling a target allocation",
      "$10m fund with a 35% strategic equity target.",
      "Dollar allocation = Fund value × Target weight",
      "35% = 0.35",
      "$10,000,000 × 0.35",
      "= $3,500,000",
      "Target equity allocation = $3.5m",
      "The same weight logic used in a small portfolio scales to",
      "professional capital: 35% of the fund is allocated to equities.",
    ],
    accent: ACCENT,
    thumbLabel: "P34 · Scaling a target",
  },
  {
    id: "yellow-s36",
    number: 36,
    title: "Portal 34 · Worked example — Maximum position size",
    subtitle: "$10m fund; maximum single-stock weight = 6%.",
    bullets: [
      "PORTAL 34 • WORKED EXAMPLE",
      "Maximum position size",
      "$10m fund; maximum single-stock weight = 6%.",
      "Maximum position = Fund value × Position limit",
      "6% = 0.06",
      "$10,000,000 × 0.06",
      "= $600,000",
      "Maximum position = $600,000",
      "No single stock may exceed $600,000 at the current fund size.",
      "The rule limits the damage if one thesis is wrong.",
    ],
    accent: ACCENT,
    thumbLabel: "P34 · Maximum position size",
  },
  {
    id: "yellow-s37",
    number: 37,
    title: "Portal 34 · Worked example — Liquidity reserve",
    subtitle: "$10m fund; mandate requires 12% in cash or highly liquid instruments.",
    bullets: [
      "PORTAL 34 • WORKED EXAMPLE",
      "Liquidity reserve",
      "$10m fund; mandate requires 12% in cash or highly liquid instruments.",
      "Reserve = Fund value × Liquidity requirement",
      "12% = 0.12",
      "$10,000,000 × 0.12",
      "= $1,200,000",
      "Minimum liquid reserve = $1.2m",
      "At least $1.2m remains available for obligations, redemptions or",
      "opportunities without forcing the sale of illiquid assets.",
    ],
    accent: ACCENT,
    thumbLabel: "P34 · Liquidity reserve",
  },
  {
    id: "yellow-s38",
    number: 38,
    title: "Portal 35 · Multi-Year Fund Simulation",
    subtitle: "Multi-year management tests whether the process remains usable as prices, interest rates, companies,",
    bullets: [
      "MANAGING WELL ONCE IS NOT ENOUGH",
      "Portal 35 — Multi-Year Fund Simulation",
      "Multi-year management tests whether the process remains usable as prices, interest rates, companies,",
      "currencies and opportunities change.",
      "Research and refresh theses.",
      "Buy, add, hold, trim or sell.",
      "Hedge and rebalance when justified.",
      "Monitor mandate limits.",
      "Record why each material decision changed.",
    ],
    accent: ACCENT,
    thumbLabel: "P35 · Multi-Year Fund Simulation",
  },
  {
    id: "yellow-s39",
    number: 39,
    title: "Portal 35 · Worked example — Geometric return",
    subtitle: "Annual returns: +10%, −5%, +12%. What constant annual rate matches the compounded path?",
    bullets: [
      "PORTAL 35 • WORKED EXAMPLE",
      "Geometric return",
      "Annual returns: +10%, −5%, +12%. What constant annual rate matches the compounded path?",
      "Geometric return = [(1+R₁)(1+R₂)(1+R₃)]^(1/3)",
      "− 1",
      "1.10 × 0.95 × 1.12 = 1.1704",
      "1.1704^(1/3) ≈ 1.05382",
      "1.05382 − 1 = 0.05382",
      "Geometric return ≈ 5.38% per year",
      "The fund compounded as though it had earned about 5.38% every",
    ],
    accent: ACCENT,
    thumbLabel: "P35 · Geometric return",
  },
  {
    id: "yellow-s40",
    number: 40,
    title: "Portal 35 · Worked example — Ending fund value",
    subtitle: "Beginning fund = $10m. Growth factor from +10%, −5%, +12% = 1.1704.",
    bullets: [
      "PORTAL 35 • WORKED EXAMPLE",
      "Ending fund value",
      "Beginning fund = $10m. Growth factor from +10%, −5%, +12% = 1.1704.",
      "Ending value = Beginning value × Growth factor",
      "$10,000,000 × 1.1704",
      "= $11,704,000",
      "Ending value = $11.704m",
      "The sequence of annual returns grows the original $10m to",
      "$11.704m before external flows or fees.",
      "INVESTMENT CONNECTION",
    ],
    accent: ACCENT,
    thumbLabel: "P35 · Ending fund value",
  },
  {
    id: "yellow-s41",
    number: 41,
    title: "Portal 35 · Turnover and decision cadence",
    subtitle: "A manager can monitor continuously without trading continuously. Turnover shows how much of the",
    bullets: [
      "PORTAL 35",
      "A manager can monitor continuously without trading continuously. Turnover shows how much of the",
      "portfolio is being replaced; cadence determines when reviews and actions occur.",
      "MONITOR",
      "Daily/weekly: material events and",
      "risk breaches.",
      "REVIEW",
      "Monthly/quarterly: positioning,",
      "liquidity, earnings and thesis",
      "refresh.",
    ],
    accent: ACCENT,
    thumbLabel: "P35 · Turnover and decision",
  },
  {
    id: "yellow-s42",
    number: 42,
    title: "Portal 36 · Final Investment Committee",
    subtitle: "EXPLAIN THE RESULT, DO NOT MERELY PRESENT IT",
    bullets: [
      "EXPLAIN THE RESULT, DO NOT MERELY PRESENT IT",
      "Portal 36 — Final Investment Committee",
      "The committee evaluates both outcomes and process. Strong returns achieved through hidden",
      "concentration or mandate violations are not automatically strong management.",
      "What was the mandate?",
      "How did the fund perform versus benchmark?",
      "What was the drawdown and risk-adjusted result?",
      "Which positions and allocation decisions drove performance?",
      "What failed?",
      "What was skill, and what may have been luck?",
    ],
    accent: ACCENT,
    thumbLabel: "P36 · Final Investment Committee",
  },
  {
    id: "yellow-s43",
    number: 43,
    title: "Portal 36 · Worked example — Total fund return",
    subtitle: "Fund begins at $10m and ends at $11.3m with no external flows.",
    bullets: [
      "PORTAL 36 • WORKED EXAMPLE",
      "Total fund return",
      "Fund begins at $10m and ends at $11.3m with no external flows.",
      "Return = (Ending − Beginning) ÷ Beginning ×",
      "100%",
      "$11.3m − $10.0m = $1.3m",
      "$1.3m ÷ $10.0m = 0.13",
      "0.13 × 100% = 13.0%",
      "Fund return = 13.0%",
      "The fund increased by 13% over the measurement period. This is",
    ],
    accent: ACCENT,
    thumbLabel: "P36 · Total fund return",
  },
  {
    id: "yellow-s44",
    number: 44,
    title: "Portal 36 · Worked example — Active return",
    subtitle: "Fund return = 13.0%; benchmark return = 9.5%.",
    bullets: [
      "PORTAL 36 • WORKED EXAMPLE",
      "Active return",
      "Fund return = 13.0%; benchmark return = 9.5%.",
      "Active return = Portfolio return − Benchmark return",
      "13.0% − 9.5%",
      "= +3.5 percentage points",
      "Active return = +3.5%",
      "The fund outperformed its benchmark by 3.5 percentage points.",
      "INVESTMENT CONNECTION",
      "The committee must determine why: intended allocation,",
    ],
    accent: ACCENT,
    thumbLabel: "P36 · Active return",
  },
  {
    id: "yellow-s45",
    number: 45,
    title: "Portal 36 · Worked example — Contribution to return",
    subtitle: "Beginning equity weight = 40%; equities return 15%.",
    bullets: [
      "PORTAL 36 • WORKED EXAMPLE",
      "Contribution to return",
      "Beginning equity weight = 40%; equities return 15%.",
      "Approx. contribution = Weight × Asset return",
      "0.40 × 0.15 = 0.060",
      "= 6.0 percentage points",
      "Equity contribution ≈ +6.0 percentage points",
      "The asset's 15% return does not become a 15% portfolio return",
      "because equities were only 40% of the fund. Their approximate",
      "effect on the total fund is 6 percentage points.",
    ],
    accent: ACCENT,
    thumbLabel: "P36 · Contribution to return",
  },
  {
    id: "yellow-s46",
    number: 46,
    title: "Portal 36 · Skill versus luck",
    subtitle: "One successful year cannot prove skill. The committee looks for repeatability, calibration and consistency",
    bullets: [
      "PORTAL 36",
      "One successful year cannot prove skill. The committee looks for repeatability, calibration and consistency",
      "with the mandate.",
      "MORE CONSISTENT WITH SKILL",
      "Repeatable process, calibrated forecasts, controlled risk,",
      "intended theses driving attribution.",
      "MORE CONSISTENT WITH LUCK",
      "One concentrated bet, unexpected factor exposure,",
      "outcomes far beyond the assumptions, rules rewritten after",
      "the fact.",
    ],
    accent: ACCENT,
    thumbLabel: "P36 · Skill versus luck",
  },
  {
    id: "yellow-s47",
    number: 47,
    title: "Portal 36 · Build your investment philosophy",
    subtitle: "A strategy describes what you do. A philosophy explains why you believe that approach can work and how",
    bullets: [
      "PORTAL 36",
      "A strategy describes what you do. A philosophy explains why you believe that approach can work and how",
      "you will behave when uncertainty appears.",
      "Where do you believe attractive opportunities come from?",
      "What evidence do you trust most?",
      "How do valuation and quality interact?",
      "How much concentration is acceptable?",
      "How do you respond to drawdowns?",
      "When is hedging appropriate?",
      "What evidence would make you change your process?",
    ],
    accent: ACCENT,
    thumbLabel: "P36 · Build your investment",
  },
  {
    id: "yellow-s48",
    number: 48,
    title: "The complete Yellow City decision loop",
    subtitle: "By the end of Yellow City, the learner should be able to move through this loop repeatedly without losing the",
    bullets: [
      "INTEGRATION",
      "By the end of Yellow City, the learner should be able to move through this loop repeatedly without losing the",
      "connection between mathematics and judgment.",
      "1. UNDERWRITE",
      "Research → valuation → expected",
      "return → catalyst → falsification.",
      "2. CONSTRUCT",
      "Weight → correlation → risk budget →",
      "constraints → optimize.",
      "3. MANAGE & REVIEW",
    ],
    accent: ACCENT,
    thumbLabel: "The complete Yellow City",
  },
  {
    id: "yellow-s49",
    number: 49,
    title: "Practical checklist · Before you buy — five questions",
    subtitle: "Use these questions to slow the decision down before capital is committed.",
    bullets: [
      "PRACTICAL CHECKLIST",
      "Use these questions to slow the decision down before capital is committed.",
      "What must be true for this investment to work?",
      "What return is implied by my scenarios?",
      "What is the plausible downside if I am wrong?",
      "What does this position add to the existing portfolio?",
      "What evidence will make me reduce or exit?",
    ],
    accent: ACCENT,
    thumbLabel: "Practical checklist · Before",
  },
  {
    id: "yellow-s50",
    number: 50,
    title: "Practical checklist · Before you sell — five questions",
    subtitle: "Selling should be based on forward evidence, not simply whether the position is currently a winner or loser.",
    bullets: [
      "PRACTICAL CHECKLIST",
      "Selling should be based on forward evidence, not simply whether the position is currently a winner or loser.",
      "Has the thesis changed?",
      "Has price moved beyond defensible value?",
      "Has risk breached the mandate?",
      "Is there a materially better use of capital after costs?",
      "Am I reacting to evidence — or to discomfort, FOMO or the desire to break even?",
    ],
    accent: ACCENT,
    thumbLabel: "Practical checklist · Before",
  },
  {
    id: "yellow-s51",
    number: 51,
    title: "Reference · Yellow City formula map",
    subtitle: "Each formula answers a different investment question. Start with the question, then choose the calculation.",
    bullets: [
      "REFERENCE",
      "Each formula answers a different investment question. Start with the question, then choose the calculation.",
      "RETURN",
      "Expected return • portfolio return •",
      "geometric return • active return.",
      "RISK",
      "Variance • volatility • Sharpe •",
      "drawdown • recovery.",
      "ALLOCATION",
      "Position size • country weight •",
    ],
    accent: ACCENT,
    thumbLabel: "Yellow City formula map",
  },
  {
    id: "yellow-s52",
    number: 52,
    title: "Reference · Formula reference — return & valuation",
    subtitle: "Use consistent units: convert percentages to decimals during multiplication and convert back to",
    bullets: [
      "REFERENCE",
      "Use consistent units: convert percentages to decimals during multiplication and convert back to",
      "percentages for interpretation.",
      "Expected return: E(R) = ΣpᵢRᵢ",
      "Upside: (Value − Price) ÷ Price × 100%",
      "Portfolio expected return: ΣwᵢE(Rᵢ)",
      "Geometric return: [Π(1+Rₜ)]^(1/n) − 1",
      "Active return: Rp − Rb",
      "Contribution ≈ Weight × Asset return",
    ],
    accent: ACCENT,
    thumbLabel: "Reference · Formula reference —",
  },
  {
    id: "yellow-s53",
    number: 53,
    title: "Reference · Formula reference — risk & management",
    subtitle: "The formula is only complete when the learner can explain what the result changes in the portfolio.",
    bullets: [
      "REFERENCE",
      "The formula is only complete when the learner can explain what the result changes in the portfolio.",
      "Required recovery: 1/(1−Loss rate) − 1",
      "Two-asset variance: w₁²σ₁² + w₂²σ₂² + 2w₁w₂σ₁σ₂ρ",
      "Sharpe: (Rp − Rf) ÷ σp",
      "Drawdown: (Trough − Peak) ÷ Peak × 100%",
      "Home-currency return: (1+Local)(1+FX) − 1",
      "Maximum position: Fund value × Position limit",
    ],
    accent: ACCENT,
    thumbLabel: "Reference · Formula reference —",
  },
  {
    id: "yellow-s54",
    number: 54,
    title: "Capstone · Final Investment Committee — presentation order",
    subtitle: "A strong committee presentation tells one coherent story from mandate to lessons learned.",
    bullets: [
      "CAPSTONE",
      "A strong committee presentation tells one coherent story from mandate to lessons learned.",
      "1. Mandate, benchmark and constraints.",
      "2. Final allocation and major holdings.",
      "3. Return, active return, drawdown and risk-adjusted performance.",
      "4. Major contributors and detractors.",
      "5. Best and worst decisions.",
      "6. Behavioral and process mistakes.",
      "7. Global/currency and crisis decisions.",
      "8. Skill versus luck.",
    ],
    accent: ACCENT,
    thumbLabel: "Capstone · Final Investment",
  },
  {
    id: "yellow-s55",
    number: 55,
    title: "Master Investor · Complete",
    subtitle: "Mastery does not mean predicting every market move. It means using a repeatable process to make,",
    bullets: [
      "MASTER INVESTOR",
      "Yellow City graduation standard",
      "Mastery does not mean predicting every market move. It means using a repeatable process to make,",
      "measure, revise and defend investment decisions under uncertainty.",
      "YOU CAN EXPLAIN",
      "Every major position has a thesis,",
      "valuation, risk case and exit logic.",
      "YOU CAN CALCULATE",
      "Returns, portfolio risk, recovery,",
      "currency effects, limits and",
    ],
    footer: "Mandate Highlands · Yellow City Master Investor Teaching Deck",
    accent: ACCENT,
    thumbLabel: "Complete",
  },
];

/** Yellow City (Mandate Highlands) Master Investor classroom — portals 28–36. */
export const YELLOW_CITY_CLASSROOM: ClassroomLesson = {
  id: "yellow-city-master-investor",
  areaId: "mandate-highlands",
  themeColor: ACCENT,
  themeColorDeep: ACCENT_DEEP,
  subject: "Mastery",
  topic: "Yellow City Master Investor",
  title: "Lesson: Yellow City Master Investor",
  classId: "high-class-yellow",
  moduleStart: 28,
  moduleEnd: 36,
  outline: [],
  slides: SLIDES,
  notesHref: "/library/mandate-highlands/yellow-city-master-investor-notes.pdf",
  notesDownloadName: "yellow-city-master-investor-connected-explanations-notes.pdf",
  deckHref: "/library/mandate-highlands/yellow-city-master-investor-teaching-deck.pdf",
  deckDownloadName: "yellow-city-master-investor-teaching-deck.pdf",
  linkedSites: [
    {
      id: "link-investor-gov-process",
      title: "Investor.gov — Investing Basics",
      url: "https://www.investor.gov/introduction-investing/investing-basics",
      platform: "web",
    },
  ],
  quote: {
    text: "Risk comes from not knowing what you are doing.",
    author: "Warren Buffett",
  },
};
