import type { ClassroomLesson, ClassroomSlide } from "@/lib/content/classroom";

const ACCENT = "#43a047";
const ACCENT_DEEP = "#2e7d32";

const SLIDES: ClassroomSlide[] = [
  {
    id: "green-s1",
    number: 1,
    title: "Green City · Portfolio Management",
    subtitle: "Learn how to manage and adapt an evolving portfolio as markets, risks and information change.",
    bullets: [
      "AI Investment Simulator teaching deck for Signal Quay (Green City).",
      "Nine portals: bonds, ETFs, allocation, diversification, and crisis management.",
      "START — understand each new portfolio tool.",
      "BUILD — calculate before making decisions.",
      "CAPABILITY — adapt without abandoning discipline.",
    ],
    footer: "Signal Quay · Green City Portfolio Management Teaching Deck",
    accent: ACCENT,
    thumbLabel: "Title",
  },
  {
    id: "green-s2",
    number: 2,
    title: "Where Green City fits",
    subtitle: "Green City assumes the portfolio already exists. Your job is now to manage the whole system.",
    bullets: [
      "PURPLE CITY",
      "Learn how to invest: foundations.",
      "BLUE CITY",
      "Learn what to invest in: analysis and selection.",
      "GREEN CITY",
      "Learn how to manage and adapt the portfolio.",
      "YELLOW CITY",
      "Prove you can manage professionally.",
    ],
    accent: ACCENT,
    thumbLabel: "Where it fits",
  },
  {
    id: "green-s3",
    number: 3,
    title: "How to learn from this deck",
    subtitle: "Every calculation is taught as a decision tool, not as isolated mathematics.",
    bullets: [
      "1 UNDERSTAND",
      "What does the idea mean?",
      "2 FORMULA",
      "What relationship are we measuring?",
      "3 SUBSTITUTE",
      "Where do the actual numbers go?",
      "4 CALCULATE — show every important step.",
      "5 INTERPRET — translate the answer into plain English.",
      "6 MANAGE — what does it change in the portfolio?",
    ],
    accent: ACCENT,
    thumbLabel: "How to learn",
  },
  {
    id: "green-s4",
    number: 4,
    title: "Green City roadmap",
    subtitle: "Nine portals turn individual investments into an actively managed portfolio.",
    bullets: [
      "19 Bonds",
      "20 ETFs & Alternatives",
      "21 Allocation",
      "22 Diversification",
      "23 Add / Trim / Exit",
      "24 Macro",
      "25 New Information",
      "26 Risk",
      "27 Crisis",
    ],
    accent: ACCENT,
    thumbLabel: "Roadmap",
  },
  {
    id: "green-s5",
    number: 5,
    title: "The Green City management mindset",
    subtitle: "A good asset can still create a bad portfolio if it is badly sized or badly combined.",
    bullets: [
      "RETURN",
      "What can this holding contribute?",
      "RISK",
      "How can it hurt the portfolio?",
      "LIQUIDITY",
      "Can capital be accessed when needed?",
      "CORRELATION",
      "What else tends to move with it?",
      "CASH FLOW",
      "Does it generate or consume cash?",
    ],
    accent: ACCENT,
    thumbLabel: "Mindset",
  },
  {
    id: "green-s6",
    number: 6,
    title: "Portal 19 · Bonds & Fixed Income",
    subtitle: "Understand government and corporate bonds, yields, duration, credit risk and interest-rate sensitivity.",
    bullets: [
      "Portal 19 of Green City Portfolio Management.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Bonds",
  },
  {
    id: "green-s7",
    number: 7,
    title: "Bond basics",
    subtitle: "A bondholder is mainly a creditor, not an owner.",
    bullets: [
      "BOND",
      "A loan made by the investor to a government or company.",
      "FACE VALUE",
      "Principal normally repaid at maturity.",
      "COUPON RATE",
      "Contractual interest rate applied to face value.",
      "MATURITY",
      "Date principal is due.",
      "MARKET PRICE",
      "What investors pay for the bond today.",
    ],
    accent: ACCENT,
    thumbLabel: "Bond basics",
  },
  {
    id: "green-s8",
    number: 8,
    title: "Coupon payment",
    subtitle: "Face value $1,000; annual coupon rate 6%.",
    bullets: [
      "Annual coupon = Face value × Coupon rate",
      "Contractual annual cash interest.",
      "WORK IT STEP BY STEP",
      "6% = 0.06 · Coupon = $1,000 × 0.06",
      "Answer: $60 per year",
      "Useful for income planning, but market value can still rise or fall.",
    ],
    accent: ACCENT,
    thumbLabel: "Coupon payment",
  },
  {
    id: "green-s9",
    number: 9,
    title: "Current yield",
    subtitle: "Annual coupon $60; bond price $950.",
    bullets: [
      "Current yield = Annual coupon / Market price × 100%",
      "Coupon income relative to today’s purchase price.",
      "WORK IT STEP BY STEP",
      "$60 / $950 = 0.0631579 · 0.0631579 × 100% = 6.31579%",
      "Answer: ≈ 6.32%",
      "Not the same as total return or yield to maturity because it ignores maturity value and timing.",
    ],
    accent: ACCENT,
    thumbLabel: "Current yield",
  },
  {
    id: "green-s10",
    number: 10,
    title: "Holding-period return",
    subtitle: "Buy at $980; receive $50 coupon; sell at $1,005.",
    bullets: [
      "HPR = (Coupon + Ending price − Beginning price) / Beginning price × 100%",
      "Coupon income plus price change over the holding period.",
      "WORK IT STEP BY STEP",
      "Price gain = $1,005 − $980 = $25 · Total gain = $50 + $25 = $75",
      "Answer: ≈ 7.65%",
      "Bond return is not only the coupon. Market-price movement matters.",
    ],
    accent: ACCENT,
    thumbLabel: "Holding-period r",
  },
  {
    id: "green-s11",
    number: 11,
    title: "Why bond prices and yields move in opposite directions",
    subtitle: "This inverse relationship is one of the most important fixed-income ideas.",
    bullets: [
      "RATES RISE",
      "New bonds can offer more attractive returns. Existing lower-paying bonds must",
      "become cheaper to compete.",
      "RATES FALL",
      "Existing higher-paying fixed coupons become more attractive, supporting higher",
      "prices.",
      "PRICE ADJUSTS",
      "The bond’s promised coupon is fixed, so market price does much of the",
      "adjustment.",
      "PORTFOLIO EFFECT",
    ],
    accent: ACCENT,
    thumbLabel: "Why bond",
  },
  {
    id: "green-s12",
    number: 12,
    title: "Duration: rate rise",
    subtitle: "Modified duration 5.2; yield rises 0.75 percentage points.",
    bullets: [
      "Approx. %ΔPrice ≈ −Modified duration × ΔYield",
      "Approximate sensitivity of price to a small yield change.",
      "WORK IT STEP BY STEP",
      "0.75% = 0.0075 · %ΔPrice ≈ −5.2 × 0.0075",
      "Answer: ≈ 3.9% price decline",
      "Higher duration means greater interest-rate sensitivity; the estimate ignores convexity.",
    ],
    accent: ACCENT,
    thumbLabel: "Duration",
  },
  {
    id: "green-s13",
    number: 13,
    title: "Duration: rate fall",
    subtitle: "Modified duration 7.0; yield falls 0.40 percentage points.",
    bullets: [
      "Approx. %ΔPrice ≈ −Duration × ΔYield",
      "The negative sign captures the inverse price/yield relationship.",
      "WORK IT STEP BY STEP",
      "ΔYield = −0.40% = −0.0040 · −7.0 × (−0.0040) = +0.028",
      "Answer: ≈ 2.8% price increase",
      "Duration helps balance income objectives against rate sensitivity.",
    ],
    accent: ACCENT,
    thumbLabel: "Duration",
  },
  {
    id: "green-s14",
    number: 14,
    title: "Credit spread",
    subtitle: "Corporate yield 6.4%; comparable government yield 4.1%.",
    bullets: [
      "Credit spread = Corporate yield − Government yield",
      "Extra yield offered above the government benchmark.",
      "WORK IT STEP BY STEP",
      "6.4% − 4.1% = 2.3 percentage points · 2.3 percentage points = 230 basis points",
      "Answer: 2.3% = 230 bps",
      "A wider spread can be compensation for credit risk—or a warning of stress.",
    ],
    accent: ACCENT,
    thumbLabel: "Credit spread",
  },
  {
    id: "green-s15",
    number: 15,
    title: "What bonds can contribute",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "INCOME",
      "Coupons can provide planned cash flow.",
      "STABILITY",
      "High-quality short bonds may fluctuate less than equities.",
      "DIVERSIFICATION",
      "Some bonds can behave differently from stocks in stress.",
      "LIABILITY MATCHING",
      "Maturities can align with future cash needs.",
      "LIQUIDITY",
      "Some government markets are deep and tradable.",
    ],
    accent: ACCENT,
    thumbLabel: "What bonds",
  },
  {
    id: "green-s16",
    number: 16,
    title: "Portal 20 · ETFs, Commodities & Alternatives",
    subtitle: "Broaden the toolkit using pooled and alternative exposures without buying every underlying asset directly.",
    bullets: [
      "Portal 20 of Green City Portfolio Management.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "ETFs, Commodities",
  },
  {
    id: "green-s17",
    number: 17,
    title: "What an ETF actually does",
    subtitle: "The label “ETF” describes the vehicle—not the risk inside it.",
    bullets: [
      "POOL",
      "Combines investor money into a portfolio that trades on an exchange.",
      "EXPOSURE",
      "Can track broad markets, sectors, bonds, commodities, factors or active",
      "strategies.",
      "HOLDINGS",
      "Always ask what the fund really owns.",
      "COST",
      "Expense ratio and trading spread reduce investor return.",
      "TRACKING",
    ],
    accent: ACCENT,
    thumbLabel: "What an",
  },
  {
    id: "green-s18",
    number: 18,
    title: "ETF expense ratio",
    subtitle: "Investment $8,000; expense ratio 0.25%.",
    bullets: [
      "Approx. annual fee = Investment × Expense ratio",
      "Approximate annual fund operating cost on the investment.",
      "WORK IT STEP BY STEP",
      "0.25% = 0.0025 · $8,000 × 0.0025 = $20",
      "Answer: ≈ $20 per year",
      "Small annual differences can compound over long holding periods.",
    ],
    accent: ACCENT,
    thumbLabel: "ETF expense ratio",
  },
  {
    id: "green-s19",
    number: 19,
    title: "Tracking difference",
    subtitle: "Index return 9.2%; ETF return 8.9%.",
    bullets: [
      "Tracking difference = ETF return − Benchmark return",
      "How the fund’s return differed from the intended benchmark.",
      "WORK IT STEP BY STEP",
      "8.9% − 9.2% = −0.3 percentage points",
      "Answer: −0.30 percentage points",
      "Fees, trading costs, cash drag and imperfect replication can contribute.",
    ],
    accent: ACCENT,
    thumbLabel: "Tracking differe",
  },
  {
    id: "green-s20",
    number: 20,
    title: "What moves commodities?",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "SUPPLY",
      "Production cuts, mine closures, crop failures.",
      "DEMAND",
      "Industry, construction, transport and consumption.",
      "INVENTORIES",
      "Low stocks can make shocks more powerful.",
      "WEATHER",
      "Important for agriculture and energy demand.",
      "GEOPOLITICS",
      "Sanctions, conflict and shipping disruption.",
    ],
    accent: ACCENT,
    thumbLabel: "What moves",
  },
  {
    id: "green-s21",
    number: 21,
    title: "Commodity price return",
    subtitle: "Gold rises from $2,000 to $2,140 per ounce.",
    bullets: [
      "Price return = (Ending price − Beginning price) / Beginning price × 100%",
      "Change in the commodity price before vehicle costs.",
      "WORK IT STEP BY STEP",
      "Price change = $2,140 − $2,000 = $140 · $140 / $2,000 = 0.07",
      "Answer: 7.0%",
      "Commodity exposure may diversify some inflation/geopolitical risks but can be volatile.",
    ],
    accent: ACCENT,
    thumbLabel: "Commodity price",
  },
  {
    id: "green-s22",
    number: 22,
    title: "Direct ownership vs pooled exposure",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "STOCKS",
      "Individual shares vs a basket of companies.",
      "BONDS",
      "Specific issuer/maturity vs diversified bond fund.",
      "GOLD",
      "Physical bullion/storage vs liquid fund exposure.",
      "PROPERTY",
      "Direct property/management vs a REIT or REIT ETF.",
      "COMMODITIES",
      "Physical ownership can be impractical; funds may use futures.",
    ],
    accent: ACCENT,
    thumbLabel: "Direct ownership",
  },
  {
    id: "green-s23",
    number: 23,
    title: "Portal 21 · Strategic Asset Allocation",
    subtitle: "Set long-term target weights based on objectives, horizon, liquidity needs and risk capacity.",
    bullets: [
      "Portal 21 of Green City Portfolio Management.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Strategic Asset",
  },
  {
    id: "green-s24",
    number: 24,
    title: "Allocation is the portfolio’s architecture",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "WEIGHTS CREATE SCALE",
      "A $4,000 holding means different things in a $5,000 versus $100,000 portfolio.",
      "OBJECTIVES FIRST",
      "Return goals must coexist with liquidity and loss capacity.",
      "STRATEGIC",
      "Long-term target structure.",
      "TACTICAL",
      "Temporary deviation based on a specific view.",
      "DISCIPLINE",
      "Targets make later rebalancing measurable.",
    ],
    accent: ACCENT,
    thumbLabel: "Allocation is",
  },
  {
    id: "green-s25",
    number: 25,
    title: "Portfolio weight",
    subtitle: "$14,800 portfolio; stocks worth $4,440.",
    bullets: [
      "Weight = Asset value / Portfolio value × 100%",
      "Share of total capital currently committed to stocks.",
      "WORK IT STEP BY STEP",
      "$4,440 / $14,800 = 0.30 · 0.30 × 100% = 30%",
      "Answer: 30% stock weight",
      "Weights are the common language for comparing portfolio exposures.",
    ],
    accent: ACCENT,
    thumbLabel: "Portfolio weight",
  },
  {
    id: "green-s26",
    number: 26,
    title: "Target dollars",
    subtitle: "$14,800 portfolio; target bond weight 25%.",
    bullets: [
      "Target value = Portfolio value × Target weight",
      "Converts a policy percentage into an implementable dollar target.",
      "WORK IT STEP BY STEP",
      "25% = 0.25 · $14,800 × 0.25 = $3,700",
      "Answer: $3,700 in bonds",
      "Needed before comparing current holdings with desired allocation.",
    ],
    accent: ACCENT,
    thumbLabel: "Target dollars",
  },
  {
    id: "green-s27",
    number: 27,
    title: "Expected portfolio return",
    subtitle: "50% stocks at 8%; 30% bonds at 4%; 20% cash at 2%.",
    bullets: [
      "E(Rp) = Σ wᵢE(Rᵢ)",
      "Weighted combination of expected asset returns.",
      "WORK IT STEP BY STEP",
      "Stocks: 0.50×8% = 4.00% · Bonds: 0.30×4% = 1.20%",
      "Answer: 5.60% expected return",
      "Expected return is an assumption-based planning measure—not a promise.",
    ],
    accent: ACCENT,
    thumbLabel: "Expected portfolio",
  },
  {
    id: "green-s28",
    number: 28,
    title: "Rebalancing amount",
    subtitle: "Bond target $3,700; current bonds $3,150.",
    bullets: [
      "Trade = Target value − Current value",
      "Difference between desired and actual dollar exposure.",
      "WORK IT STEP BY STEP",
      "$3,700 − $3,150 = +$550",
      "Answer: Buy/add $550",
      "Rebalancing reconnects the real portfolio to the policy target.",
    ],
    accent: ACCENT,
    thumbLabel: "Rebalancing amount",
  },
  {
    id: "green-s29",
    number: 29,
    title: "Example strategic allocation",
    subtitle: "Illustrative allocation from the notes—not a universal recommendation.",
    bullets: [
      "STOCKS 30%",
      "$4,440",
      "BONDS 25%",
      "$3,700",
      "REAL ESTATE 15%",
      "$2,220",
      "DIVERSIFIED ETF 10%",
      "$1,480",
      "ALTERNATIVES 5%",
      "$740",
    ],
    accent: ACCENT,
    thumbLabel: "Example strategic",
  },
  {
    id: "green-s30",
    number: 30,
    title: "Portal 22 · Portfolio Diversification",
    subtitle: "Identify hidden concentrations by examining correlation, sector, geography, currency and liquidity.",
    bullets: [
      "Portal 22 of Green City Portfolio Management.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Portfolio Divers",
  },
  {
    id: "green-s31",
    number: 31,
    title: "Diversification is not “own many things”",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "NAMES ≠ RISKS",
      "Ten technology stocks can still be one concentrated bet.",
      "SECTOR",
      "How much depends on one industry?",
      "GEOGRAPHY",
      "How much depends on one economy?",
      "CURRENCY",
      "Foreign assets add exchange-rate exposure.",
      "LIQUIDITY",
      "Can enough capital be accessed in a crisis?",
    ],
    accent: ACCENT,
    thumbLabel: "Diversification is",
  },
  {
    id: "green-s32",
    number: 32,
    title: "Sector concentration",
    subtitle: "Technology exposure $6,216; portfolio $14,800.",
    bullets: [
      "Sector weight = Sector exposure / Portfolio value × 100%",
      "Percentage of portfolio tied to one broad sector.",
      "WORK IT STEP BY STEP",
      "$6,216 / $14,800 = 0.42 · 0.42 × 100% = 42%",
      "Answer: 42% technology exposure",
      "Ask whether this concentration is intentional and adequately rewarded.",
    ],
    accent: ACCENT,
    thumbLabel: "Sector concentra",
  },
  {
    id: "green-s33",
    number: 33,
    title: "Correlation made simple",
    subtitle: "Diversification improves when risks do not all respond identically.",
    bullets: [
      "+1",
      "Assets move perfectly together.",
      "POSITIVE",
      "They often move in the same direction.",
      "No linear relationship in the sample.",
      "NEGATIVE",
      "They often move in opposite directions.",
      "−1",
      "Perfect opposite movement.",
      "IMPORTANT",
    ],
    accent: ACCENT,
    thumbLabel: "Correlation made",
  },
  {
    id: "green-s34",
    number: 34,
    title: "Two-asset portfolio volatility",
    subtitle: "60% A, 40% B; σA=15%, σB=10%; correlation=0.20.",
    bullets: [
      "σp² = wA²σA² + wB²σB² + 2wAwBσAσBρ",
      "Combined risk depends on both individual volatility and correlation.",
      "WORK IT STEP BY STEP",
      "Term 1 = (0.60²)(0.15²) = 0.00810 · Term 2 = (0.40²)(0.10²) = 0.00160",
      "Answer: ≈ 10.56% volatility",
      "Lower correlation can reduce total portfolio volatility.",
    ],
    accent: ACCENT,
    thumbLabel: "Two-asset portfo",
  },
  {
    id: "green-s35",
    number: 35,
    title: "What if correlation rises?",
    subtitle: "Same portfolio, but correlation rises from 0.20 to 0.90.",
    bullets: [
      "σp² = wA²σA² + wB²σB² + 2wAwBσAσBρ",
      "The portfolio becomes riskier when assets move more closely together.",
      "WORK IT STEP BY STEP",
      "Term 1 = 0.00810 · Term 2 = 0.00160",
      "Answer: ≈ 12.72% volatility",
      "Diversification benefits can weaken in a crisis.",
    ],
    accent: ACCENT,
    thumbLabel: "What if",
  },
  {
    id: "green-s36",
    number: 36,
    title: "Foreign asset + currency",
    subtitle: "Foreign stock +8%; foreign currency +5% vs home currency.",
    bullets: [
      "Domestic return = (1 + Local return)(1 + FX return) − 1",
      "Combines local asset performance with currency movement.",
      "WORK IT STEP BY STEP",
      "(1+0.08)(1+0.05) − 1 · 1.08 × 1.05 − 1",
      "Answer: 13.4% domestic return",
      "Global diversification requires tracking both asset and FX exposure.",
    ],
    accent: ACCENT,
    thumbLabel: "Foreign asset",
  },
  {
    id: "green-s37",
    number: 37,
    title: "Liquidity is part of diversification",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "CASH / T-BILLS",
      "Usually accessible quickly.",
      "LARGE STOCKS / ETFs",
      "Often liquid, but spreads can widen.",
      "CORPORATE BONDS",
      "Liquidity varies by issue.",
      "DIRECT PROPERTY",
      "Sale can take months.",
      "PRIVATE BUSINESS",
      "Buyer may be difficult to find.",
    ],
    accent: ACCENT,
    thumbLabel: "Liquidity is",
  },
  {
    id: "green-s38",
    number: 38,
    title: "Portal 23 · Add, Trim or Exit",
    subtitle: "Turn portfolio diagnosis into disciplined action rather than emotional trading.",
    bullets: [
      "Portal 23 of Green City Portfolio Management.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Add, Trim or Exit",
  },
  {
    id: "green-s39",
    number: 39,
    title: "Five core management decisions",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "ADD",
      "Increase when evidence strengthens, valuation improves or position is below",
      "target.",
      "HOLD",
      "Keep deliberately when thesis and sizing remain appropriate.",
      "TRIM",
      "Reduce because valuation, concentration or risk has risen.",
      "EXIT",
      "Close when thesis breaks or risk becomes unacceptable.",
      "REPLACE",
    ],
    accent: ACCENT,
    thumbLabel: "Five core",
  },
  {
    id: "green-s40",
    number: 40,
    title: "Rebalancing band",
    subtitle: "Target stock weight 30%; allowed deviation ±5 percentage points.",
    bullets: [
      "Upper = Target + deviation; Lower = Target − deviation",
      "Tolerance range around the target.",
      "WORK IT STEP BY STEP",
      "Upper = 30% + 5% = 35% · Lower = 30% − 5% = 25%",
      "Answer: 25% to 35% band",
      "Bands reduce needless trading while creating a pre-agreed action rule.",
    ],
    accent: ACCENT,
    thumbLabel: "Rebalancing band",
  },
  {
    id: "green-s41",
    number: 41,
    title: "Trim to target",
    subtitle: "Portfolio $16,000; stock position $6,000; target 30%.",
    bullets: [
      "Target value = Portfolio × Target weight; Trim = Current − Target",
      "Amount required to return the position to its target weight.",
      "WORK IT STEP BY STEP",
      "Target = $16,000 × 0.30 = $4,800 · Trim = $6,000 − $4,800 = $1,200",
      "Answer: Trim $1,200",
      "A trim can reduce concentration without declaring the thesis wrong.",
    ],
    accent: ACCENT,
    thumbLabel: "Trim to target",
  },
  {
    id: "green-s42",
    number: 42,
    title: "Remaining valuation upside",
    subtitle: "Estimated value $72; current price $66.",
    bullets: [
      "Upside = (Value − Price) / Price × 100%",
      "Remaining gap between market price and estimated value.",
      "WORK IT STEP BY STEP",
      "Difference = $72 − $66 = $6 · $6 / $66 = 0.090909",
      "Answer: ≈ 9.09% upside",
      "A good company may become less attractive when the valuation gap narrows.",
    ],
    accent: ACCENT,
    thumbLabel: "Remaining valuat",
  },
  {
    id: "green-s43",
    number: 43,
    title: "Capital rotation",
    subtitle: "Current holding expected return 5%; new opportunity 9%.",
    bullets: [
      "Relative advantage = New E(R) − Current E(R)",
      "Estimated expected-return advantage of the alternative.",
      "WORK IT STEP BY STEP",
      "9% − 5% = 4 percentage points",
      "Answer: 4 percentage points",
      "Also consider risk, liquidity, taxes, costs and forecast uncertainty.",
    ],
    accent: ACCENT,
    thumbLabel: "Capital rotation",
  },
  {
    id: "green-s44",
    number: 44,
    title: "What can break a thesis?",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "ECONOMICS",
      "Revenue or cash-flow driver weakens structurally.",
      "ADVANTAGE",
      "Competitive position deteriorates.",
      "BALANCE SHEET",
      "Debt/refinancing risk rises materially.",
      "MANAGEMENT",
      "Credibility or execution worsens.",
      "REGULATION",
      "Rules damage access, costs or profitability.",
    ],
    accent: ACCENT,
    thumbLabel: "What can",
  },
  {
    id: "green-s45",
    number: 45,
    title: "Portal 24 · Macroeconomics for Investors",
    subtitle: "Use the economic environment to understand forces acting across several portfolio holdings at once.",
    bullets: [
      "Portal 24 of Green City Portfolio Management.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Macroeconomics for",
  },
  {
    id: "green-s46",
    number: 46,
    title: "The macro dashboard",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "GDP",
      "Is economic activity accelerating or slowing?",
      "INFLATION",
      "Are prices rising faster or slower?",
      "INTEREST RATES",
      "How expensive is capital?",
      "UNEMPLOYMENT",
      "How strong is labor demand and household income?",
      "FISCAL POLICY",
      "Is government policy stimulating or restraining demand?",
    ],
    accent: ACCENT,
    thumbLabel: "The macro",
  },
  {
    id: "green-s47",
    number: 47,
    title: "Approximate real rate",
    subtitle: "Nominal rate 5.5%; inflation 3.2%.",
    bullets: [
      "Approx. real rate ≈ Nominal rate − Inflation",
      "Simple inflation-adjusted rate approximation.",
      "WORK IT STEP BY STEP",
      "5.5% − 3.2% = 2.3%",
      "Answer: ≈ +2.3%",
      "Higher real rates can tighten financial conditions and pressure long-duration assets.",
    ],
    accent: ACCENT,
    thumbLabel: "Approximate real",
  },
  {
    id: "green-s48",
    number: 48,
    title: "Exact real rate",
    subtitle: "Nominal rate 5.5%; inflation 3.2%.",
    bullets: [
      "Real = (1 + Nominal) / (1 + Inflation) − 1",
      "More precise inflation adjustment using the Fisher relationship.",
      "WORK IT STEP BY STEP",
      "1.055 / 1.032 − 1 · = 1.0222868 − 1",
      "Answer: ≈ 2.23%",
      "Use exact calculation when precision matters or rates/inflation are high.",
    ],
    accent: ACCENT,
    thumbLabel: "Exact real rate",
  },
  {
    id: "green-s49",
    number: 49,
    title: "Yield-curve spread",
    subtitle: "10-year yield 4.0%; 2-year yield 4.7%.",
    bullets: [
      "Term spread = Long-term yield − Short-term yield",
      "Selected curve segment is inverted.",
      "WORK IT STEP BY STEP",
      "4.0% − 4.7% = −0.7 percentage points · = −70 basis points",
      "Answer: −0.70% = −70 bps",
      "Investigate policy and growth expectations; inversion is a signal, not a guaranteed recession timer.",
    ],
    accent: ACCENT,
    thumbLabel: "Yield-curve spread",
  },
  {
    id: "green-s50",
    number: 50,
    title: "How inflation can affect assets",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "CASH",
      "Purchasing power can erode if yield lags inflation.",
      "NOMINAL BONDS",
      "Fixed payments lose real value; rising yields can reduce price.",
      "STOCKS",
      "Depends on pricing power, input costs and valuation.",
      "REAL ESTATE",
      "Rents may rise, but financing costs can also rise.",
      "COMMODITIES",
      "Some react strongly to supply shocks and inflation.",
    ],
    accent: ACCENT,
    thumbLabel: "How inflation",
  },
  {
    id: "green-s51",
    number: 51,
    title: "Economic cycle: ask different questions",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "EXPANSION",
      "Growth strong: are cyclicals and credit risks underpriced?",
      "LATE CYCLE",
      "Inflation/rates may rise: is leverage becoming dangerous?",
      "SLOWDOWN / RECESSION",
      "Which earnings are cyclical? Is liquidity sufficient?",
      "RECOVERY",
      "Where are prices still reflecting recession conditions?",
    ],
    accent: ACCENT,
    thumbLabel: "Economic cycle",
  },
  {
    id: "green-s52",
    number: 52,
    title: "Portal 25 · Earnings, News & New Information",
    subtitle: "Separate thesis-changing evidence from market noise by comparing new facts with prior expectations.",
    bullets: [
      "Portal 25 of Green City Portfolio Management.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Earnings, News",
  },
  {
    id: "green-s53",
    number: 53,
    title: "Markets react to surprise—not simply “good” or “bad”",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "EXPECTATIONS",
      "A record result can disappoint if investors expected even more.",
      "SOURCE",
      "Prefer primary, credible evidence.",
      "CASH FLOW",
      "Does the news change future cash generation?",
      "RISK",
      "Does it change the probability or severity of loss?",
      "VALUATION",
      "Does the value estimate need revision?",
    ],
    accent: ACCENT,
    thumbLabel: "Markets react",
  },
  {
    id: "green-s54",
    number: 54,
    title: "Earnings surprise",
    subtitle: "Actual EPS $2.10; consensus expected $1.95.",
    bullets: [
      "Surprise % = (Actual − Expected) / |Expected| × 100%",
      "Reported EPS exceeded consensus by about 7.69%.",
      "WORK IT STEP BY STEP",
      "Difference = $2.10 − $1.95 = $0.15 · $0.15 / $1.95 = 0.076923",
      "Answer: ≈ +7.69%",
      "Now investigate whether the beat is sustainable or driven by temporary/accounting factors.",
    ],
    accent: ACCENT,
    thumbLabel: "Earnings surprise",
  },
  {
    id: "green-s55",
    number: 55,
    title: "Guidance revision",
    subtitle: "Old revenue guide $980m–$1.02bn; new $1.04bn–$1.10bn.",
    bullets: [
      "Midpoint = (Low + High)/2; Change = (New − Old)/Old ×100%",
      "Management raised its central revenue expectation materially.",
      "WORK IT STEP BY STEP",
      "Old midpoint = ($980m+$1,020m)/2 = $1,000m · New midpoint = ($1,040m+$1,100m)/2 = $1,070m",
      "Answer: Guidance midpoint +7.0%",
      "A weak-growth thesis may need revision if the new guidance is credible.",
    ],
    accent: ACCENT,
    thumbLabel: "Guidance revision",
  },
  {
    id: "green-s56",
    number: 56,
    title: "Event return",
    subtitle: "Stock $50 before earnings; $46 after.",
    bullets: [
      "Event return = (Post-event price − Pre-event price) / Pre-event price × 100%",
      "Measures the market price reaction around the event.",
      "WORK IT STEP BY STEP",
      "Change = $46 − $50 = −$4 · −$4 / $50 = −0.08",
      "Answer: −8.0%",
      "It does not prove the market is right. Identify what expectation changed.",
    ],
    accent: ACCENT,
    thumbLabel: "Event return",
  },
  {
    id: "green-s57",
    number: 57,
    title: "Information triage: seven questions",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "What exactly changed?",
      "Is the source primary and credible?",
      "Was it already expected?",
      "Does it alter cash flow, risk, valuation or financing?",
      "Temporary or structural?",
      "One holding or the whole portfolio?",
      "Does the action change: ADD, HOLD, TRIM, EXIT—or no action?",
      "DISCIPLINE",
      "A price move alone is not a thesis.",
    ],
    accent: ACCENT,
    thumbLabel: "Information triage",
  },
  {
    id: "green-s58",
    number: 58,
    title: "Portal 26 · Risk Management & Stress Testing",
    subtitle: "Measure different dimensions of risk and test how the portfolio might behave under adverse scenarios.",
    bullets: [
      "Portal 26 of Green City Portfolio Management.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Risk Management",
  },
  {
    id: "green-s59",
    number: 59,
    title: "Risk has more than one meaning",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "VOLATILITY",
      "How widely returns vary.",
      "BETA",
      "Sensitivity to broad market movement.",
      "DRAWDOWN",
      "Peak-to-trough loss.",
      "SHARPE",
      "Excess return per unit of volatility.",
      "VaR",
      "Model-based loss threshold under assumptions.",
    ],
    accent: ACCENT,
    thumbLabel: "Risk has",
  },
  {
    id: "green-s60",
    number: 60,
    title: "Average return",
    subtitle: "Monthly returns: 2%, −1%, 3%, 0%, 1%.",
    bullets: [
      "Arithmetic mean = ΣRᵢ / n",
      "Central arithmetic return across observations.",
      "WORK IT STEP BY STEP",
      "Sum = 2% −1% +3% +0% +1% = 5% · n = 5",
      "Answer: 1% average monthly return",
      "Average return alone does not tell you how unstable the path was.",
    ],
    accent: ACCENT,
    thumbLabel: "Average return",
  },
  {
    id: "green-s61",
    number: 61,
    title: "Sample volatility",
    subtitle: "Returns: 2%, −1%, 3%, 0%, 1%; mean = 1%.",
    bullets: [
      "s² = Σ(Rᵢ−R̄)²/(n−1); s = √s²",
      "Historical spread of returns around the mean.",
      "WORK IT STEP BY STEP",
      "Deviations: 1%, −2%, 2%, −1%, 0% · Decimals squared: .0001,.0004,.0004,.0001,0",
      "Answer: ≈ 1.58% monthly volatility",
      "Higher volatility means wider variation, but does not capture every form of risk.",
    ],
    accent: ACCENT,
    thumbLabel: "Sample volatility",
  },
  {
    id: "green-s62",
    number: 62,
    title: "Beta interpretation",
    subtitle: "Stock beta 1.30; market rises 4%.",
    bullets: [
      "Approx. market-driven move ≈ Beta × Market move",
      "Simplified market-related sensitivity estimate.",
      "WORK IT STEP BY STEP",
      "1.30 × 4% = 5.2%",
      "Answer: ≈ +5.2%",
      "Beta is not an exact return forecast and excludes company- specific news.",
    ],
    accent: ACCENT,
    thumbLabel: "Beta interpretat",
  },
  {
    id: "green-s63",
    number: 63,
    title: "Drawdown",
    subtitle: "Portfolio peak $18,000; trough $14,400.",
    bullets: [
      "Drawdown = (Trough − Peak) / Peak × 100%",
      "Loss from the prior peak to the trough.",
      "WORK IT STEP BY STEP",
      "Loss = $14,400 − $18,000 = −$3,600 · −$3,600/$18,000 = −0.20",
      "Answer: −20% drawdown",
      "Drawdown expresses the decline an investor actually had to endure.",
    ],
    accent: ACCENT,
    thumbLabel: "Drawdown",
  },
  {
    id: "green-s64",
    number: 64,
    title: "Recovery after drawdown",
    subtitle: "Recover from $14,400 back to $18,000.",
    bullets: [
      "Recovery return = Peak / Trough − 1",
      "Losses and recoveries are asymmetric because recovery starts from a smaller base.",
      "WORK IT STEP BY STEP",
      "$18,000/$14,400 = 1.25 · 1.25 − 1 = 0.25",
      "Answer: 25% required gain",
      "A 20% loss requires a 25% gain to get back to the original peak.",
    ],
    accent: ACCENT,
    thumbLabel: "Recovery after",
  },
  {
    id: "green-s65",
    number: 65,
    title: "Sharpe ratio",
    subtitle: "Portfolio return 9%; risk-free 3%; volatility 12%.",
    bullets: [
      "Sharpe = (Rp − Rf) / σp",
      "Excess return earned per unit of volatility.",
      "WORK IT STEP BY STEP",
      "Excess return = 9% − 3% = 6% · 0.06 / 0.12 = 0.50",
      "Answer: 0.50",
      "Compare only when periods, inputs and methodology are consistent.",
    ],
    accent: ACCENT,
    thumbLabel: "Sharpe ratio",
  },
  {
    id: "green-s66",
    number: 66,
    title: "Simple 95% one-day VaR",
    subtitle: "Portfolio $100,000; one-day volatility 1.2%; z=1.645; zero mean.",
    bullets: [
      "VaR ≈ Portfolio value × z × σ",
      "Model-based 95% one-day loss threshold under normal assumptions.",
      "WORK IT STEP BY STEP",
      "σ = 0.012 · 1.645 × 0.012 = 0.01974",
      "Answer: ≈ $1,974",
      "There is still a 5% tail beyond the threshold; VaR is not worst-case loss.",
    ],
    accent: ACCENT,
    thumbLabel: "Simple 95%",
  },
  {
    id: "green-s67",
    number: 67,
    title: "Leverage",
    subtitle: "Investor equity $20,000; gross exposure $30,000.",
    bullets: [
      "Leverage = Gross exposure / Equity",
      "Investor controls $1.50 of gross exposure for each $1 of equity.",
      "WORK IT STEP BY STEP",
      "$30,000/$20,000 = 1.5",
      "Answer: 1.5× leverage",
      "Leverage magnifies gains, losses and potential forced- selling risk.",
    ],
    accent: ACCENT,
    thumbLabel: "Leverage",
  },
  {
    id: "green-s68",
    number: 68,
    title: "Recession stress test",
    subtitle: "$6,000 stocks −20%; $4,000 bonds +5%; $3,000 property −15%; $1,800 cash 0%.",
    bullets: [
      "Scenario P/L = Σ(Position value × Scenario return)",
      "Estimated portfolio dollar loss under the chosen shocks.",
      "WORK IT STEP BY STEP",
      "Stocks = −$1,200 · Bonds = +$200",
      "Answer: −$1,450",
      "Stress tests reveal which exposures drive loss and which provide protection.",
    ],
    accent: ACCENT,
    thumbLabel: "Recession stress",
  },
  {
    id: "green-s69",
    number: 69,
    title: "Scenario return",
    subtitle: "Starting portfolio $14,800; scenario P/L −$1,450.",
    bullets: [
      "Scenario return = Scenario P/L / Starting value × 100%",
      "Portfolio-level percentage loss under the scenario.",
      "WORK IT STEP BY STEP",
      "−$1,450/$14,800 = −0.097973 · ×100% = −9.80%",
      "Answer: ≈ −9.80%",
      "Compare the loss with risk tolerance, liquidity needs and mandate.",
    ],
    accent: ACCENT,
    thumbLabel: "Scenario return",
  },
  {
    id: "green-s70",
    number: 70,
    title: "Stress more than prices",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "RECESSION",
      "Revenue, credit spreads, property and unemployment.",
      "INFLATION SHOCK",
      "Bond prices, margins and pricing power.",
      "RATE SHOCK",
      "Duration, mortgages and valuations.",
      "CURRENCY SHOCK",
      "Foreign holdings and hedges.",
      "COMPANY SHOCK",
      "What if the largest holding falls 40%?",
    ],
    accent: ACCENT,
    thumbLabel: "Stress more",
  },
  {
    id: "green-s71",
    number: 71,
    title: "Portal 27 · Green City Crisis Challenge",
    subtitle: "Combine market, rate, credit, property, currency and company shocks—and make decisions under pressure.",
    bullets: [
      "Portal 27 of Green City Portfolio Management.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Green City",
  },
  {
    id: "green-s72",
    number: 72,
    title: "Crisis triage: use this order",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "1 LIQUIDITY",
      "Are there near-term cash obligations?",
      "2 FORCED RISKS",
      "Margin calls, refinancing, covenants or redemption pressure?",
      "3 THESIS BREAKS",
      "Which assumptions are no longer valid?",
      "4 CONCENTRATION",
      "Which positions now dominate risk?",
      "5 STRESS LOSS",
      "What does the scenario do to capital?",
    ],
    accent: ACCENT,
    thumbLabel: "Crisis triage",
  },
  {
    id: "green-s73",
    number: 73,
    title: "Integrated crisis scenario",
    subtitle: "The objective is not to avoid every loss. It is to respond rationally to several shocks at once.",
    bullets: [
      "RATES",
      "Policy rates unexpectedly +1.0 percentage point.",
      "EQUITIES",
      "Broad equity market −15%.",
      "PROPERTY",
      "Portfolio property value −10%.",
      "CREDIT",
      "Corporate spreads widen.",
      "CURRENCY",
      "Home currency appreciates 6%.",
    ],
    accent: ACCENT,
    thumbLabel: "Integrated crisis",
  },
  {
    id: "green-s74",
    number: 74,
    title: "Crisis duration loss",
    subtitle: "$3,700 bond allocation; modified duration 5.0; yield +1.0%.",
    bullets: [
      "%ΔPrice ≈ −Duration × ΔYield; Dollar P/L ≈ Position × %ΔPrice",
      "Approximate interest-rate loss on the bond allocation.",
      "WORK IT STEP BY STEP",
      "ΔYield = 0.010 · %ΔPrice ≈ −5.0×0.010 = −5.0%",
      "Answer: ≈ −$185",
      "Judge the loss alongside the bond’s liquidity/stabilizing role and higher future reinvestment yields.",
    ],
    accent: ACCENT,
    thumbLabel: "Crisis duration",
  },
  {
    id: "green-s75",
    number: 75,
    title: "Currency shock",
    subtitle: "Foreign asset local return 0%; foreign currency −6% vs home currency.",
    bullets: [
      "Domestic return = (1+Local)(1+FX) − 1",
      "Currency translation creates a loss even though local asset price is unchanged.",
      "WORK IT STEP BY STEP",
      "(1+0)(1−0.06) − 1 · = 0.94 − 1 = −0.06",
      "Answer: −6.0%",
      "FX risk can matter even when asset fundamentals have not changed.",
    ],
    accent: ACCENT,
    thumbLabel: "Currency shock",
  },
  {
    id: "green-s76",
    number: 76,
    title: "Weights change during crisis",
    subtitle: "Defensive holding stays $2,500; portfolio falls to $12,500.",
    bullets: [
      "New weight = New position value / New portfolio value × 100%",
      "A stable holding becomes a larger share when the rest of the portfolio falls.",
      "WORK IT STEP BY STEP",
      "$2,500/$12,500 = 0.20 · ×100% = 20%",
      "Answer: 20% new weight",
      "Rebalance using updated values, not old percentages.",
    ],
    accent: ACCENT,
    thumbLabel: "Weights change",
  },
  {
    id: "green-s77",
    number: 77,
    title: "Crisis decision grid",
    subtitle: "Green City Portfolio Management teaching deck.",
    bullets: [
      "LONG-DURATION BOND",
      "Rate shock → quantify duration loss before acting.",
      "SHORT HIGH-QUALITY BOND",
      "May preserve liquidity and stability.",
      "GROWTH STOCK",
      "Separate rate-driven repricing from thesis damage.",
      "WEAK COMPANY",
      "Guidance cut may represent thesis deterioration.",
      "DIRECT PROPERTY",
      "Check debt service and refinancing capacity.",
    ],
    accent: ACCENT,
    thumbLabel: "Crisis decision",
  },
  {
    id: "green-s78",
    number: 78,
    title: "Green City integrated decision workflow",
    subtitle: "Use one repeatable process across every holding and every portal.",
    bullets: [
      "1 OBSERVE",
      "What changed in price, economics or information?",
      "2 CALCULATE",
      "Use the relevant formula and show workings.",
      "3 INTERPRET",
      "Translate the number into portfolio meaning.",
      "4 COMPARE",
      "Targets, benchmarks, alternatives and scenarios.",
      "5 ACT",
      "Add, hold, trim, exit, replace, hedge or rebalance.",
    ],
    accent: ACCENT,
    thumbLabel: "Workflow",
  },
  {
    id: "green-s79",
    number: 79,
    title: "Calculation self-check",
    subtitle: "A correct number is only the middle of the analysis.",
    bullets: [
      "Did I choose the correct relationship? UNITS Are dollars, percentages, years and rates consistent? PERCENTAGES Did I convert to decimals when multiplying?",
      "WORK IT STEP BY STEP",
      "Can another learner follow each step? · INTERPRETATION",
    ],
    accent: ACCENT,
    thumbLabel: "Self-check",
  },
  {
    id: "green-s80",
    number: 80,
    title: "Green City readiness checklist",
    subtitle: "Strong capability means you can explain, calculate, interpret and act.",
    bullets: [
      "BONDS",
      "Coupon, yield, HPR, duration and credit risk.",
      "ETFs / ALTERNATIVES",
      "Costs, holdings, tracking and exposure.",
      "ALLOCATION",
      "Weights, target dollars and expected portfolio return.",
      "DIVERSIFICATION",
      "Concentration, correlation, FX and liquidity.",
      "ACTIVE MANAGEMENT",
      "Add, hold, trim, exit and replace.",
    ],
    accent: ACCENT,
    thumbLabel: "Checklist",
  },
  {
    id: "green-s81",
    number: 81,
    title: "GREEN CITY COMPLETE",
    subtitle: "Manage the portfolio—not the headlines.",
    bullets: [
      "A strong Green City learner can adapt to changing markets without abandoning a disciplined process.",
      "Measure exposures",
      "Show calculations",
      "Interpret risk",
      "Use new information",
      "Rebalance deliberately",
      "Act under crisis pressure",
      "NEXT: YELLOW CITY — professional portfolio construction and optimization.",
    ],
    footer: "Signal Quay · Green City Portfolio Management Teaching Deck",
    accent: "#c6a15b",
    thumbLabel: "Complete",
  },
];

/** Green City (Signal Quay) Portfolio Management classroom — portals 19–27. */
export const GREEN_CITY_CLASSROOM: ClassroomLesson = {
  id: "green-city-portfolio",
  areaId: "signal-quay",
  themeColor: ACCENT,
  themeColorDeep: ACCENT_DEEP,
  subject: "Portfolio",
  topic: "Green City Portfolio Management",
  title: "Lesson: Green City Portfolio Management",
  classId: "quay-class-green",
  moduleStart: 19,
  moduleEnd: 27,
  outline: [],
  slides: SLIDES,
  notesHref: "/library/signal-quay/green-city-portfolio-management-notes.pdf",
  notesDownloadName: "green-city-portfolio-management-notes.pdf",
  deckHref: "/library/signal-quay/green-city-portfolio-management-teaching-deck.pdf",
  deckDownloadName: "green-city-portfolio-management-teaching-deck.pdf",
  linkedSites: [
    {
      id: "link-treasury-rates",
      title: "U.S. Treasury — Interest Rate Statistics",
      url: "https://home.treasury.gov/policy-issues/financing-the-government/interest-rate-statistics",
      platform: "web",
    },
    {
      id: "link-investor-gov-research",
      title: "Investor.gov — Researching Investments",
      url: "https://www.investor.gov/introduction-investing/investing-basics",
      platform: "web",
    },
  ],
  quote: {
    text: "The investor's chief problem — and even his worst enemy — is likely to be himself.",
    author: "Benjamin Graham",
  },
};
