import type { ClassroomLesson, ClassroomSlide } from "@/lib/content/classroom";

const ACCENT = "#43a047";
const ACCENT_DEEP = "#2e7d32";

const SLIDES: ClassroomSlide[] = [
  {
    id: "green-s1",
    number: 1,
    title: "Green City · Portfolio Management",
    subtitle: "A visual teaching deck for Signal Quay (Green City)",
    bullets: [
      "Portfolio Management",
      "Learn how to manage and adapt an evolving portfolio as markets, risks and information change.",
      "START",
      "Understand each new portfolio tool.",
      "BUILD",
      "Calculate before making decisions.",
      "CAPABILITY",
      "Adapt without abandoning discipline.",
    ],
    footer: "Signal Quay · Green City Portfolio Management Teaching Deck",
    accent: ACCENT,
    thumbLabel: "Title",
  },
  {
    id: "green-s2",
    number: 2,
    title: "Where Green City fits",
    subtitle: "Green City assumes the portfolio already exists. Your job is now to manage the whole system.",
    bullets: [
      "PURPLE CITY",
      "Learn how to invest: foundations.",
      "BLUE CITY",
      "Learn what to invest in: analysis and selection.",
      "GREEN CITY",
      "Learn how to manage and adapt the portfolio.",
      "YELLOW CITY",
      "Prove you can manage professionally.",
    ],
    accent: ACCENT,
    thumbLabel: "Where it fits",
  },
  {
    id: "green-s3",
    number: 3,
    title: "How to learn from this deck",
    subtitle: "Every calculation is taught as a decision tool, not as isolated mathematics.",
    bullets: [
      "1 UNDERSTAND",
      "What does the idea mean?",
      "2 FORMULA",
      "What relationship are we measuring?",
      "3 SUBSTITUTE",
      "Where do the actual numbers go?",
      "4 CALCULATE",
      "Show every important step.",
      "5 INTERPRET",
      "Translate the answer into plain English.",
    ],
    accent: ACCENT,
    thumbLabel: "How to learn",
  },
  {
    id: "green-s4",
    number: 4,
    title: "Green City roadmap",
    subtitle: "Nine portals turn individual investments into an actively managed portfolio.",
    bullets: [
      "Bonds",
      "ETFs &",
      "Alternatives",
      "Allocation",
      "Diversification",
      "Add / Trim /",
      "Exit",
      "Macro",
      "New",
      "Information",
    ],
    accent: ACCENT,
    thumbLabel: "Roadmap",
  },
  {
    id: "green-s5",
    number: 5,
    title: "The Green City management mindset",
    subtitle: "A good asset can still create a bad portfolio if it is badly sized or badly combined.",
    bullets: [
      "RETURN",
      "What can this holding contribute?",
      "RISK",
      "How can it hurt the portfolio?",
      "LIQUIDITY",
      "Can capital be accessed when needed?",
      "CORRELATION",
      "What else tends to move with it?",
      "CASH FLOW",
      "Does it generate or consume cash?",
    ],
    accent: ACCENT,
    thumbLabel: "Mindset",
  },
  {
    id: "green-s6",
    number: 6,
    title: "Portal 19 · Bonds & Fixed Income",
    subtitle: "Understand government and corporate bonds, yields, duration, credit risk and interest-rate",
    bullets: [
      "sensitivity.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Bonds & Fixed Income",
  },
  {
    id: "green-s7",
    number: 7,
    title: "Portal 19 · Bond basics",
    subtitle: "A bondholder is mainly a creditor, not an owner.",
    bullets: [
      "BOND",
      "A loan made by the investor to a government or company.",
      "FACE VALUE",
      "Principal normally repaid at maturity.",
      "COUPON RATE",
      "Contractual interest rate applied to face value.",
      "MATURITY",
      "Date principal is due.",
      "MARKET PRICE",
      "What investors pay for the bond today.",
    ],
    accent: ACCENT,
    thumbLabel: "Bond basics",
  },
  {
    id: "green-s8",
    number: 8,
    title: "Portal 19 · Coupon payment",
    subtitle: "Face value $1,000; annual coupon rate 6%.",
    bullets: [
      "FORMULA",
      "Annual coupon = Face value × Coupon rate",
      "WHAT ARE WE MEASURING?",
      "Contractual annual cash interest.",
      "WORKINGS",
      "6% = 0.06",
      "Coupon = $1,000 × 0.06",
      "Coupon = $60",
      "ANSWER",
      "$60 per year",
    ],
    accent: ACCENT,
    thumbLabel: "Coupon payment",
  },
  {
    id: "green-s9",
    number: 9,
    title: "Portal 19 · Current yield",
    subtitle: "Annual coupon $60; bond price $950.",
    bullets: [
      "FORMULA",
      "Current yield = Annual coupon / Market price × 100%",
      "WHAT ARE WE MEASURING?",
      "Coupon income relative to today’s purchase price.",
      "WORKINGS",
      "$60 / $950 = 0.0631579",
      "0.0631579 × 100% = 6.31579%",
      "ANSWER",
      "≈ 6.32%",
      "PORTFOLIO MEANING",
    ],
    accent: ACCENT,
    thumbLabel: "Current yield",
  },
  {
    id: "green-s10",
    number: 10,
    title: "Portal 19 · Holding-period return",
    subtitle: "Buy at $980; receive $50 coupon; sell at $1,005.",
    bullets: [
      "FORMULA",
      "HPR = (Coupon + Ending price − Beginning price) /",
      "Beginning price × 100%",
      "WHAT ARE WE MEASURING?",
      "Coupon income plus price change over the holding period.",
      "WORKINGS",
      "Price gain = $1,005 − $980 = $25",
      "Total gain = $50 + $25 = $75",
      "$75 / $980 × 100% = 7.65306%",
      "ANSWER",
      "≈ 7.65%",
    ],
    accent: ACCENT,
    thumbLabel: "Holding-period",
  },
  {
    id: "green-s11",
    number: 11,
    title: "Portal 19 · Why bond prices and yields move in opposite directions",
    subtitle: "This inverse relationship is one of the most important fixed-income ideas.",
    bullets: [
      "RATES RISE",
      "New bonds can offer more attractive returns. Existing lower-paying bonds must",
      "become cheaper to compete.",
      "RATES FALL",
      "Existing higher-paying fixed coupons become more attractive, supporting higher",
      "prices.",
      "PRICE ADJUSTS",
      "The bond’s promised coupon is fixed, so market price does much of the",
      "adjustment.",
      "PORTFOLIO EFFECT",
    ],
    accent: ACCENT,
    thumbLabel: "Why bond prices and",
  },
  {
    id: "green-s12",
    number: 12,
    title: "Portal 19 · Duration: rate rise",
    subtitle: "Modified duration 5.2; yield rises 0.75 percentage points.",
    bullets: [
      "FORMULA",
      "Approx. %ΔPrice ≈ −Modified duration × ΔYield",
      "WHAT ARE WE MEASURING?",
      "Approximate sensitivity of price to a small yield change.",
      "WORKINGS",
      "0.75% = 0.0075",
      "%ΔPrice ≈ −5.2 × 0.0075",
      "= −0.039 = −3.9%",
      "ANSWER",
      "≈ 3.9% price decline",
    ],
    accent: ACCENT,
    thumbLabel: "Duration: rate rise",
  },
  {
    id: "green-s13",
    number: 13,
    title: "Portal 19 · Duration: rate fall",
    subtitle: "Modified duration 7.0; yield falls 0.40 percentage points.",
    bullets: [
      "FORMULA",
      "Approx. %ΔPrice ≈ −Duration × ΔYield",
      "WHAT ARE WE MEASURING?",
      "The negative sign captures the inverse price/yield relationship.",
      "WORKINGS",
      "ΔYield = −0.40% = −0.0040",
      "−7.0 × (−0.0040) = +0.028",
      "= +2.8%",
      "ANSWER",
      "≈ 2.8% price increase",
    ],
    accent: ACCENT,
    thumbLabel: "Duration: rate fall",
  },
  {
    id: "green-s14",
    number: 14,
    title: "Portal 19 · Credit spread",
    subtitle: "Corporate yield 6.4%; comparable government yield 4.1%.",
    bullets: [
      "FORMULA",
      "Credit spread = Corporate yield − Government yield",
      "WHAT ARE WE MEASURING?",
      "Extra yield offered above the government benchmark.",
      "WORKINGS",
      "6.4% − 4.1% = 2.3 percentage points",
      "2.3 percentage points = 230 basis points",
      "ANSWER",
      "2.3% = 230 bps",
      "PORTFOLIO MEANING",
    ],
    accent: ACCENT,
    thumbLabel: "Credit spread",
  },
  {
    id: "green-s15",
    number: 15,
    title: "Portal 19 · What bonds can contribute",
    subtitle: "INCOME",
    bullets: [
      "Coupons can provide planned cash flow.",
      "STABILITY",
      "High-quality short bonds may fluctuate less than equities.",
      "DIVERSIFICATION",
      "Some bonds can behave differently from stocks in stress.",
      "LIABILITY MATCHING",
      "Maturities can align with future cash needs.",
      "LIQUIDITY",
      "Some government markets are deep and tradable.",
      "RISKS REMAIN",
    ],
    accent: ACCENT,
    thumbLabel: "What bonds can",
  },
  {
    id: "green-s16",
    number: 16,
    title: "Portal 20 · ETFs, Commodities & Alternatives",
    subtitle: "Broaden the toolkit using pooled and alternative exposures without buying every underlying asset",
    bullets: [
      "directly.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "ETFs, Commodities &",
  },
  {
    id: "green-s17",
    number: 17,
    title: "Portal 20 · What an ETF actually does",
    subtitle: "The label “ETF” describes the vehicle—not the risk inside it.",
    bullets: [
      "POOL",
      "Combines investor money into a portfolio that trades on an exchange.",
      "EXPOSURE",
      "Can track broad markets, sectors, bonds, commodities, factors or active",
      "strategies.",
      "HOLDINGS",
      "Always ask what the fund really owns.",
      "COST",
      "Expense ratio and trading spread reduce investor return.",
      "TRACKING",
    ],
    accent: ACCENT,
    thumbLabel: "What an ETF actually",
  },
  {
    id: "green-s18",
    number: 18,
    title: "Portal 20 · ETF expense ratio",
    subtitle: "Investment $8,000; expense ratio 0.25%.",
    bullets: [
      "FORMULA",
      "Approx. annual fee = Investment × Expense ratio",
      "WHAT ARE WE MEASURING?",
      "Approximate annual fund operating cost on the investment.",
      "WORKINGS",
      "0.25% = 0.0025",
      "$8,000 × 0.0025 = $20",
      "ANSWER",
      "≈ $20 per year",
      "PORTFOLIO MEANING",
    ],
    accent: ACCENT,
    thumbLabel: "ETF expense ratio",
  },
  {
    id: "green-s19",
    number: 19,
    title: "Portal 20 · Tracking difference",
    subtitle: "Index return 9.2%; ETF return 8.9%.",
    bullets: [
      "FORMULA",
      "Tracking difference = ETF return − Benchmark return",
      "WHAT ARE WE MEASURING?",
      "How the fund’s return differed from the intended benchmark.",
      "WORKINGS",
      "8.9% − 9.2% = −0.3 percentage points",
      "ANSWER",
      "−0.30 percentage points",
      "PORTFOLIO MEANING",
      "Fees, trading costs, cash drag and imperfect replication can",
    ],
    accent: ACCENT,
    thumbLabel: "Tracking difference",
  },
  {
    id: "green-s20",
    number: 20,
    title: "Portal 20 · What moves commodities?",
    subtitle: "SUPPLY",
    bullets: [
      "Production cuts, mine closures, crop failures.",
      "DEMAND",
      "Industry, construction, transport and consumption.",
      "INVENTORIES",
      "Low stocks can make shocks more powerful.",
      "WEATHER",
      "Important for agriculture and energy demand.",
      "GEOPOLITICS",
      "Sanctions, conflict and shipping disruption.",
      "FUTURES STRUCTURE",
    ],
    accent: ACCENT,
    thumbLabel: "What moves",
  },
  {
    id: "green-s21",
    number: 21,
    title: "Portal 20 · Commodity price return",
    subtitle: "Gold rises from $2,000 to $2,140 per ounce.",
    bullets: [
      "FORMULA",
      "Price return = (Ending price − Beginning price) /",
      "Beginning price × 100%",
      "WHAT ARE WE MEASURING?",
      "Change in the commodity price before vehicle costs.",
      "WORKINGS",
      "Price change = $2,140 − $2,000 = $140",
      "$140 / $2,000 = 0.07",
      "0.07 × 100% = 7.0%",
      "ANSWER",
      "7.0%",
    ],
    accent: ACCENT,
    thumbLabel: "Commodity price",
  },
  {
    id: "green-s22",
    number: 22,
    title: "Portal 20 · Direct ownership vs pooled exposure",
    subtitle: "STOCKS",
    bullets: [
      "Individual shares vs a basket of companies.",
      "BONDS",
      "Specific issuer/maturity vs diversified bond fund.",
      "GOLD",
      "Physical bullion/storage vs liquid fund exposure.",
      "PROPERTY",
      "Direct property/management vs a REIT or REIT ETF.",
      "COMMODITIES",
      "Physical ownership can be impractical; funds may use futures.",
      "KEY QUESTION",
    ],
    accent: ACCENT,
    thumbLabel: "Direct ownership vs",
  },
  {
    id: "green-s23",
    number: 23,
    title: "Portal 21 · Strategic Asset Allocation",
    subtitle: "Set long-term target weights based on objectives, horizon, liquidity needs and risk capacity.",
    bullets: [
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Strategic Asset",
  },
  {
    id: "green-s24",
    number: 24,
    title: "Portal 21 · Allocation is the portfolio’s architecture",
    subtitle: "WEIGHTS CREATE SCALE",
    bullets: [
      "A $4,000 holding means different things in a $5,000 versus $100,000 portfolio.",
      "OBJECTIVES FIRST",
      "Return goals must coexist with liquidity and loss capacity.",
      "STRATEGIC",
      "Long-term target structure.",
      "TACTICAL",
      "Temporary deviation based on a specific view.",
      "DISCIPLINE",
      "Targets make later rebalancing measurable.",
      "NOT A FORECAST",
    ],
    accent: ACCENT,
    thumbLabel: "Allocation is the",
  },
  {
    id: "green-s25",
    number: 25,
    title: "Portal 21 · Portfolio weight",
    subtitle: "$14,800 portfolio; stocks worth $4,440.",
    bullets: [
      "FORMULA",
      "Weight = Asset value / Portfolio value × 100%",
      "WHAT ARE WE MEASURING?",
      "Share of total capital currently committed to stocks.",
      "WORKINGS",
      "$4,440 / $14,800 = 0.30",
      "0.30 × 100% = 30%",
      "ANSWER",
      "30% stock weight",
      "PORTFOLIO MEANING",
    ],
    accent: ACCENT,
    thumbLabel: "Portfolio weight",
  },
  {
    id: "green-s26",
    number: 26,
    title: "Portal 21 · Target dollars",
    subtitle: "$14,800 portfolio; target bond weight 25%.",
    bullets: [
      "FORMULA",
      "Target value = Portfolio value × Target weight",
      "WHAT ARE WE MEASURING?",
      "Converts a policy percentage into an implementable dollar target.",
      "WORKINGS",
      "25% = 0.25",
      "$14,800 × 0.25 = $3,700",
      "ANSWER",
      "$3,700 in bonds",
      "PORTFOLIO MEANING",
    ],
    accent: ACCENT,
    thumbLabel: "Target dollars",
  },
  {
    id: "green-s27",
    number: 27,
    title: "Portal 21 · Expected portfolio return",
    subtitle: "50% stocks at 8%; 30% bonds at 4%; 20% cash at 2%.",
    bullets: [
      "FORMULA",
      "E(Rp) = Σ wᵢE(Rᵢ)",
      "WHAT ARE WE MEASURING?",
      "Weighted combination of expected asset returns.",
      "WORKINGS",
      "Stocks: 0.50×8% = 4.00%",
      "Bonds: 0.30×4% = 1.20%",
      "Cash: 0.20×2% = 0.40%",
      "Total = 5.60%",
      "ANSWER",
      "5.60% expected return",
    ],
    accent: ACCENT,
    thumbLabel: "Expected portfolio",
  },
  {
    id: "green-s28",
    number: 28,
    title: "Portal 21 · Rebalancing amount",
    subtitle: "Bond target $3,700; current bonds $3,150.",
    bullets: [
      "FORMULA",
      "Trade = Target value − Current value",
      "WHAT ARE WE MEASURING?",
      "Difference between desired and actual dollar exposure.",
      "WORKINGS",
      "$3,700 − $3,150 = +$550",
      "ANSWER",
      "Buy/add $550",
      "PORTFOLIO MEANING",
      "Rebalancing reconnects the real portfolio to the policy",
    ],
    accent: ACCENT,
    thumbLabel: "Rebalancing amount",
  },
  {
    id: "green-s29",
    number: 29,
    title: "Portal 21 · Example strategic allocation",
    subtitle: "Illustrative allocation from the notes—not a universal recommendation.",
    bullets: [
      "STOCKS 30%",
      "$4,440",
      "BONDS 25%",
      "$3,700",
      "REAL ESTATE 15%",
      "$2,220",
      "DIVERSIFIED ETF 10%",
      "$1,480",
      "ALTERNATIVES 5%",
      "$740",
    ],
    accent: ACCENT,
    thumbLabel: "Example strategic",
  },
  {
    id: "green-s30",
    number: 30,
    title: "Portal 22 · Portfolio Diversification",
    subtitle: "Identify hidden concentrations by examining correlation, sector, geography, currency and liquidity.",
    bullets: [
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Portfolio",
  },
  {
    id: "green-s31",
    number: 31,
    title: "Portal 22 · Diversification is not “own many things”",
    subtitle: "NAMES ≠ RISKS",
    bullets: [
      "Ten technology stocks can still be one concentrated bet.",
      "SECTOR",
      "How much depends on one industry?",
      "GEOGRAPHY",
      "How much depends on one economy?",
      "CURRENCY",
      "Foreign assets add exchange-rate exposure.",
      "LIQUIDITY",
      "Can enough capital be accessed in a crisis?",
      "CORRELATION",
    ],
    accent: ACCENT,
    thumbLabel: "Diversification is",
  },
  {
    id: "green-s32",
    number: 32,
    title: "Portal 22 · Sector concentration",
    subtitle: "Technology exposure $6,216; portfolio $14,800.",
    bullets: [
      "FORMULA",
      "Sector weight = Sector exposure / Portfolio value ×",
      "100%",
      "WHAT ARE WE MEASURING?",
      "Percentage of portfolio tied to one broad sector.",
      "WORKINGS",
      "$6,216 / $14,800 = 0.42",
      "0.42 × 100% = 42%",
      "ANSWER",
      "42% technology exposure",
    ],
    accent: ACCENT,
    thumbLabel: "Sector concentration",
  },
  {
    id: "green-s33",
    number: 33,
    title: "Portal 22 · Correlation made simple",
    subtitle: "Diversification improves when risks do not all respond identically.",
    bullets: [
      "+1",
      "Assets move perfectly together.",
      "POSITIVE",
      "They often move in the same direction.",
      "No linear relationship in the sample.",
      "NEGATIVE",
      "They often move in opposite directions.",
      "−1",
      "Perfect opposite movement.",
      "IMPORTANT",
    ],
    accent: ACCENT,
    thumbLabel: "Correlation made",
  },
  {
    id: "green-s34",
    number: 34,
    title: "Portal 22 · Two-asset portfolio volatility",
    subtitle: "60% A, 40% B; σA=15%, σB=10%; correlation=0.20.",
    bullets: [
      "FORMULA",
      "σp² = wA²σA² + wB²σB² + 2wAwBσAσBρ",
      "WHAT ARE WE MEASURING?",
      "Combined risk depends on both individual volatility and correlation.",
      "WORKINGS",
      "Term 1 = (0.60²)(0.15²) = 0.00810",
      "Term 2 = (0.40²)(0.10²) = 0.00160",
      "Covariance term = 0.00144",
      "Variance = 0.01114",
      "σp = √0.01114 = 0.10555 = 10.56%",
    ],
    accent: ACCENT,
    thumbLabel: "Two-asset portfolio",
  },
  {
    id: "green-s35",
    number: 35,
    title: "Portal 22 · What if correlation rises?",
    subtitle: "Same portfolio, but correlation rises from 0.20 to 0.90.",
    bullets: [
      "FORMULA",
      "σp² = wA²σA² + wB²σB² + 2wAwBσAσBρ",
      "WHAT ARE WE MEASURING?",
      "The portfolio becomes riskier when assets move more closely together.",
      "WORKINGS",
      "Term 1 = 0.00810",
      "Term 2 = 0.00160",
      "Covariance term = 0.00648",
      "Variance = 0.01618",
      "σp = √0.01618 = 12.72%",
    ],
    accent: ACCENT,
    thumbLabel: "What if correlation",
  },
  {
    id: "green-s36",
    number: 36,
    title: "Portal 22 · Foreign asset + currency",
    subtitle: "Foreign stock +8%; foreign currency +5% vs home currency.",
    bullets: [
      "FORMULA",
      "Domestic return = (1 + Local return)(1 + FX return)",
      "− 1",
      "WHAT ARE WE MEASURING?",
      "Combines local asset performance with currency movement.",
      "WORKINGS",
      "(1+0.08)(1+0.05) − 1",
      "1.08 × 1.05 − 1",
      "1.134 − 1 = 0.134",
      "ANSWER",
      "13.4% domestic return",
    ],
    accent: ACCENT,
    thumbLabel: "Foreign asset +",
  },
  {
    id: "green-s37",
    number: 37,
    title: "Portal 22 · Liquidity is part of diversification",
    subtitle: "CASH / T-BILLS",
    bullets: [
      "Usually accessible quickly.",
      "LARGE STOCKS / ETFs",
      "Often liquid, but spreads can widen.",
      "CORPORATE BONDS",
      "Liquidity varies by issue.",
      "DIRECT PROPERTY",
      "Sale can take months.",
      "PRIVATE BUSINESS",
      "Buyer may be difficult to find.",
      "ALTERNATIVES",
    ],
    accent: ACCENT,
    thumbLabel: "Liquidity is part of",
  },
  {
    id: "green-s38",
    number: 38,
    title: "Portal 23 · Add, Trim or Exit",
    subtitle: "Turn portfolio diagnosis into disciplined action rather than emotional trading.",
    bullets: [
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Add, Trim or Exit",
  },
  {
    id: "green-s39",
    number: 39,
    title: "Portal 23 · Five core management decisions",
    subtitle: "ADD",
    bullets: [
      "Increase when evidence strengthens, valuation improves or position is below",
      "target.",
      "HOLD",
      "Keep deliberately when thesis and sizing remain appropriate.",
      "TRIM",
      "Reduce because valuation, concentration or risk has risen.",
      "EXIT",
      "Close when thesis breaks or risk becomes unacceptable.",
      "REPLACE",
      "Move capital to a superior opportunity.",
    ],
    accent: ACCENT,
    thumbLabel: "Five core management",
  },
  {
    id: "green-s40",
    number: 40,
    title: "Portal 23 · Rebalancing band",
    subtitle: "Target stock weight 30%; allowed deviation ±5 percentage points.",
    bullets: [
      "FORMULA",
      "Upper = Target + deviation; Lower = Target −",
      "deviation",
      "WHAT ARE WE MEASURING?",
      "Tolerance range around the target.",
      "WORKINGS",
      "Upper = 30% + 5% = 35%",
      "Lower = 30% − 5% = 25%",
      "ANSWER",
      "25% to 35% band",
    ],
    accent: ACCENT,
    thumbLabel: "Rebalancing band",
  },
  {
    id: "green-s41",
    number: 41,
    title: "Portal 23 · Trim to target",
    subtitle: "Portfolio $16,000; stock position $6,000; target 30%.",
    bullets: [
      "FORMULA",
      "Target value = Portfolio × Target weight; Trim =",
      "Current − Target",
      "WHAT ARE WE MEASURING?",
      "Amount required to return the position to its target weight.",
      "WORKINGS",
      "Target = $16,000 × 0.30 = $4,800",
      "Trim = $6,000 − $4,800 = $1,200",
      "ANSWER",
      "Trim $1,200",
    ],
    accent: ACCENT,
    thumbLabel: "Trim to target",
  },
  {
    id: "green-s42",
    number: 42,
    title: "Portal 23 · Remaining valuation upside",
    subtitle: "Estimated value $72; current price $66.",
    bullets: [
      "FORMULA",
      "Upside = (Value − Price) / Price × 100%",
      "WHAT ARE WE MEASURING?",
      "Remaining gap between market price and estimated value.",
      "WORKINGS",
      "Difference = $72 − $66 = $6",
      "$6 / $66 = 0.090909",
      "×100% = 9.09%",
      "ANSWER",
      "≈ 9.09% upside",
    ],
    accent: ACCENT,
    thumbLabel: "Remaining valuation",
  },
  {
    id: "green-s43",
    number: 43,
    title: "Portal 23 · Capital rotation",
    subtitle: "Current holding expected return 5%; new opportunity 9%.",
    bullets: [
      "FORMULA",
      "Relative advantage = New E(R) − Current E(R)",
      "WHAT ARE WE MEASURING?",
      "Estimated expected-return advantage of the alternative.",
      "WORKINGS",
      "9% − 5% = 4 percentage points",
      "ANSWER",
      "4 percentage points",
      "PORTFOLIO MEANING",
      "Also consider risk, liquidity, taxes, costs and forecast",
    ],
    accent: ACCENT,
    thumbLabel: "Capital rotation",
  },
  {
    id: "green-s44",
    number: 44,
    title: "Portal 23 · What can break a thesis?",
    subtitle: "ECONOMICS",
    bullets: [
      "Revenue or cash-flow driver weakens structurally.",
      "ADVANTAGE",
      "Competitive position deteriorates.",
      "BALANCE SHEET",
      "Debt/refinancing risk rises materially.",
      "MANAGEMENT",
      "Credibility or execution worsens.",
      "REGULATION",
      "Rules damage access, costs or profitability.",
      "VALUATION",
    ],
    accent: ACCENT,
    thumbLabel: "What can break a",
  },
  {
    id: "green-s45",
    number: 45,
    title: "Portal 24 · Macroeconomics for Investors",
    subtitle: "Use the economic environment to understand forces acting across several portfolio holdings at",
    bullets: [
      "once.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Macroeconomics for",
  },
  {
    id: "green-s46",
    number: 46,
    title: "Portal 24 · The macro dashboard",
    subtitle: "GDP",
    bullets: [
      "Is economic activity accelerating or slowing?",
      "INFLATION",
      "Are prices rising faster or slower?",
      "INTEREST RATES",
      "How expensive is capital?",
      "UNEMPLOYMENT",
      "How strong is labor demand and household income?",
      "FISCAL POLICY",
      "Is government policy stimulating or restraining demand?",
      "MONETARY POLICY",
    ],
    accent: ACCENT,
    thumbLabel: "The macro dashboard",
  },
  {
    id: "green-s47",
    number: 47,
    title: "Portal 24 · Approximate real rate",
    subtitle: "Nominal rate 5.5%; inflation 3.2%.",
    bullets: [
      "FORMULA",
      "Approx. real rate ≈ Nominal rate − Inflation",
      "WHAT ARE WE MEASURING?",
      "Simple inflation-adjusted rate approximation.",
      "WORKINGS",
      "5.5% − 3.2% = 2.3%",
      "ANSWER",
      "≈ +2.3%",
      "PORTFOLIO MEANING",
      "Higher real rates can tighten financial conditions and",
    ],
    accent: ACCENT,
    thumbLabel: "Approximate real",
  },
  {
    id: "green-s48",
    number: 48,
    title: "Portal 24 · Exact real rate",
    subtitle: "Nominal rate 5.5%; inflation 3.2%.",
    bullets: [
      "FORMULA",
      "Real = (1 + Nominal) / (1 + Inflation) − 1",
      "WHAT ARE WE MEASURING?",
      "More precise inflation adjustment using the Fisher relationship.",
      "WORKINGS",
      "1.055 / 1.032 − 1",
      "= 1.0222868 − 1",
      "= 0.0222868 = 2.22868%",
      "ANSWER",
      "≈ 2.23%",
    ],
    accent: ACCENT,
    thumbLabel: "Exact real rate",
  },
  {
    id: "green-s49",
    number: 49,
    title: "Portal 24 · Yield-curve spread",
    subtitle: "10-year yield 4.0%; 2-year yield 4.7%.",
    bullets: [
      "FORMULA",
      "Term spread = Long-term yield − Short-term yield",
      "WHAT ARE WE MEASURING?",
      "Selected curve segment is inverted.",
      "WORKINGS",
      "4.0% − 4.7% = −0.7 percentage points",
      "= −70 basis points",
      "ANSWER",
      "−0.70% = −70 bps",
      "PORTFOLIO MEANING",
    ],
    accent: ACCENT,
    thumbLabel: "Yield-curve spread",
  },
  {
    id: "green-s50",
    number: 50,
    title: "Portal 24 · How inflation can affect assets",
    subtitle: "CASH",
    bullets: [
      "Purchasing power can erode if yield lags inflation.",
      "NOMINAL BONDS",
      "Fixed payments lose real value; rising yields can reduce price.",
      "STOCKS",
      "Depends on pricing power, input costs and valuation.",
      "REAL ESTATE",
      "Rents may rise, but financing costs can also rise.",
      "COMMODITIES",
      "Some react strongly to supply shocks and inflation.",
      "FOREX",
    ],
    accent: ACCENT,
    thumbLabel: "How inflation can",
  },
  {
    id: "green-s51",
    number: 51,
    title: "Portal 24 · Economic cycle: ask different questions",
    subtitle: "EXPANSION",
    bullets: [
      "Growth strong: are cyclicals and credit risks underpriced?",
      "LATE CYCLE",
      "Inflation/rates may rise: is leverage becoming dangerous?",
      "SLOWDOWN / RECESSION",
      "Which earnings are cyclical? Is liquidity sufficient?",
      "RECOVERY",
      "Where are prices still reflecting recession conditions?",
    ],
    accent: ACCENT,
    thumbLabel: "Economic cycle: ask",
  },
  {
    id: "green-s52",
    number: 52,
    title: "Portal 25 · Earnings, News & New Information",
    subtitle: "Separate thesis-changing evidence from market noise by comparing new facts with prior",
    bullets: [
      "expectations.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Earnings, News & New",
  },
  {
    id: "green-s53",
    number: 53,
    title: "Portal 25 · Markets react to surprise—not simply “good” or “bad”",
    subtitle: "EXPECTATIONS",
    bullets: [
      "A record result can disappoint if investors expected even more.",
      "SOURCE",
      "Prefer primary, credible evidence.",
      "CASH FLOW",
      "Does the news change future cash generation?",
      "RISK",
      "Does it change the probability or severity of loss?",
      "VALUATION",
      "Does the value estimate need revision?",
      "DURATION",
    ],
    accent: ACCENT,
    thumbLabel: "Markets react to",
  },
  {
    id: "green-s54",
    number: 54,
    title: "Portal 25 · Earnings surprise",
    subtitle: "Actual EPS $2.10; consensus expected $1.95.",
    bullets: [
      "FORMULA",
      "Surprise % = (Actual − Expected) / |Expected| ×",
      "100%",
      "WHAT ARE WE MEASURING?",
      "Reported EPS exceeded consensus by about 7.69%.",
      "WORKINGS",
      "Difference = $2.10 − $1.95 = $0.15",
      "$0.15 / $1.95 = 0.076923",
      "×100% = 7.69%",
      "ANSWER",
      "≈ +7.69%",
    ],
    accent: ACCENT,
    thumbLabel: "Earnings surprise",
  },
  {
    id: "green-s55",
    number: 55,
    title: "Portal 25 · Guidance revision",
    subtitle: "Old revenue guide $980m–$1.02bn; new $1.04bn–$1.10bn.",
    bullets: [
      "FORMULA",
      "Midpoint = (Low + High)/2; Change = (New −",
      "Old)/Old ×100%",
      "WHAT ARE WE MEASURING?",
      "Management raised its central revenue expectation materially.",
      "WORKINGS",
      "Old midpoint = ($980m+$1,020m)/2 = $1,000m",
      "New midpoint = ($1,040m+$1,100m)/2 = $1,070m",
      "Change = $70m/$1,000m ×100% = 7.0%",
      "ANSWER",
      "Guidance midpoint +7.0%",
    ],
    accent: ACCENT,
    thumbLabel: "Guidance revision",
  },
  {
    id: "green-s56",
    number: 56,
    title: "Portal 25 · Event return",
    subtitle: "Stock $50 before earnings; $46 after.",
    bullets: [
      "FORMULA",
      "Event return = (Post-event price − Pre-event price) /",
      "Pre-event price × 100%",
      "WHAT ARE WE MEASURING?",
      "Measures the market price reaction around the event.",
      "WORKINGS",
      "Change = $46 − $50 = −$4",
      "−$4 / $50 = −0.08",
      "×100% = −8.0%",
      "ANSWER",
      "−8.0%",
    ],
    accent: ACCENT,
    thumbLabel: "Event return",
  },
  {
    id: "green-s57",
    number: 57,
    title: "Portal 25 · Information triage: seven questions",
    subtitle: "What exactly changed?",
    bullets: [
      "Is the source primary and credible?",
      "Was it already expected?",
      "Does it alter cash flow, risk, valuation or financing?",
      "Temporary or structural?",
      "One holding or the whole portfolio?",
      "Does the action change: ADD, HOLD, TRIM, EXIT—or no action?",
      "DISCIPLINE",
      "A price move alone is not a thesis.",
    ],
    accent: ACCENT,
    thumbLabel: "Information triage:",
  },
  {
    id: "green-s58",
    number: 58,
    title: "Portal 26 · Risk Management & Stress Testing",
    subtitle: "Measure different dimensions of risk and test how the portfolio might behave under adverse",
    bullets: [
      "scenarios.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Risk Management &",
  },
  {
    id: "green-s59",
    number: 59,
    title: "Portal 26 · Risk has more than one meaning",
    subtitle: "VOLATILITY",
    bullets: [
      "How widely returns vary.",
      "BETA",
      "Sensitivity to broad market movement.",
      "DRAWDOWN",
      "Peak-to-trough loss.",
      "SHARPE",
      "Excess return per unit of volatility.",
      "VaR",
      "Model-based loss threshold under assumptions.",
      "LEVERAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Risk has more than",
  },
  {
    id: "green-s60",
    number: 60,
    title: "Portal 26 · Average return",
    subtitle: "Monthly returns: 2%, −1%, 3%, 0%, 1%.",
    bullets: [
      "FORMULA",
      "Arithmetic mean = ΣRᵢ / n",
      "WHAT ARE WE MEASURING?",
      "Central arithmetic return across observations.",
      "WORKINGS",
      "Sum = 2% −1% +3% +0% +1% = 5%",
      "n = 5",
      "Mean = 5% / 5 = 1%",
      "ANSWER",
      "1% average monthly return",
    ],
    accent: ACCENT,
    thumbLabel: "Average return",
  },
  {
    id: "green-s61",
    number: 61,
    title: "Portal 26 · Sample volatility",
    subtitle: "Returns: 2%, −1%, 3%, 0%, 1%; mean = 1%.",
    bullets: [
      "FORMULA",
      "s² = Σ(Rᵢ−R̄)²/(n−1); s = √s²",
      "WHAT ARE WE MEASURING?",
      "Historical spread of returns around the mean.",
      "WORKINGS",
      "Deviations: 1%, −2%, 2%, −1%, 0%",
      "Decimals squared: .0001,.0004,.0004,.0001,0",
      "Sum = 0.0010; variance = 0.0010/4 = 0.00025",
      "s = √0.00025 = 0.015811 = 1.58%",
      "ANSWER",
      "≈ 1.58% monthly volatility",
    ],
    accent: ACCENT,
    thumbLabel: "Sample volatility",
  },
  {
    id: "green-s62",
    number: 62,
    title: "Portal 26 · Beta interpretation",
    subtitle: "Stock beta 1.30; market rises 4%.",
    bullets: [
      "FORMULA",
      "Approx. market-driven move ≈ Beta × Market move",
      "WHAT ARE WE MEASURING?",
      "Simplified market-related sensitivity estimate.",
      "WORKINGS",
      "1.30 × 4% = 5.2%",
      "ANSWER",
      "≈ +5.2%",
      "PORTFOLIO MEANING",
      "Beta is not an exact return forecast and excludes company-",
    ],
    accent: ACCENT,
    thumbLabel: "Beta interpretation",
  },
  {
    id: "green-s63",
    number: 63,
    title: "Portal 26 · Drawdown",
    subtitle: "Portfolio peak $18,000; trough $14,400.",
    bullets: [
      "FORMULA",
      "Drawdown = (Trough − Peak) / Peak × 100%",
      "WHAT ARE WE MEASURING?",
      "Loss from the prior peak to the trough.",
      "WORKINGS",
      "Loss = $14,400 − $18,000 = −$3,600",
      "−$3,600/$18,000 = −0.20",
      "×100% = −20%",
      "ANSWER",
      "−20% drawdown",
    ],
    accent: ACCENT,
    thumbLabel: "Drawdown",
  },
  {
    id: "green-s64",
    number: 64,
    title: "Portal 26 · Recovery after drawdown",
    subtitle: "Recover from $14,400 back to $18,000.",
    bullets: [
      "FORMULA",
      "Recovery return = Peak / Trough − 1",
      "WHAT ARE WE MEASURING?",
      "Losses and recoveries are asymmetric because recovery starts from a smaller base.",
      "WORKINGS",
      "$18,000/$14,400 = 1.25",
      "1.25 − 1 = 0.25",
      "= 25%",
      "ANSWER",
      "25% required gain",
    ],
    accent: ACCENT,
    thumbLabel: "Recovery after",
  },
  {
    id: "green-s65",
    number: 65,
    title: "Portal 26 · Sharpe ratio",
    subtitle: "Portfolio return 9%; risk-free 3%; volatility 12%.",
    bullets: [
      "FORMULA",
      "Sharpe = (Rp − Rf) / σp",
      "WHAT ARE WE MEASURING?",
      "Excess return earned per unit of volatility.",
      "WORKINGS",
      "Excess return = 9% − 3% = 6%",
      "0.06 / 0.12 = 0.50",
      "ANSWER",
      "0.50",
      "PORTFOLIO MEANING",
    ],
    accent: ACCENT,
    thumbLabel: "Sharpe ratio",
  },
  {
    id: "green-s66",
    number: 66,
    title: "Portal 26 · Simple 95% one-day VaR",
    subtitle: "Portfolio $100,000; one-day volatility 1.2%; z=1.645; zero mean.",
    bullets: [
      "FORMULA",
      "VaR ≈ Portfolio value × z × σ",
      "WHAT ARE WE MEASURING?",
      "Model-based 95% one-day loss threshold under normal assumptions.",
      "WORKINGS",
      "σ = 0.012",
      "1.645 × 0.012 = 0.01974",
      "$100,000 × 0.01974 = $1,974",
      "ANSWER",
      "≈ $1,974",
    ],
    accent: ACCENT,
    thumbLabel: "Simple 95% one-day",
  },
  {
    id: "green-s67",
    number: 67,
    title: "Portal 26 · Leverage",
    subtitle: "Investor equity $20,000; gross exposure $30,000.",
    bullets: [
      "FORMULA",
      "Leverage = Gross exposure / Equity",
      "WHAT ARE WE MEASURING?",
      "Investor controls $1.50 of gross exposure for each $1 of equity.",
      "WORKINGS",
      "$30,000/$20,000 = 1.5",
      "ANSWER",
      "1.5× leverage",
      "PORTFOLIO MEANING",
      "Leverage magnifies gains, losses and potential forced-",
    ],
    accent: ACCENT,
    thumbLabel: "Leverage",
  },
  {
    id: "green-s68",
    number: 68,
    title: "Portal 26 · Recession stress test",
    subtitle: "$6,000 stocks −20%; $4,000 bonds +5%; $3,000 property −15%; $1,800 cash 0%.",
    bullets: [
      "FORMULA",
      "Scenario P/L = Σ(Position value × Scenario return)",
      "WHAT ARE WE MEASURING?",
      "Estimated portfolio dollar loss under the chosen shocks.",
      "WORKINGS",
      "Stocks = −$1,200",
      "Bonds = +$200",
      "Property = −$450",
      "Cash = $0",
      "Total = −$1,450",
    ],
    accent: ACCENT,
    thumbLabel: "Recession stress",
  },
  {
    id: "green-s69",
    number: 69,
    title: "Portal 26 · Scenario return",
    subtitle: "Starting portfolio $14,800; scenario P/L −$1,450.",
    bullets: [
      "FORMULA",
      "Scenario return = Scenario P/L / Starting value ×",
      "100%",
      "WHAT ARE WE MEASURING?",
      "Portfolio-level percentage loss under the scenario.",
      "WORKINGS",
      "−$1,450/$14,800 = −0.097973",
      "×100% = −9.80%",
      "ANSWER",
      "≈ −9.80%",
    ],
    accent: ACCENT,
    thumbLabel: "Scenario return",
  },
  {
    id: "green-s70",
    number: 70,
    title: "Portal 26 · Stress more than prices",
    subtitle: "RECESSION",
    bullets: [
      "Revenue, credit spreads, property and unemployment.",
      "INFLATION SHOCK",
      "Bond prices, margins and pricing power.",
      "RATE SHOCK",
      "Duration, mortgages and valuations.",
      "CURRENCY SHOCK",
      "Foreign holdings and hedges.",
      "COMPANY SHOCK",
      "What if the largest holding falls 40%?",
      "LIQUIDITY SHOCK",
    ],
    accent: ACCENT,
    thumbLabel: "Stress more than",
  },
  {
    id: "green-s71",
    number: 71,
    title: "Portal 27 · Green City Crisis Challenge",
    subtitle: "Combine market, rate, credit, property, currency and company shocks—and make decisions",
    bullets: [
      "under pressure.",
      "UNDERSTAND → CALCULATE → INTERPRET → MANAGE",
    ],
    accent: ACCENT,
    thumbLabel: "Green City Crisis",
  },
  {
    id: "green-s72",
    number: 72,
    title: "Portal 27 · Crisis triage: use this order",
    subtitle: "1 LIQUIDITY",
    bullets: [
      "Are there near-term cash obligations?",
      "2 FORCED RISKS",
      "Margin calls, refinancing, covenants or redemption pressure?",
      "3 THESIS BREAKS",
      "Which assumptions are no longer valid?",
      "4 CONCENTRATION",
      "Which positions now dominate risk?",
      "5 STRESS LOSS",
      "What does the scenario do to capital?",
      "6 VALUATION",
    ],
    accent: ACCENT,
    thumbLabel: "Crisis triage: use",
  },
  {
    id: "green-s73",
    number: 73,
    title: "Portal 27 · Integrated crisis scenario",
    subtitle: "The objective is not to avoid every loss. It is to respond rationally to several shocks at once.",
    bullets: [
      "RATES",
      "Policy rates unexpectedly +1.0 percentage point.",
      "EQUITIES",
      "Broad equity market −15%.",
      "PROPERTY",
      "Portfolio property value −10%.",
      "CREDIT",
      "Corporate spreads widen.",
      "CURRENCY",
      "Home currency appreciates 6%.",
    ],
    accent: ACCENT,
    thumbLabel: "Integrated crisis",
  },
  {
    id: "green-s74",
    number: 74,
    title: "Portal 27 · Crisis duration loss",
    subtitle: "$3,700 bond allocation; modified duration 5.0; yield +1.0%.",
    bullets: [
      "FORMULA",
      "%ΔPrice ≈ −Duration × ΔYield; Dollar P/L ≈ Position",
      "× %ΔPrice",
      "WHAT ARE WE MEASURING?",
      "Approximate interest-rate loss on the bond allocation.",
      "WORKINGS",
      "ΔYield = 0.010",
      "%ΔPrice ≈ −5.0×0.010 = −5.0%",
      "$3,700×(−0.05) = −$185",
      "ANSWER",
      "≈ −$185",
    ],
    accent: ACCENT,
    thumbLabel: "Crisis duration loss",
  },
  {
    id: "green-s75",
    number: 75,
    title: "Portal 27 · Currency shock",
    subtitle: "Foreign asset local return 0%; foreign currency −6% vs home currency.",
    bullets: [
      "FORMULA",
      "Domestic return = (1+Local)(1+FX) − 1",
      "WHAT ARE WE MEASURING?",
      "Currency translation creates a loss even though local asset price is unchanged.",
      "WORKINGS",
      "(1+0)(1−0.06) − 1",
      "= 0.94 − 1 = −0.06",
      "ANSWER",
      "−6.0%",
      "PORTFOLIO MEANING",
    ],
    accent: ACCENT,
    thumbLabel: "Currency shock",
  },
  {
    id: "green-s76",
    number: 76,
    title: "Portal 27 · Weights change during crisis",
    subtitle: "Defensive holding stays $2,500; portfolio falls to $12,500.",
    bullets: [
      "FORMULA",
      "New weight = New position value / New portfolio",
      "value × 100%",
      "WHAT ARE WE MEASURING?",
      "A stable holding becomes a larger share when the rest of the portfolio falls.",
      "WORKINGS",
      "$2,500/$12,500 = 0.20",
      "×100% = 20%",
      "ANSWER",
      "20% new weight",
    ],
    accent: ACCENT,
    thumbLabel: "Weights change",
  },
  {
    id: "green-s77",
    number: 77,
    title: "Portal 27 · Crisis decision grid",
    subtitle: "LONG-DURATION BOND",
    bullets: [
      "Rate shock → quantify duration loss before acting.",
      "SHORT HIGH-QUALITY BOND",
      "May preserve liquidity and stability.",
      "GROWTH STOCK",
      "Separate rate-driven repricing from thesis damage.",
      "WEAK COMPANY",
      "Guidance cut may represent thesis deterioration.",
      "DIRECT PROPERTY",
      "Check debt service and refinancing capacity.",
      "FOREIGN ASSET",
    ],
    accent: ACCENT,
    thumbLabel: "Crisis decision grid",
  },
  {
    id: "green-s78",
    number: 78,
    title: "Green City integrated decision workflow",
    subtitle: "Use one repeatable process across every holding and every portal.",
    bullets: [
      "1 OBSERVE",
      "What changed in price, economics or information?",
      "2 CALCULATE",
      "Use the relevant formula and show workings.",
      "3 INTERPRET",
      "Translate the number into portfolio meaning.",
      "4 COMPARE",
      "Targets, benchmarks, alternatives and scenarios.",
      "5 ACT",
      "Add, hold, trim, exit, replace, hedge or rebalance.",
    ],
    accent: ACCENT,
    thumbLabel: "Integrated flow",
  },
  {
    id: "green-s79",
    number: 79,
    title: "Calculation self-check",
    subtitle: "A correct number is only the middle of the analysis.",
    bullets: [
      "FORMULA",
      "Did I choose the correct relationship?",
      "UNITS",
      "Are dollars, percentages, years and rates consistent?",
      "PERCENTAGES",
      "Did I convert to decimals when multiplying?",
      "WORKINGS",
      "Can another learner follow each step?",
      "INTERPRETATION",
      "Can I explain the answer in one sentence?",
    ],
    accent: ACCENT,
    thumbLabel: "Self-check",
  },
  {
    id: "green-s80",
    number: 80,
    title: "Green City readiness checklist",
    subtitle: "Strong capability means you can explain, calculate, interpret and act.",
    bullets: [
      "BONDS",
      "Coupon, yield, HPR, duration and credit risk.",
      "ETFs / ALTERNATIVES",
      "Costs, holdings, tracking and exposure.",
      "ALLOCATION",
      "Weights, target dollars and expected portfolio return.",
      "DIVERSIFICATION",
      "Concentration, correlation, FX and liquidity.",
      "ACTIVE MANAGEMENT",
      "Add, hold, trim, exit and replace.",
    ],
    accent: ACCENT,
    thumbLabel: "Readiness",
  },
  {
    id: "green-s81",
    number: 81,
    title: "GREEN CITY COMPLETION",
    subtitle: "Manage the portfolio—not the headlines.",
    bullets: [
      "A strong Green City learner can adapt to changing markets without abandoning a disciplined",
      "process.",
      "Measure exposures",
      "Show calculations",
      "Interpret risk",
      "Use new information",
      "Rebalance deliberately",
      "Act under crisis pressure",
      "NEXT: YELLOW CITY — professional portfolio construction and optimization.",
    ],
    footer: "Signal Quay · Green City Portfolio Management Teaching Deck",
    accent: "#c6a15b",
    thumbLabel: "Complete",
  },
];

/** Green City (Signal Quay) Portfolio Management classroom — portals 19–27. */
export const GREEN_CITY_CLASSROOM: ClassroomLesson = {
  id: "green-city-portfolio",
  areaId: "signal-quay",
  themeColor: ACCENT,
  themeColorDeep: ACCENT_DEEP,
  subject: "Portfolio",
  topic: "Green City Portfolio Management",
  title: "Lesson: Green City Portfolio Management",
  classId: "quay-class-green",
  moduleStart: 19,
  moduleEnd: 27,
  outline: [],
  slides: SLIDES,
  notesHref: "/library/signal-quay/green-city-portfolio-management-notes.pdf",
  notesDownloadName: "green-city-portfolio-management-expanded-notes.pdf",
  deckHref: "/library/signal-quay/green-city-portfolio-management-teaching-deck.pdf",
  deckDownloadName: "green-city-portfolio-management-teaching-deck.pdf",
  linkedSites: [
    {
      id: "link-investor-gov-portfolio",
      title: "Investor.gov — Asset Allocation",
      url: "https://www.investor.gov/introduction-investing/investing-basics/asset-allocation",
      platform: "web",
    },
  ],
  quote: {
    text: "Diversification is protection against ignorance. It makes little sense if you know what you are doing.",
    author: "Warren Buffett",
  },
};

