import type { ModuleQuest } from "@/lib/types";

/** Purple City (Coral Ledger Bay) portals 1–9 — syllabus + foundation notes. */
export const MODULES_PURPLE: ModuleQuest[] = [
  {
    id: "m1",
    number: 1,
    title: "Enter the Market",
    mapLabel: "Enter Market",
    x: 20,
    y: 80,
    summary: "Investing vs saving vs trading; risk, return, compounding, inflation and real returns.",
    concepts: [
      "saving vs investing vs trading",
      "risk and return",
      "compound growth",
      "inflation and real return",
      "$14,800 starting capital",
    ],
    outcome: "Establish the first investment objective with your $14,800 virtual cash.",
    lesson: "Saving preserves money for near-term needs. Investing accepts uncertainty to grow purchasing power over time. Trading seeks shorter-term price moves. Return is the gain or loss; risk is that outcomes differ from expectations, including permanent loss. Compounding reinvests gains so returns can earn returns. Nominal return ignores inflation; real return is what remains after inflation. Your simulator starts with $14,800 \u2014 set an objective before deploying capital.",
    scenario: "You receive $14,800. Will you keep it in cash for safety, begin a long-horizon investment plan, or chase short-term trades \u2014 and what objective will guide you?",
    questions: [
      {
        id: "m1-q1",
        prompt: "Which best describes investing versus saving?",
        choices: [
          "Saving preserves near-term liquidity; investing accepts uncertainty to grow purchasing power over time",
          "Investing never involves risk",
          "Saving always beats investing",
          "They are identical",
        ],
        correctIndex: 0,
        explanation: "Saving prioritizes preservation/liquidity; investing accepts risk for longer-term growth.",
      },
      {
        id: "m1-q2",
        prompt: "If $14,800 grows at 7% annually for five years with gains reinvested, which idea is illustrated?",
        choices: [
          "Compound growth (returns earning returns over time)",
          "Guaranteed market profit",
          "Zero inflation forever",
          "A market order fill",
        ],
        correctIndex: 0,
        explanation: "FV = PV(1+r)^n illustrates compounding \u2014 not a guaranteed outcome.",
      },
      {
        id: "m1-q3",
        prompt: "Nominal return differs from real return because:",
        choices: [
          "Real return adjusts for inflation\u2019s effect on purchasing power",
          "Nominal return always includes dividends only",
          "Real return ignores risk",
          "They are the same number",
        ],
        correctIndex: 0,
        explanation: "Real return is purchasing-power aware; nominal is the raw money change.",
      },
      {
        id: "m1-q4",
        prompt: "Higher expected return generally requires:",
        choices: [
          "Accepting some form of additional risk \u2014 without guaranteeing a higher realized return",
          "Zero risk if you use ETFs",
          "Avoiding all asset classes",
          "Ignoring your time horizon",
        ],
        correctIndex: 0,
        explanation: "Risk and expected return are linked; more risk does not guarantee better results.",
      },
      {
        id: "m1-q5",
        prompt: "Your Portfolio Lab mission for Portal 1 is to:",
        choices: [
          "Receive $14,800 and establish a first investment objective",
          "Buy every asset class immediately",
          "Maximize day trades",
          "Delete cash from the portfolio",
        ],
        correctIndex: 0,
        explanation: "Purple City starts by clarifying purpose before action.",
      },
    ],
  },
  {
    id: "m2",
    number: 2,
    title: "Know Your Investor",
    mapLabel: "Investor Profile",
    x: 28,
    y: 84,
    summary:
      "Risk tolerance vs capacity, horizon, liquidity and return objectives — write a personal investment mandate for the $14,800.",
    concepts: [
      "risk tolerance",
      "risk capacity",
      "investment horizon",
      "liquidity needs",
      "return objectives",
      "investment mandate",
    ],
    outcome: "Create a personal investment mandate that constrains portfolio choices.",
    lesson:
      "Risk tolerance is psychological: how much uncertainty and loss you can emotionally accept. Risk capacity is financial: how much loss you can afford without jeopardizing essential goals — you can have high tolerance but low capacity, or the reverse. Horizon is when you need the money; a short horizon usually raises the need for stability and liquidity (turning assets into cash quickly without a large discount). Return objectives must connect to purpose and constraints — “I want 20%” is incomplete. A mandate states objective, horizon, risk tolerance/capacity, minimum cash reserve, permitted asset classes, max single-position weight and review frequency before capital moves.",
    scenario:
      "Draft a one-page mandate for your $14,800 using the notes template: objective, horizon, risk limits, cash reserve, permitted asset classes and max position size. Answer: would a 10% decline make you sell immediately?",
    questions: [
      {
        id: "m2-q1",
        prompt: "Risk tolerance primarily measures:",
        choices: [
          "How much uncertainty and loss you can emotionally accept",
          "Exact future portfolio return",
          "The bid/ask spread",
          "Company market capitalization",
        ],
        correctIndex: 0,
        explanation: "Tolerance is psychological comfort with volatility and drawdowns.",
      },
      {
        id: "m2-q2",
        prompt: "Risk capacity is best described as:",
        choices: [
          "How much loss you can afford without jeopardizing essential goals",
          "How exciting a stock tip feels",
          "The number of shares outstanding",
          "A type of market order",
        ],
        correctIndex: 0,
        explanation: "Capacity is financial ability to bear loss, not just feelings.",
      },
      {
        id: "m2-q3",
        prompt: "Liquidity in this portal means:",
        choices: [
          "Converting an asset to usable cash quickly without a large discount",
          "Owning only the most popular stocks",
          "Never holding cash",
          "Guaranteed overnight profit",
        ],
        correctIndex: 0,
        explanation: "Liquidity is about access to cash without painful price concessions.",
      },
      {
        id: "m2-q4",
        prompt: "Which statement is a complete-enough mandate ingredient set?",
        choices: [
          "Objective, horizon, risk limits, cash reserve, permitted assets and max position weight",
          "A single target return with no constraints",
          "Copying another player’s holdings",
          "Ignoring when the money might be needed",
        ],
        correctIndex: 0,
        explanation: "Mandates turn purpose and constraints into portfolio rules.",
      },
      {
        id: "m2-q5",
        prompt: "Portfolio Lab mission for Portal 2 is to:",
        choices: [
          "Create a personal investment mandate",
          "Execute 20 day trades",
          "Ignore risk capacity",
          "Copy a stranger’s portfolio blindly",
        ],
        correctIndex: 0,
        explanation: "Write the rules that will govern the $14,800.",
      },
    ],
  },
  {
    id: "m3",
    number: 3,
    title: "Understanding Asset Classes",
    mapLabel: "Asset Classes",
    x: 36,
    y: 78,
    summary:
      "Stocks, bonds, ETFs, real estate, businesses, forex, commodities and cash — build a multi-class watchlist.",
    concepts: [
      "asset classes",
      "stocks",
      "bonds",
      "ETFs",
      "real estate",
      "forex",
      "commodities",
      "cash",
    ],
    outcome: "Build an initial asset-class watchlist aligned to your mandate.",
    lesson:
      "An asset class groups investments that share economic characteristics and respond differently to growth, inflation, rates and sentiment — that difference is the foundation of diversification. Stocks are ownership (earnings, dividends, valuation risk). Bonds are debt claims (interest/principal; rates, inflation and credit move prices — when market rates rise, existing fixed-rate bond prices generally fall). ETFs are exchange-traded baskets — check holdings, fees, liquidity and concentration. Real estate can earn rent and appreciation but may be illiquid (REITs trade on exchanges). Cash offers liquidity with inflation drag. Commodities and forex add other macro exposures. Private businesses can be hard to value or sell.",
    scenario:
      "Build a watchlist with at least one idea from six asset classes that fit your Portal 2 mandate. For each, note what it is, main risk, what would move its value, and whether it is invest or observe-only.",
    questions: [
      {
        id: "m3-q1",
        prompt: "A share of stock represents:",
        choices: [
          "An ownership claim on a company",
          "A government-guaranteed savings deposit",
          "A currency pair",
          "Always a risk-free bond",
        ],
        correctIndex: 0,
        explanation: "Equity is ownership of residual business value.",
      },
      {
        id: "m3-q2",
        prompt: "When market interest rates rise, existing fixed-rate bond prices generally:",
        choices: [
          "Fall",
          "Always rise",
          "Become risk-free",
          "Stop paying interest automatically",
        ],
        correctIndex: 0,
        explanation: "New higher yields make older lower-coupon bonds less attractive.",
      },
      {
        id: "m3-q3",
        prompt: "An ETF is useful because it:",
        choices: [
          "Can provide diversified exposure through one exchange-traded vehicle",
          "Eliminates all market risk",
          "Is never traded during market hours",
          "Is identical to holding only cash",
        ],
        correctIndex: 0,
        explanation: "ETFs bundle exposures; risk remains inside the holdings.",
      },
      {
        id: "m3-q4",
        prompt: "Cash in a portfolio mainly provides:",
        choices: [
          "Liquidity and stability, with possible inflation and opportunity cost",
          "Guaranteed outperformance of stocks",
          "Infinite compounding with no trade-offs",
          "Freedom from any mandate rules",
        ],
        correctIndex: 0,
        explanation: "Cash is a deliberate position with benefits and costs.",
      },
      {
        id: "m3-q5",
        prompt: "Portal 3’s Portfolio Lab mission is to:",
        choices: [
          "Build an initial asset-class watchlist",
          "Sell every bond forever",
          "Ignore your mandate",
          "Trade only on social media tips",
        ],
        correctIndex: 0,
        explanation: "Watchlists prepare research without forcing instant buys.",
      },
    ],
  },
  {
    id: "m4",
    number: 4,
    title: "How Markets Work",
    mapLabel: "How Markets Work",
    x: 24,
    y: 72,
    summary:
      "Exchanges, brokers, bid/ask, liquidity, market vs limit orders, spreads, slippage and first-trade checklist.",
    concepts: [
      "exchanges",
      "brokers",
      "bid/ask",
      "liquidity",
      "market order",
      "limit order",
      "spread",
      "slippage",
    ],
    outcome: "Execute the first simulated transaction with cost awareness.",
    lesson:
      "An investor normally sends an order through a broker to an exchange or other venue that matches buyers and sellers. The bid is the best current buying price; the ask is the best current selling price; the spread is trading friction. Liquidity means trading quickly with limited price impact — narrow spreads and depth help; shocks can erase liquidity. Market orders prioritize execution at available prices; limit orders set your worst acceptable price and may not fill. Costs include commissions plus spreads, slippage and market impact. Before the first trade, answer: what, why now, size, order type, estimated cost, exit plan and % of the $14,800.",
    scenario:
      "Place your first simulated order using the first-trade checklist. Choose market vs limit carefully and estimate spread cost (e.g. buy at ask, sell at bid) before clicking.",
    questions: [
      {
        id: "m4-q1",
        prompt: "The ask price is:",
        choices: [
          "The price at which sellers are currently willing to sell",
          "Always lower than the bid",
          "The dividend yield",
          "Your risk capacity",
        ],
        correctIndex: 0,
        explanation: "You typically buy near the ask in a simple quote.",
      },
      {
        id: "m4-q2",
        prompt: "A market buy order primarily prioritizes:",
        choices: [
          "Immediate execution at available prices",
          "A guaranteed maximum purchase price",
          "Zero commissions forever",
          "Avoiding all slippage",
        ],
        correctIndex: 0,
        explanation: "Market orders chase a fill, not price certainty.",
      },
      {
        id: "m4-q3",
        prompt: "A buy limit order:",
        choices: [
          "Sets the maximum price you are willing to pay and may not execute",
          "Always fills instantly at any price",
          "Removes bid/ask spreads",
          "Is only used for forex",
        ],
        correctIndex: 0,
        explanation: "Limits give price control with fill risk.",
      },
      {
        id: "m4-q4",
        prompt: "If you buy 100 shares at a $20.10 ask and could sell at a $20.00 bid, spread cost is:",
        choices: ["$10", "$0", "$2,010", "$100"],
        correctIndex: 0,
        explanation: "100 × $0.10 = $10 of spread cost.",
      },
      {
        id: "m4-q5",
        prompt: "Portal 4’s mission is to:",
        choices: [
          "Execute the first simulated transaction",
          "Delete your mandate",
          "Ignore transaction costs",
          "Only use leverage",
        ],
        correctIndex: 0,
        explanation: "Practice a careful first fill with cost awareness.",
      },
    ],
  },
  {
    id: "m5",
    number: 5,
    title: "Reading the Market",
    mapLabel: "Reading Markets",
    x: 32,
    y: 68,
    summary:
      "Charts, market-cap math, indices, volume, volatility and sentiment — read before you decide.",
    concepts: [
      "price charts",
      "market capitalization",
      "indices",
      "volume",
      "volatility",
      "sentiment",
      "expectations",
    ],
    outcome: "Interpret basic market information before making a decision.",
    lesson:
      "Charts summarize historical prices (direction, range, pullbacks, variability) — they do not establish fundamental value. Market capitalization ≈ share price × shares outstanding (equity value, not full enterprise value including debt); a higher share price does not always mean a larger company. Indices (S&P 500, DJIA, Nasdaq Composite, etc.) are barometers/benchmarks — pick one that matches the risk you take. Volume shows participation; volatility shows move size; sentiment can move price without changing fundamentals. Prices respond to information relative to expectations — separate facts from the crowd’s reaction.",
    scenario:
      "Complete a market-reading worksheet on one watchlist name: price range, market cap, benchmark, volume vs normal, volatility, plus one fundamental and one sentiment explanation — then decide whether to act.",
    questions: [
      {
        id: "m5-q1",
        prompt: "Market capitalization is approximately:",
        choices: [
          "Share price × shares outstanding",
          "Revenue × P/E",
          "Assets − cash only",
          "Bid − ask",
        ],
        correctIndex: 0,
        explanation: "Market cap values equity shares, not necessarily the whole enterprise.",
      },
      {
        id: "m5-q2",
        prompt: "Company A at $200 with 1M shares vs Company B at $20 with 50M shares:",
        choices: [
          "B has the larger market cap ($1B vs $200M)",
          "A is always the larger company",
          "Share price alone decides company size",
          "Neither has a market cap",
        ],
        correctIndex: 0,
        explanation: "Market cap = price × shares; higher price ≠ larger equity value.",
      },
      {
        id: "m5-q3",
        prompt: "An index such as the S&P 500 is useful as:",
        choices: [
          "A market barometer or performance benchmark",
          "A risk-free savings account",
          "Proof a single stock cannot fall",
          "A type of limit order",
        ],
        correctIndex: 0,
        explanation: "Choose a benchmark that matches the risk you take.",
      },
      {
        id: "m5-q4",
        prompt: "High trading volume during a price jump mainly signals:",
        choices: [
          "Unusually strong participation — not automatic fundamental value",
          "That the stock is risk-free",
          "That inflation is zero",
          "That you should always use market orders",
        ],
        correctIndex: 0,
        explanation: "Volume shows activity; research still decides value.",
      },
      {
        id: "m5-q5",
        prompt: "Portal 5’s mission is to:",
        choices: [
          "Interpret basic market information before deciding",
          "Ignore benchmarks",
          "Trade only on sentiment",
          "Avoid looking at prices",
        ],
        correctIndex: 0,
        explanation: "Read the market thoughtfully, then decide.",
      },
    ],
  },

  {
    id: "m6",
    number: 6,
    title: "Research Fundamentals",
    mapLabel: "Research Desk",
    x: 40,
    y: 72,
    summary:
      "Evidence hierarchy, source credibility tests, research logs and ranking opportunities before capital moves.",
    concepts: [
      "evidence hierarchy",
      "primary sources",
      "source credibility",
      "research log",
      "confirmation bias",
      "disconfirming evidence",
    ],
    outcome: "Research several opportunities and rank the quality of the evidence.",
    lesson:
      "Good research separates primary evidence (filings, audited reports, official releases, regulatory disclosures) from interpretation (analyst notes, journalism) and from leads/sentiment (tips, social posts) that must be verified. Start with “What would I need to know to decide whether this deserves capital?” — not “Why should I buy this tip?” — to reduce confirmation bias. Score sources on authority, evidence, timeliness, incentives, consistency and specificity. Keep a research log with date, asset, question, source, finding and decision impact. When two ideas compete for the same dollars, rank which has stronger primary evidence before sizing a position.",
    scenario:
      "Research two watchlist ideas. Complete one research-log row for each, note the strongest primary source, score credibility, and rank which idea deserves capital first — and which is observe-only.",
    questions: [
      {
        id: "m6-q1",
        prompt: "The best first research question is:",
        choices: [
          "What would I need to know to decide if this deserves capital?",
          "How do I justify buying this tip?",
          "Which influencer likes it?",
          "How do I ignore risks?",
        ],
        correctIndex: 0,
        explanation: "Curiosity before commitment reduces confirmation bias.",
      },
      {
        id: "m6-q2",
        prompt: "Which source is generally closest to primary evidence?",
        choices: [
          "Audited company filings / official economic releases",
          "Anonymous social media claims",
          "Unverified rumor screenshots",
          "A meme about prices",
        ],
        correctIndex: 0,
        explanation: "Primary documents beat unverified commentary.",
      },
      {
        id: "m6-q3",
        prompt: "A credibility test should include:",
        choices: [
          "Authority, evidence, timeliness, incentives, consistency, specificity",
          "Only the stock’s ticker length",
          "Whether the logo looks premium",
          "Ignoring conflicts of interest",
        ],
        correctIndex: 0,
        explanation: "Incentives and evidence quality matter as much as confidence.",
      },
      {
        id: "m6-q4",
        prompt:
          "You have Idea A backed by a current 10-K and Idea B backed only by an anonymous tip. For a $2,220 slot, the disciplined ranking is:",
        choices: [
          "Prefer Idea A unless Idea B can produce verifiable primary evidence",
          "Always buy the tip because it sounds urgent",
          "Ignore filings if the tip has more likes",
          "Split 50/50 with no research log",
        ],
        correctIndex: 0,
        explanation: "Rank evidence quality before allocating scarce capital.",
      },
      {
        id: "m6-q5",
        prompt: "Portal 6’s Portfolio Lab mission is to:",
        choices: [
          "Research opportunities and rank evidence quality",
          "Buy first, research later",
          "Delete primary sources",
          "Use only sentiment polls",
        ],
        correctIndex: 0,
        explanation: "Evidence ranking precedes capital deployment.",
      },
    ],
  },
  {
    id: "m7",
    number: 7,
    title: "Build Your First Portfolio",
    mapLabel: "First Portfolio",
    x: 22,
    y: 62,
    summary:
      "Position size, portfolio weights, diversification checks and cash allocation for the $14,800 book.",
    concepts: [
      "position size",
      "portfolio weight",
      "diversification",
      "concentration",
      "cash allocation",
      "$14,800 deployment",
    ],
    outcome: "Deploy part or all of the $14,800 into a defensible starting portfolio.",
    lesson:
      "Position size is the dollars committed; portfolio weight = position value ÷ total portfolio value × 100%. Example: $5,180 of stocks in a $14,800 book is 35%; a $2,220 single name is 15% — too large if your mandate caps one position at 12%. Diversification spreads non-identical risks; ten names in one industry can still be one bet. Cash (e.g. 15% = $2,220) buys liquidity and optionality but can lose purchasing power to inflation. Construction sequence: re-read the mandate → target asset-class weights → select Portal 6 researched candidates → set max single-position size → decide cash → check concentration by class/sector/geography/currency → execute and record each thesis. An illustrative mix for practice: stocks $5,180 (35%), bonds $2,960 (20%), ETF $2,220 (15%), real-estate $1,480 (10%), commodity $740 (5%), cash $2,220 (15%).",
    scenario:
      "Propose target weights for $14,800 that respect your cash reserve and max single-position rule. Calculate each sleeve in dollars and percent, then justify sizes with Portal 6 evidence — not conviction alone.",
    questions: [
      {
        id: "m7-q1",
        prompt: "Portfolio weight equals:",
        choices: [
          "Position value / total portfolio value × 100%",
          "Share price × P/E",
          "Bid + ask",
          "Only the cash balance",
        ],
        correctIndex: 0,
        explanation: "Weights reveal concentration risk across the whole book.",
      },
      {
        id: "m7-q2",
        prompt:
          "In a $14,800 portfolio, a $2,960 bond sleeve is approximately what weight?",
        choices: [
          "20%",
          "2%",
          "50%",
          "100%",
        ],
        correctIndex: 0,
        explanation: "$2,960 ÷ $14,800 × 100% = 20%.",
      },
      {
        id: "m7-q3",
        prompt:
          "Mandate max single-position weight is 12%. A proposed buy of $2,220 in a $14,800 book is:",
        choices: [
          "About 15% — above the cap, so size down or do not buy full size",
          "Exactly 12% — perfect fill",
          "Under 5% — always safe",
          "Impossible to calculate without P/E",
        ],
        correctIndex: 0,
        explanation: "$2,220 ÷ $14,800 ≈ 15% > 12% mandate limit.",
      },
      {
        id: "m7-q4",
        prompt: "Diversification fails when:",
        choices: [
          "Many holdings still share the same economic bet",
          "You own more than one ETF",
          "You hold any cash",
          "You use a research log",
        ],
        correctIndex: 0,
        explanation: "Shared drivers matter more than ticker count.",
      },
      {
        id: "m7-q5",
        prompt: "Portal 7’s mission is to:",
        choices: [
          "Deploy part or all of $14,800 into a defensible starting portfolio",
          "Keep 100% in one meme tip",
          "Ignore weights",
          "Skip diversification forever",
        ],
        correctIndex: 0,
        explanation: "Build an allocation you can defend with weights and evidence.",
      },
    ],
  },
  {
    id: "m8",
    number: 8,
    title: "Investment Decisions",
    mapLabel: "Decide & Act",
    x: 30,
    y: 58,
    summary:
      "BUY, ADD, HOLD, TRIM and EXIT — opportunity cost, position-weight math and decision journals.",
    concepts: [
      "buy",
      "add",
      "hold",
      "trim",
      "exit",
      "opportunity cost",
      "decision journal",
      "falsifiers",
    ],
    outcome: "Make and document active portfolio decisions with clear rationale.",
    lesson:
      "Active portfolio language: BUY opens a position when expected reward justifies risk; ADD increases when evidence strengthens or valuation improves; HOLD keeps exposure when the thesis and size remain appropriate; TRIM reduces exposure for valuation, concentration, risk or a better use of capital; EXIT closes when the thesis breaks or capital has a superior alternative. Opportunity cost is the next-best alternative forgone — a $2,220 slot held in ABC cannot also fund DEF or sit as cash optionality. Example: HOLD at 15% weight vs mandate 12% → TRIM $444 to restore the cap ($14,800 × 3% ≈ $444). A strong rationale states action, evidence, what changed, expected reward, main risk, new portfolio weight, falsifiers and a review date. “The price is going up” is an observation, not a thesis.",
    scenario:
      "For each holding or watchlist candidate, choose BUY/ADD/HOLD/TRIM/EXIT. Calculate the new portfolio weight after the action and record evidence, opportunity cost and what would prove the decision wrong.",
    questions: [
      {
        id: "m8-q1",
        prompt: "TRIM most often means:",
        choices: [
          "Reduce exposure due to valuation, concentration, risk or a better opportunity",
          "Always sell everything to cash",
          "Never take profits",
          "Ignore opportunity cost",
        ],
        correctIndex: 0,
        explanation: "Trimming is controlled risk or capital rotation — not panic.",
      },
      {
        id: "m8-q2",
        prompt: "EXIT is appropriate when:",
        choices: [
          "The thesis breaks or capital has a clearly better use",
          "A stock is up for one day",
          "You feel bored",
          "An index exists",
        ],
        correctIndex: 0,
        explanation: "Exit when the reason to own is gone or capital is better deployed.",
      },
      {
        id: "m8-q3",
        prompt:
          "A name is 15% of a $14,800 book; mandate max is 12%. Approximate TRIM dollars to restore the cap:",
        choices: [
          "About $444 (3% × $14,800)",
          "$14,800",
          "$0 — weights never matter",
          "$2,220 exactly every time",
        ],
        correctIndex: 0,
        explanation: "15% − 12% = 3%; 0.03 × 14,800 = 444.",
      },
      {
        id: "m8-q4",
        prompt: "Opportunity cost is:",
        choices: [
          "The value of the next-best alternative you forgo",
          "A type of stock exchange",
          "Always zero in cash",
          "Only relevant to forex",
        ],
        correctIndex: 0,
        explanation: "Every allocation displaces another use of capital.",
      },
      {
        id: "m8-q5",
        prompt: "Portal 8’s mission is to:",
        choices: [
          "Make and document active portfolio decisions",
          "Never update holdings",
          "Avoid stating why you acted",
          "Only use market orders",
        ],
        correctIndex: 0,
        explanation: "Decision discipline — with a journal — is the skill.",
      },
    ],
  },
  {
    id: "m9",
    number: 9,
    title: "Purple City Challenge",
    mapLabel: "Purple Challenge",
    x: 38,
    y: 62,
    summary:
      "Defend mandate, allocation, evidence and risk; score the rubric; calculate rebalance trades before Blue City.",
    concepts: [
      "portfolio review",
      "defense structure",
      "evidence quality",
      "rebalancing",
      "rubric weights",
      "mandate check",
    ],
    outcome: "Defend the initial portfolio and rebalance before entering Blue City.",
    lesson:
      "The Purple City Challenge is a defense of process, not a race for the highest short-term return. Structure the defense: mandate (objective, horizon, risk, liquidity) → allocation and cash reserve → thesis for every holding → strongest evidence and uncertainties → concentrations and downside scenarios → at least one BUY/ADD/HOLD/TRIM/EXIT with rationale → weaknesses → rebalance actions. Rubric weights: mandate 15%, research 20%, construction 20%, decision rationale 20%, risk awareness 15%, reflection 10%. Rebalance math example: target stocks 35% ($5,180) but current stocks $6,290 (42.5%) → overweight 7.5% ≈ $1,110 to TRIM; if cash is 8% vs 15% target, raise cash toward $2,220. You are ready for Blue City when the $14,800 book is defensible even if near-term performance disappoints.",
    scenario:
      "Present a short defense of your Purple City portfolio: mandate, allocation weights (with dollar amounts), top holdings and evidence, main risks, one scored rubric gap, and one calculated rebalance (TRIM/ADD/cash) before Blue City.",
    questions: [
      {
        id: "m9-q1",
        prompt: "The Purple City Challenge mainly asks you to:",
        choices: [
          "Review foundations and defend/rebalance the starting portfolio",
          "Delete the portfolio and restart at $0",
          "Skip to Yellow City",
          "Ignore your mandate",
        ],
        correctIndex: 0,
        explanation: "Portal 9 is an integrated defense and cleanup.",
      },
      {
        id: "m9-q2",
        prompt:
          "Target stocks 35% of $14,800 but current stocks are $6,290. Approximate overweight to TRIM:",
        choices: [
          "About $1,110 (42.5% − 35% of the book)",
          "$6,290 — sell the entire sleeve",
          "$0 — never rebalance",
          "$14,800 — restart cash",
        ],
        correctIndex: 0,
        explanation: "$6,290 / $14,800 ≈ 42.5%; 7.5% × $14,800 ≈ $1,110.",
      },
      {
        id: "m9-q3",
        prompt: "Which rubric area carries 20% weight alongside research and construction?",
        choices: [
          "Decision rationale (actions linked to evidence and opportunity cost)",
          "Logo design quality",
          "Number of day trades",
          "Ignoring downside scenarios",
        ],
        correctIndex: 0,
        explanation: "Decision rationale is 20% of the Purple City rubric.",
      },
      {
        id: "m9-q4",
        prompt: "Rebalancing is useful when:",
        choices: [
          "Exposures drift from targets or evidence changes your plan",
          "You want to trade every minute",
          "Cash must always be zero",
          "Research logs are banned",
        ],
        correctIndex: 0,
        explanation: "Rebalancing restores intentional risk after drift or new evidence.",
      },
      {
        id: "m9-q5",
        prompt: "After Purple City you should be ready to:",
        choices: [
          "Enter Blue City analysis & asset selection with a defended base portfolio",
          "Stop using the Portfolio Lab",
          "Avoid financial statements",
          "Never update theses",
        ],
        correctIndex: 0,
        explanation: "Purple builds process foundations for Blue’s deeper valuation work.",
      },
    ],
  },
];

