import type { ModuleQuest } from "@/lib/types";
import { MODULES_EXTRA } from "@/lib/content/modules-extra";

/** 36 syllabus modules as quest portals on the adventure map. */
const MODULES_CORE: ModuleQuest[] = [
  {
    id: "m1",
    number: 1,
    title: "Welcome to Investing",
    mapLabel: "Opening Bell",
    x: 8,
    y: 72,
    summary: "Investing vs saving vs trading — claim your starting capital.",
    concepts: [
      "investing vs saving vs trading",
      "stocks, bonds, ETFs, commodities, cash",
      "risk and return",
      "compound growth",
    ],
    outcome: "Understand the purpose of investing and major asset classes.",
    lesson:
      "Investing puts capital to work for future return. Saving preserves cash. Trading seeks short-term price moves. Stocks are ownership, bonds are loans, ETFs bundle many holdings, commodities are real goods, and cash is dry powder. Return usually requires accepting risk; compounding rewards time.",
    scenario:
      "You receive $14,800 virtual capital. Do you invest immediately, hold cash, or build a starter allocation — and why?",
    questions: [
      {
        id: "m1-q1",
        prompt: "Which statement best separates investing from trading?",
        choices: [
          "Investing always uses leverage; trading never does",
          "Investing focuses on longer-horizon ownership of cash flows; trading focuses on short-term price moves",
          "Investing only uses ETFs; trading only uses stocks",
          "They are identical terms",
        ],
        correctIndex: 1,
        explanation:
          "Horizon and intent differ: investing compounds ownership/cash flows; trading seeks near-term price changes.",
      },
      {
        id: "m1-q2",
        prompt: "An ETF is best described as:",
        choices: [
          "A single private company share",
          "A fund that holds a basket of assets and trades on an exchange",
          "A government savings account",
          "A loan you make to a bank",
        ],
        correctIndex: 1,
        explanation: "ETFs package many holdings into one exchange-traded vehicle.",
      },
      {
        id: "m1-q3",
        prompt: "You hold cash while researching. What is the main trade-off?",
        choices: [
          "Cash has infinite expected return",
          "Cash avoids market risk but may lose purchasing power to inflation",
          "Cash guarantees beating the market",
          "Cash cannot be part of a portfolio",
        ],
        correctIndex: 1,
        explanation: "Cash is low volatility but can lose real value when inflation runs hot.",
      },
    ],
  },
  {
    id: "m2",
    number: 2,
    title: "Understanding the Stock Market",
    mapLabel: "Exchange Floor",
    x: 18,
    y: 58,
    summary: "Orders, indices, and your first trade under a sudden 15% spike.",
    concepts: ["exchanges", "market cap", "bid/ask", "orders", "bull/bear"],
    outcome: "Execute first trades while navigating order types and price moves.",
    lesson:
      "A stock is a claim on a company. Prices form on exchanges via bids and asks. Market orders fill now; limit orders wait for your price. Indices summarize baskets of stocks. Bull markets rise; bear markets fall.",
    scenario:
      "A stock jumps 15% in a day. Do you buy the breakout, wait, research first, or avoid?",
    questions: [
      {
        id: "m2-q1",
        prompt: "A market order primarily prioritizes:",
        choices: ["Price certainty", "Immediate execution", "Dividend yield", "Tax deferral"],
        correctIndex: 1,
        explanation: "Market orders chase fill speed, not a guaranteed price.",
        chartHint: "stock",
      },
      {
        id: "m2-q2",
        prompt: "Market capitalization equals:",
        choices: [
          "Revenue × margin",
          "Share price × shares outstanding",
          "Assets − liabilities",
          "Dividend × payout ratio",
        ],
        correctIndex: 1,
        explanation: "Market cap is equity value implied by the share price.",
      },
      {
        id: "m2-q3",
        prompt: "After a 15% spike with no news you researched, the most disciplined next step is usually:",
        choices: [
          "Max leverage buy",
          "Pause and check thesis, liquidity, and valuation before acting",
          "Sell every other holding",
          "Ignore price entirely forever",
        ],
        correctIndex: 1,
        explanation: "Sudden moves without homework invite FOMO; verify the thesis first.",
        chartHint: "stock",
      },
    ],
  },
  {
    id: "m3",
    number: 3,
    title: "Risk, Return & Behaviour",
    mapLabel: "Risk Alley",
    x: 28,
    y: 68,
    summary: "Survive the first portfolio decline without panic.",
    concepts: ["volatility", "risk tolerance", "loss aversion", "FOMO", "herding"],
    outcome: "Respond to a decline with process, not panic.",
    lesson:
      "Expected return is the payoff you hope for; volatility and drawdowns are the path risk. Risk tolerance is emotional; risk capacity is financial. Biases (loss aversion, FOMO, herding, anchoring) distort decisions.",
    scenario:
      "Your Portfolio Lab drops sharply. Sell, hold, rebalance, or research further?",
    questions: [
      {
        id: "m3-q1",
        prompt: "Loss aversion means investors tend to:",
        choices: [
          "Feel losses more strongly than equivalent gains",
          "Prefer only crypto",
          "Ignore all news",
          "Always buy dips with leverage",
        ],
        correctIndex: 0,
        explanation: "Losses typically hurt more than similar gains please — driving panic sells.",
      },
      {
        id: "m3-q2",
        prompt: "Risk capacity differs from risk tolerance because capacity is about:",
        choices: [
          "How exciting charts look",
          "Your financial ability to absorb losses given goals and horizon",
          "Whether friends are buying",
          "The color of candlesticks",
        ],
        correctIndex: 1,
        explanation: "Capacity is objective affordability of risk; tolerance is comfort.",
      },
      {
        id: "m3-q3",
        prompt: "In a sudden decline, a sound first move is:",
        choices: [
          "Liquidate everything instantly",
          "Revisit thesis, horizon, and position size before changing course",
          "Double every position",
          "Stop looking at statements forever",
        ],
        correctIndex: 1,
        explanation: "Process first: thesis and constraints beat reflex.",
        chartHint: "stock",
      },
    ],
  },
  {
    id: "m4",
    number: 4,
    title: "How to Research a Company",
    mapLabel: "Research Desk",
    x: 38,
    y: 52,
    summary: "Compare three businesses before you dig deeper.",
    concepts: ["business model", "moat", "competition", "management"],
    outcome: "Choose which company deserves deeper research — and defend why.",
    lesson:
      "Great research starts with how a company makes money, who pays, what advantages persist, and how competition or disruption could erode them.",
    scenario:
      "Three firms look interesting. Which one do you research first, and what evidence tips you?",
    questions: [
      {
        id: "m4-q1",
        prompt: "A durable competitive advantage (moat) most often shows up as:",
        choices: [
          "One lucky quarter",
          "Persistent pricing power, switching costs, network effects, or cost advantages",
          "A viral meme",
          "High short interest alone",
        ],
        correctIndex: 1,
        explanation: "Moats are structural advantages that persist across cycles.",
      },
      {
        id: "m4-q2",
        prompt: "Before deep-dive modeling, the best filter is usually:",
        choices: [
          "Only the logo color",
          "Business model clarity and industry structure",
          "Ignoring competitors",
          "Assuming growth forever",
        ],
        correctIndex: 1,
        explanation: "If you cannot explain the model, valuation theater is premature.",
      },
      {
        id: "m4-q3",
        prompt: "Industry structure matters because:",
        choices: [
          "It never affects margins",
          "Rivalry, buyers, suppliers, and substitutes shape sustainable returns",
          "Only macro matters",
          "It replaces reading financials",
        ],
        correctIndex: 1,
        explanation: "Porter-style forces frame how hard it is to earn excess returns.",
      },
    ],
  },
  {
    id: "m5",
    number: 5,
    title: "Reading Financial Statements",
    mapLabel: "Ledger Lane",
    x: 48,
    y: 62,
    summary: "Profit without cash flow is a trap.",
    concepts: ["income statement", "balance sheet", "cash flow", "FCF"],
    outcome: "Investigate when accounting profit and cash diverge.",
    lesson:
      "Income statements show accrual profit; cash-flow statements show cash reality; balance sheets show resources and claims. Free cash flow funds reinvestment, debt paydown, and owner returns.",
    scenario:
      "A company reports strong profit but cash flow is deteriorating. Investigate before buying.",
    questions: [
      {
        id: "m5-q1",
        prompt: "If net income rises while operating cash flow falls for several periods, you should:",
        choices: [
          "Celebrate and max buy",
          "Investigate receivables, inventory, and earnings quality",
          "Ignore cash forever",
          "Assume auditors always catch issues instantly",
        ],
        correctIndex: 1,
        explanation: "Cash divergence is a classic earnings-quality red flag.",
      },
      {
        id: "m5-q2",
        prompt: "Free cash flow is roughly:",
        choices: [
          "Revenue − dividends",
          "Operating cash flow − capital expenditures",
          "Assets − liabilities",
          "Share price × EPS",
        ],
        correctIndex: 1,
        explanation: "FCF approximates cash left after maintaining/growing the asset base.",
      },
      {
        id: "m5-q3",
        prompt: "The balance sheet is most useful for seeing:",
        choices: [
          "Only marketing spend",
          "Assets, liabilities, and equity at a point in time",
          "Intraday candles",
          "Twitter sentiment",
        ],
        correctIndex: 1,
        explanation: "It is a snapshot of financial position.",
      },
    ],
  },
  {
    id: "m6",
    number: 6,
    title: "Financial Ratios",
    mapLabel: "Ratio Row",
    x: 58,
    y: 48,
    summary: "Ratios only mean something in context.",
    concepts: ["P/E", "ROE", "debt-to-equity", "margins", "FCF yield"],
    outcome: "Compare companies with ratios without treating any metric as magic.",
    lesson:
      "Ratios compress financials into comparable signals. A low P/E can be cheap or a value trap. ROE can be high from leverage. Always compare peers, history, and business quality.",
    scenario: "Two peers have different P/E and ROE. Which deserves capital, and why?",
    questions: [
      {
        id: "m6-q1",
        prompt: "A very high ROE funded mostly by extreme leverage is:",
        choices: [
          "Always safer than low ROE",
          "A warning that returns may be fragile in stress",
          "Proof of a moat",
          "Irrelevant to risk",
        ],
        correctIndex: 1,
        explanation: "Leverage can inflate ROE and amplify drawdowns.",
      },
      {
        id: "m6-q2",
        prompt: "P/E is most meaningful when:",
        choices: [
          "Compared across totally different industries with no adjustment",
          "Earnings are reasonably sustainable and peers/history provide context",
          "Used alone with no other evidence",
          "The stock just went viral",
        ],
        correctIndex: 1,
        explanation: "Multiple quality depends on earnings quality and context.",
      },
      {
        id: "m6-q3",
        prompt: "Debt-to-equity helps you assess:",
        choices: [
          "Brand love",
          "Financial leverage and balance-sheet risk",
          "Intraday momentum",
          "FX pip spreads",
        ],
        correctIndex: 1,
        explanation: "It frames how much equity cushions creditor claims.",
      },
    ],
  },
  {
    id: "m7",
    number: 7,
    title: "Valuation",
    mapLabel: "Value Spire",
    x: 68,
    y: 58,
    summary: "Estimate value before peeking at price.",
    concepts: ["intrinsic value", "comps", "DCF", "margin of safety"],
    outcome: "Decide whether price vs value justifies investment.",
    lesson:
      "Price is what you pay; value is what you get. Relative valuation uses comps; DCF discounts expected cash flows. Margin of safety buffers estimation error.",
    scenario:
      "Estimate fair value, then reveal market price. Is the gap wide enough to act?",
    questions: [
      {
        id: "m7-q1",
        prompt: "Margin of safety exists to:",
        choices: [
          "Maximize leverage",
          "Buffer against forecast error and adverse surprises",
          "Guarantee profits",
          "Eliminate diversification needs",
        ],
        correctIndex: 1,
        explanation: "It is a cushion for being wrong.",
      },
      {
        id: "m7-q2",
        prompt: "In a simple DCF, a higher discount rate generally:",
        choices: [
          "Raises present value",
          "Lowers present value of distant cash flows",
          "Does nothing",
          "Converts equity to debt",
        ],
        correctIndex: 1,
        explanation: "Higher required returns reduce PV of future cash.",
      },
      {
        id: "m7-q3",
        prompt: "If your value estimate is $80 and price is $120, the disciplined default is:",
        choices: [
          "Buy because momentum",
          "Wait or pass unless thesis/price changes",
          "Ignore valuation forever",
          "Short every peer",
        ],
        correctIndex: 1,
        explanation: "Paying far above value needs extraordinary justification.",
      },
    ],
  },
  {
    id: "m8",
    number: 8,
    title: "Growth, Value & Styles",
    mapLabel: "Style Cross",
    x: 78,
    y: 46,
    summary: "Defend which style fits your objectives.",
    concepts: ["growth", "value", "quality", "dividend", "momentum", "GARP"],
    outcome: "Match style to goals — not fashion.",
    lesson:
      "Styles are lenses: growth pays for future expansion, value seeks underpricing, quality seeks durable economics, dividends seek cash return, momentum follows trends. GARP blends growth at a reasonable price.",
    scenario: "Two companies: hyper-growth expensive vs cheap slow grower. Which fits you?",
    questions: [
      {
        id: "m8-q1",
        prompt: "GARP stands for:",
        choices: [
          "Growth at a Reasonable Price",
          "Gold and Rare Platinum",
          "Guaranteed Annual Return Plan",
          "Global Arbitrage Repo Pool",
        ],
        correctIndex: 0,
        explanation: "GARP seeks growth without reckless multiples.",
      },
      {
        id: "m8-q2",
        prompt: "Dividend investing still requires:",
        choices: [
          "Ignoring payout sustainability",
          "Checking cash generation and balance-sheet health",
          "Only buying the highest yield no matter what",
          "Avoiding all equity risk",
        ],
        correctIndex: 1,
        explanation: "Unsafe payouts can be cut; yield traps exist.",
      },
      {
        id: "m8-q3",
        prompt: "Style consistency helps because:",
        choices: [
          "It prevents ever updating views",
          "It reduces random strategy-hopping after short performance streaks",
          "It guarantees alpha",
          "It removes the need for risk limits",
        ],
        correctIndex: 1,
        explanation: "Hopping styles after noise is a common behavioural leak.",
      },
    ],
  },
  {
    id: "m9",
    number: 9,
    title: "ETFs, Bonds & Other Assets",
    mapLabel: "Asset Pier",
    x: 72,
    y: 32,
    summary: "Build allocations for different horizons.",
    concepts: ["ETFs", "bonds", "yields", "REITs", "gold", "cash"],
    outcome: "Compare multi-asset mixes to your Portfolio Lab.",
    lesson:
      "Bonds provide income and often diversify equities; duration and credit risk matter. REITs expose you to property cash flows. Gold can hedge certain regimes. Cash is optionality.",
    scenario: "Construct mixes for a retiree vs a 25-year accumulator — then compare to yours.",
    questions: [
      {
        id: "m9-q1",
        prompt: "When interest rates rise, existing long-duration bond prices typically:",
        choices: ["Rise", "Fall", "Stay identical always", "Convert to equity"],
        correctIndex: 1,
        explanation: "Bond prices and yields move inversely, especially at long duration.",
      },
      {
        id: "m9-q2",
        prompt: "REITs primarily give investors exposure to:",
        choices: [
          "Real estate cash flows via listed vehicles",
          "Only cryptocurrency mining",
          "Central bank reserves",
          "Unlisted art only",
        ],
        correctIndex: 0,
        explanation: "REITs pool property-related income streams.",
      },
      {
        id: "m9-q3",
        prompt: "A broad equity index ETF is often used to:",
        choices: [
          "Concentrate in one stock",
          "Gain diversified market exposure at low cost",
          "Eliminate all risk",
          "Avoid equities entirely",
        ],
        correctIndex: 1,
        explanation: "Index ETFs are core diversification tools.",
      },
    ],
  },
  {
    id: "m10",
    number: 10,
    title: "Portfolio Construction",
    mapLabel: "Portfolio Plaza",
    x: 58,
    y: 28,
    summary: "Stress-test concentration and correlations.",
    concepts: ["diversification", "correlation", "sizing", "rebalancing"],
    outcome: "Decide whether to rebalance after a risk review.",
    lesson:
      "Diversification helps when holdings do not all move together. Position sizing and sector/geography exposure control single-point failure. Rebalancing restores target risk.",
    scenario: "AI flags correlated tech concentration. Rebalance or defend the bet?",
    questions: [
      {
        id: "m10-q1",
        prompt: "True diversification requires more than many tickers if:",
        choices: [
          "They are highly correlated to the same factor",
          "They have different CUSIPs only",
          "They are all cash",
          "Fees are low",
        ],
        correctIndex: 0,
        explanation: "Correlated bets collapse together in stress.",
      },
      {
        id: "m10-q2",
        prompt: "Rebalancing typically:",
        choices: [
          "Sells relative winners and buys relative laggards toward targets",
          "Always doubles winners",
          "Ignores risk",
          "Only happens in bull markets",
        ],
        correctIndex: 0,
        explanation: "It restores intended allocation and risk.",
      },
      {
        id: "m10-q3",
        prompt: "Position sizing matters because:",
        choices: [
          "A correct idea sized too large can still ruin the portfolio",
          "Size never affects outcomes",
          "Only entry price matters",
          "It replaces research",
        ],
        correctIndex: 0,
        explanation: "Risk of ruin is a sizing problem as much as a foresight problem.",
      },
    ],
  },
  {
    id: "m11",
    number: 11,
    title: "Macroeconomics for Investors",
    mapLabel: "Macro Desk",
    x: 44,
    y: 22,
    summary: "Inflation, rates, and growth reshape holdings.",
    concepts: ["GDP", "inflation", "rates", "yield curve", "FX"],
    outcome: "Link macro shocks to assets you already hold.",
    lesson:
      "Growth, inflation, and policy set the weather for assets. Rising rates pressure long-duration valuations; inflation hurts cash and some bonds; FX moves hit foreign earnings and forex trades.",
    scenario: "Inflation rises, rates jump, growth slows. Re-underwrite your book.",
    questions: [
      {
        id: "m11-q1",
        prompt: "All else equal, higher discount rates tend to hurt most:",
        choices: [
          "Short-duration cash-like assets the most",
          "Long-duration growth equities the most",
          "Only gold forever",
          "Nothing",
        ],
        correctIndex: 1,
        explanation: "Distant cash flows are more sensitive to rate changes.",
        chartHint: "stock",
      },
      {
        id: "m11-q2",
        prompt: "A strengthening domestic currency can:",
        choices: [
          "Boost translated foreign earnings for domestic multinationals",
          "Pressure translated foreign earnings for domestic multinationals",
          "Delete FX risk entirely",
          "Set stock splits",
        ],
        correctIndex: 1,
        explanation: "Stronger home currency reduces foreign earnings when translated home.",
        chartHint: "forex",
      },
      {
        id: "m11-q3",
        prompt: "Stagflation-like conditions (high inflation, weak growth) often challenge:",
        choices: [
          "Only crypto",
          "Both traditional bonds and cyclical equities in different ways",
          "Only cash",
          "Nothing ever",
        ],
        correctIndex: 1,
        explanation: "Inflation hurts bonds; weak growth hurts cyclicals — a hard mix.",
        newsHint: true,
      },
    ],
  },
  {
    id: "m12",
    number: 12,
    title: "Earnings & Market News",
    mapLabel: "News Wire",
    x: 30,
    y: 30,
    summary: "Price moves vs expectations — not headlines alone.",
    concepts: ["earnings", "guidance", "surprises", "material news"],
    outcome: "Explain why good growth can still reprice a stock lower.",
    lesson:
      "Markets price expectations. Beating weak expectations can rally a name; beating lofty expectations by less than hoped can drop it. Guidance and quality of growth matter.",
    scenario:
      "A company grows strongly yet the shares fall. Investigate expectations before changing thesis.",
    questions: [
      {
        id: "m12-q1",
        prompt: "An earnings beat with a falling stock often means:",
        choices: [
          "Accounting is illegal always",
          "Results failed a higher bar priced into the shares (or guidance disappointed)",
          "Markets never look forward",
          "Volume was zero",
        ],
        correctIndex: 1,
        explanation: "Expectation gaps dominate short-term earnings reactions.",
        newsHint: true,
        chartHint: "stock",
      },
      {
        id: "m12-q2",
        prompt: "Material news is information that:",
        choices: [
          "Is only gossip",
          "Could reasonably influence an investor's decisions",
          "Never affects price",
          "Only appears on weekends",
        ],
        correctIndex: 1,
        explanation: "Materiality is about decision-relevance.",
      },
      {
        id: "m12-q3",
        prompt: "Before rewriting a thesis on one print, check:",
        choices: [
          "Only the emoji reactions",
          "Whether the long-term drivers actually changed",
          "Only the opening second",
          "Nothing",
        ],
        correctIndex: 1,
        explanation: "Separate noise from thesis-breaking facts.",
      },
    ],
  },
  {
    id: "m13",
    number: 13,
    title: "Market Crashes",
    mapLabel: "Crash Corridor",
    x: 20,
    y: 40,
    summary: "Liquidity, contagion, and disciplined responses.",
    concepts: ["drawdowns", "liquidity", "panic", "defensive assets"],
    outcome: "Log decisions that separate risk management from panic.",
    lesson:
      "Crashes compress liquidity and correlations. Panic selling crystallizes losses; disciplined rebalancing or thesis checks can be appropriate — if sizing and horizon allow.",
    scenario: "Weekly losses escalate. Manage exposure without abandoning process.",
    questions: [
      {
        id: "m13-q1",
        prompt: "In crashes, correlations across risk assets often:",
        choices: [
          "Fall to zero",
          "Rise as many assets sell off together",
          "Become exactly −1 always",
          "Stop existing",
        ],
        correctIndex: 1,
        explanation: "Diversification can fail temporarily when everyone needs cash.",
        chartHint: "stock",
      },
      {
        id: "m13-q2",
        prompt: "Liquidity risk is the danger that:",
        choices: [
          "You cannot exit without large price impact when you need to",
          "Dividends are too high",
          "ETFs never trade",
          "Cash earns interest",
        ],
        correctIndex: 0,
        explanation: "Stressed markets widen spreads and deepen impact costs.",
      },
      {
        id: "m13-q3",
        prompt: "A pre-committed risk rule helps because:",
        choices: [
          "It removes all uncertainty",
          "It reduces improvisation under fear",
          "It guarantees market timing",
          "It bans all equities",
        ],
        correctIndex: 1,
        explanation: "Rules beat adrenaline when drawdowns hit.",
      },
    ],
  },
  {
    id: "m14",
    number: 14,
    title: "Historical Crisis Simulator",
    mapLabel: "Crisis Archive",
    x: 12,
    y: 24,
    summary: "Act first — learn the analogue after.",
    concepts: ["1987", "dot-com", "2008", "COVID shock", "2022 rates"],
    outcome: "Compare your live decisions to historical analogues.",
    lesson:
      "Regimes rhyme: leverage unwind, valuation resets, policy shocks, and liquidity freezes. Studying analogues builds pattern recognition without assuming perfect repetition.",
    scenario: "Enter a hidden historical-style tape; decide; then reveal the analogue.",
    questions: [
      {
        id: "m14-q1",
        prompt: "The 2008 crisis centered heavily on:",
        choices: [
          "Only a single tech IPO",
          "Leverage and fragile funding against housing/credit assets",
          "A gold standard return",
          "FX pip spreads alone",
        ],
        correctIndex: 1,
        explanation: "Funding and credit fragility amplified the housing shock.",
      },
      {
        id: "m14-q2",
        prompt: "2022 challenged long-duration assets mainly via:",
        choices: [
          "Rate and inflation shocks repricing distant cash flows",
          "The end of all stocks forever",
          "Zero volatility",
          "Mandatory gold ownership",
        ],
        correctIndex: 0,
        explanation: "Higher rates compressed valuations for long-duration claims.",
        newsHint: true,
      },
      {
        id: "m14-q3",
        prompt: "Using history well means:",
        choices: [
          "Copy-pasting the last war blindly",
          "Extracting mechanisms while respecting differences today",
          "Ignoring primary sources",
          "Only trading memes",
        ],
        correctIndex: 1,
        explanation: "Mechanisms transfer better than exact path copies.",
      },
    ],
  },
  {
    id: "m15",
    number: 15,
    title: "Advanced Risk Management",
    mapLabel: "Risk Bastion",
    x: 26,
    y: 14,
    summary: "Returns are not enough — control downside.",
    concepts: ["beta", "Sharpe", "drawdown", "VaR", "stress tests"],
    outcome: "Manage the book inside explicit risk limits.",
    lesson:
      "Risk metrics quantify path pain and efficiency. Max drawdown, volatility, beta, and stress scenarios constrain how you pursue return. Alpha is excess return after risk/factor exposure.",
    scenario: "Hit risk limits even if recent returns look fine.",
    questions: [
      {
        id: "m15-q1",
        prompt: "Maximum drawdown measures:",
        choices: [
          "Average dividend",
          "Peak-to-trough decline over a period",
          "Only one-day moves",
          "Bid-ask spread",
        ],
        correctIndex: 1,
        explanation: "It captures the worst peak-to-trough loss path.",
      },
      {
        id: "m15-q2",
        prompt: "A high Sharpe ratio suggests:",
        choices: [
          "Return per unit of volatility looked attractive historically",
          "No future risk exists",
          "Leverage is infinite",
          "Beta is zero always",
        ],
        correctIndex: 0,
        explanation: "Sharpe is a historical efficiency snapshot, not a guarantee.",
      },
      {
        id: "m15-q3",
        prompt: "Stress testing is valuable because:",
        choices: [
          "It predicts exact future prices",
          "It reveals how the portfolio might behave in adverse scenarios",
          "It replaces diversification",
          "It is only for banks",
        ],
        correctIndex: 1,
        explanation: "Scenarios expose hidden concentrations before reality does.",
      },
    ],
  },
  {
    id: "m16",
    number: 16,
    title: "Building an Investment Thesis",
    mapLabel: "Thesis Forge",
    x: 42,
    y: 10,
    summary: "Write what you own, why, risks, and kill criteria.",
    concepts: ["mispricing", "catalysts", "sell discipline", "falsification"],
    outcome: "Defend formal theses for selected holdings.",
    lesson:
      "A thesis states the bet, the market's potential miss, catalysts, risks, and what would prove you wrong. Without falsifiers, you cannot sell with discipline.",
    scenario: "Draft theses for your top holdings with explicit kill switches.",
    questions: [
      {
        id: "m16-q1",
        prompt: "A falsification criterion is:",
        choices: [
          "A reason to never sell",
          "A pre-defined signal that the thesis is broken",
          "A tax form",
          "A candlestick color",
        ],
        correctIndex: 1,
        explanation: "It is your pre-committed 'wrong' detector.",
      },
      {
        id: "m16-q2",
        prompt: "Catalysts matter because:",
        choices: [
          "They may close the gap between price and value",
          "They guarantee timing",
          "They replace valuation",
          "They eliminate risk",
        ],
        correctIndex: 0,
        explanation: "Value can stay unrecognized without a path to recognition.",
      },
      {
        id: "m16-q3",
        prompt: "Sell discipline fails most often when:",
        choices: [
          "Rules were never defined and hope takes over",
          "You rebalance on schedule",
          "You size positions modestly",
          "You keep a journal",
        ],
        correctIndex: 0,
        explanation: "Hope is not a risk process.",
      },
    ],
  },
  {
    id: "m17",
    number: 17,
    title: "Journal & Bias Detection",
    mapLabel: "Bias Mirror",
    x: 58,
    y: 12,
    summary: "Your history becomes the curriculum.",
    concepts: ["confirmation bias", "disposition effect", "overconfidence"],
    outcome: "Correct recurring behavioural patterns with targeted scenarios.",
    lesson:
      "Journals expose patterns: selling winners too early, clinging to losers, seeking confirming news, overtrading after wins. Adaptation means changing behaviour, not just reading about biases.",
    scenario: "Review your Portfolio Lab history; face a personalised corrective scenario.",
    questions: [
      {
        id: "m17-q1",
        prompt: "The disposition effect is the tendency to:",
        choices: [
          "Sell winners too early and hold losers too long",
          "Only buy bonds",
          "Never trade",
          "Ignore taxes only",
        ],
        correctIndex: 0,
        explanation: "It is a classic behavioural leak around realizing gains/losses.",
      },
      {
        id: "m17-q2",
        prompt: "Confirmation bias shows up when you:",
        choices: [
          "Seek only evidence that supports your existing view",
          "Actively seek disconfirming data",
          "Use checklists",
          "Size small",
        ],
        correctIndex: 0,
        explanation: "You filter the world to protect the thesis.",
      },
      {
        id: "m17-q3",
        prompt: "A useful journal entry includes:",
        choices: [
          "Only the P&L number",
          "Thesis, evidence, emotions, and what would change your mind",
          "Only screenshots of green candles",
          "Nothing dated",
        ],
        correctIndex: 1,
        explanation: "Process detail enables later bias detection.",
      },
    ],
  },
  {
    id: "m18",
    number: 18,
    title: "Capstone: The Fund Mandate",
    mapLabel: "Fund Mandate",
    x: 78,
    y: 16,
    summary: "Graduate from $14,800 to a $10M professional mandate.",
    concepts: ["IPS", "constraints", "committee", "multi-year simulation"],
    outcome: "Integrate judgement, risk, and behaviour under mandate pressure.",
    lesson:
      "Module 18 expands the Portfolio Lab into a professional mandate: $10M AUM, 5-year horizon, 7–10% target return, 20% max drawdown, liquidity and concentration constraints. Write an IPS, face client pressure, survive a crisis exam, and defend process before committee.",
    scenario:
      "Present your $14,800 history, accept the mandate, build the fund, and endure multi-year shocks without abandoning process.",
    questions: [
      {
        id: "m18-q1",
        prompt: "An Investment Policy Statement (IPS) should define:",
        choices: [
          "Only a lucky ticker",
          "Objectives, constraints, risk limits, and governance rules before deploying capital",
          "Intraday scalps only",
          "A promise of no drawdowns",
        ],
        correctIndex: 1,
        explanation: "IPS is the constitution of the mandate.",
      },
      {
        id: "m18-q2",
        prompt: "A client demanding you chase a fashionable asset is a test of:",
        choices: [
          "Whether you abandon process for politics",
          "Your ability to ignore fiduciary duty",
          "Candlestick colors",
          "Tax lot software only",
        ],
        correctIndex: 0,
        explanation: "Stakeholder pressure is part of professional investing.",
      },
      {
        id: "m18-q3",
        prompt: "In the assessment framework, raw return weight is relatively:",
        choices: [
          "Dominant over all process scores",
          "Small versus reasoning, risk, research, and behaviour",
          "The only score that matters",
          "Ignored entirely",
        ],
        correctIndex: 1,
        explanation: "Syllabus weights return at 5% — process dominates mastery.",
      },
    ],
  },
];

export const MODULES: ModuleQuest[] = [...MODULES_CORE, ...MODULES_EXTRA];

export function getModule(id: string) {
  return MODULES.find((m) => m.id === id);
}
