import type { ModuleQuest } from "@/lib/types";

/** Purple City (Coral Ledger Bay) portals 1–9 — syllabus + foundation notes. */
export const MODULES_PURPLE: ModuleQuest[] = [
  {
    id: "m1",
    number: 1,
    title: "Enter the Market",
    mapLabel: "Enter Market",
    x: 20,
    y: 80,
    summary: "Investing vs saving vs trading; risk, return, compounding, inflation and real returns.",
    concepts: [
      "saving vs investing vs trading",
      "risk and return",
      "compound growth",
      "inflation and real return",
      "$14,800 starting capital",
    ],
    outcome: "Establish the first investment objective with your $14,800 virtual cash.",
    lesson: "Saving preserves money for near-term needs. Investing accepts uncertainty to grow purchasing power over time. Trading seeks shorter-term price moves. Return is the gain or loss; risk is that outcomes differ from expectations, including permanent loss. Compounding reinvests gains so returns can earn returns. Nominal return ignores inflation; real return is what remains after inflation. Your simulator starts with $14,800 \u2014 set an objective before deploying capital.",
    scenario: "You receive $14,800. Will you keep it in cash for safety, begin a long-horizon investment plan, or chase short-term trades \u2014 and what objective will guide you?",
    questions: [
      {
        id: "m1-q1",
        prompt: "Which best describes investing versus saving?",
        choices: [
          "Saving preserves near-term liquidity; investing accepts uncertainty to grow purchasing power over time",
          "Investing never involves risk",
          "Saving always beats investing",
          "They are identical",
        ],
        correctIndex: 0,
        explanation: "Saving prioritizes preservation/liquidity; investing accepts risk for longer-term growth.",
      },
      {
        id: "m1-q2",
        prompt: "If $14,800 grows at 7% annually for five years with gains reinvested, which idea is illustrated?",
        choices: [
          "Compound growth (returns earning returns over time)",
          "Guaranteed market profit",
          "Zero inflation forever",
          "A market order fill",
        ],
        correctIndex: 0,
        explanation: "FV = PV(1+r)^n illustrates compounding \u2014 not a guaranteed outcome.",
      },
      {
        id: "m1-q3",
        prompt: "Nominal return differs from real return because:",
        choices: [
          "Real return adjusts for inflation\u2019s effect on purchasing power",
          "Nominal return always includes dividends only",
          "Real return ignores risk",
          "They are the same number",
        ],
        correctIndex: 0,
        explanation: "Real return is purchasing-power aware; nominal is the raw money change.",
      },
      {
        id: "m1-q4",
        prompt: "Higher expected return generally requires:",
        choices: [
          "Accepting some form of additional risk \u2014 without guaranteeing a higher realized return",
          "Zero risk if you use ETFs",
          "Avoiding all asset classes",
          "Ignoring your time horizon",
        ],
        correctIndex: 0,
        explanation: "Risk and expected return are linked; more risk does not guarantee better results.",
      },
      {
        id: "m1-q5",
        prompt: "Your Portfolio Lab mission for Portal 1 is to:",
        choices: [
          "Receive $14,800 and establish a first investment objective",
          "Buy every asset class immediately",
          "Maximize day trades",
          "Delete cash from the portfolio",
        ],
        correctIndex: 0,
        explanation: "Purple City starts by clarifying purpose before action.",
      },
    ],
  },
  {
    id: "m2",
    number: 2,
    title: "Know Your Investor",
    mapLabel: "Investor Profile",
    x: 28,
    y: 84,
    summary: "Risk tolerance, capacity, horizon, liquidity needs and return objectives \u2014 write your mandate.",
    concepts: [
      "risk tolerance",
      "risk capacity",
      "investment horizon",
      "liquidity needs",
      "investment mandate",
    ],
    outcome: "Create a personal investment mandate that constrains portfolio choices.",
    lesson: "Risk tolerance is emotional comfort with ups and downs. Risk capacity is what you can afford to lose given finances and goals. Horizon is when you need the money. Liquidity needs are how quickly you may require cash. Return objectives should be realistic given those constraints. Together they form an investment mandate \u2014 rules that keep decisions consistent.",
    scenario: "Draft a one-page mandate for your $14,800: what risks are acceptable, when might you need cash, and what return target is realistic?",
    questions: [
      {
        id: "m2-q1",
        prompt: "Risk tolerance primarily measures:",
        choices: [
          "How much market stress you can emotionally withstand",
          "Exact future portfolio return",
          "The bid/ask spread",
          "Company market capitalization",
        ],
        correctIndex: 0,
        explanation: "Tolerance is psychological comfort with volatility and drawdowns.",
      },
      {
        id: "m2-q2",
        prompt: "Risk capacity is best described as:",
        choices: [
          "What losses you can afford given income, goals and obligations",
          "How exciting a stock tip feels",
          "The number of shares outstanding",
          "A type of market order",
        ],
        correctIndex: 0,
        explanation: "Capacity is financial ability to bear loss, not just feelings.",
      },
      {
        id: "m2-q3",
        prompt: "A short investment horizon usually implies:",
        choices: [
          "Higher need for liquidity and often less aggressive risk taking",
          "You must use maximum leverage",
          "Cash is forbidden",
          "Only forex trading is allowed",
        ],
        correctIndex: 0,
        explanation: "Near-term needs favor liquidity and caution.",
      },
      {
        id: "m2-q4",
        prompt: "An investment mandate should:",
        choices: [
          "State objectives, constraints, horizon and risk limits before allocating capital",
          "Guarantee profits",
          "Replace research entirely",
          "Ignore inflation",
        ],
        correctIndex: 0,
        explanation: "Mandates turn personal constraints into portfolio rules.",
      },
      {
        id: "m2-q5",
        prompt: "Portfolio Lab mission for Portal 2 is to:",
        choices: [
          "Create a personal investment mandate",
          "Execute 20 day trades",
          "Ignore risk capacity",
          "Copy a stranger\u2019s portfolio blindly",
        ],
        correctIndex: 0,
        explanation: "Write the rules that will govern the $14,800.",
      },
    ],
  },
  {
    id: "m3",
    number: 3,
    title: "Understanding Asset Classes",
    mapLabel: "Asset Classes",
    x: 36,
    y: 78,
    summary: "Stocks, bonds, ETFs, real estate, businesses, forex, commodities and cash \u2014 build a watchlist.",
    concepts: [
      "stocks",
      "bonds",
      "ETFs",
      "real estate",
      "forex",
      "commodities",
      "cash",
    ],
    outcome: "Build an initial asset-class watchlist aligned to your mandate.",
    lesson: "Stocks are ownership claims on companies. Bonds are loans that pay interest. ETFs package many holdings into one exchange-traded share. Real estate and private businesses can produce income and appreciation but may be less liquid. Forex is currency exposure. Commodities are real goods like oil or gold. Cash is liquidity and optionality. Diversification starts by understanding how these risks differ.",
    scenario: "Build a watchlist with at least one idea from several asset classes that fit your mandate \u2014 not a single all-in bet.",
    questions: [
      {
        id: "m3-q1",
        prompt: "A share of stock represents:",
        choices: [
          "An ownership claim on a company",
          "A government-guaranteed savings deposit",
          "A currency pair",
          "Always a risk-free bond",
        ],
        correctIndex: 0,
        explanation: "Equity is ownership of residual business value.",
      },
      {
        id: "m3-q2",
        prompt: "A bond is best thought of as:",
        choices: [
          "A loan to an issuer that typically pays interest",
          "Owning the company\u2019s brand only",
          "A type of candlestick chart",
          "Unlimited leverage",
        ],
        correctIndex: 0,
        explanation: "Bonds are debt claims with credit and rate risks.",
      },
      {
        id: "m3-q3",
        prompt: "An ETF is useful because it:",
        choices: [
          "Can provide diversified exposure through one exchange-traded vehicle",
          "Eliminates all market risk",
          "Is never traded during market hours",
          "Is identical to holding only cash",
        ],
        correctIndex: 0,
        explanation: "ETFs bundle exposures; risk remains.",
      },
      {
        id: "m3-q4",
        prompt: "Cash in a portfolio mainly provides:",
        choices: [
          "Liquidity and optionality, with possible inflation drag",
          "Guaranteed outperformance of stocks",
          "Infinite compounding with no trade-offs",
          "Freedom from opportunity cost",
        ],
        correctIndex: 0,
        explanation: "Cash is a deliberate position with benefits and costs.",
      },
      {
        id: "m3-q5",
        prompt: "Portal 3\u2019s Portfolio Lab mission is to:",
        choices: [
          "Build an initial asset-class watchlist",
          "Sell every bond forever",
          "Ignore your mandate",
          "Trade only on social media tips",
        ],
        correctIndex: 0,
        explanation: "Watchlists prepare research without forcing instant buys.",
      },
    ],
  },
  {
    id: "m4",
    number: 4,
    title: "How Markets Work",
    mapLabel: "How Markets Work",
    x: 24,
    y: 72,
    summary: "Exchanges, brokers, bid/ask, liquidity, market vs limit orders, and transaction costs.",
    concepts: [
      "exchanges",
      "bid/ask",
      "market order",
      "limit order",
      "spread",
      "slippage",
    ],
    outcome: "Execute the first simulated transaction with cost awareness.",
    lesson: "Exchanges match buyers and sellers; brokers route orders. The bid is what buyers offer; the ask is what sellers want. The spread is a trading cost. Market orders prioritize speed of fill; limit orders prioritize price control and may not fill. Slippage and commissions also reduce net results. Liquidity is how easily you can trade without moving the price much.",
    scenario: "Place your first simulated order. Choose market vs limit carefully and estimate spread cost before clicking.",
    questions: [
      {
        id: "m4-q1",
        prompt: "The ask price is:",
        choices: [
          "The price at which sellers are currently willing to sell",
          "Always lower than the bid",
          "The dividend yield",
          "Your risk capacity",
        ],
        correctIndex: 0,
        explanation: "You typically buy near the ask in a simple quote.",
      },
      {
        id: "m4-q2",
        prompt: "A market buy order primarily prioritizes:",
        choices: [
          "Immediate execution at available prices",
          "A guaranteed maximum purchase price",
          "Zero commissions forever",
          "Avoiding all slippage",
        ],
        correctIndex: 0,
        explanation: "Market orders chase a fill, not price certainty.",
      },
      {
        id: "m4-q3",
        prompt: "A buy limit order:",
        choices: [
          "Sets the maximum price you are willing to pay and may not execute",
          "Always fills instantly at any price",
          "Removes bid/ask spreads",
          "Is only used for forex",
        ],
        correctIndex: 0,
        explanation: "Limits give price control with fill risk.",
      },
      {
        id: "m4-q4",
        prompt: "If you buy at $20.10 ask and could sell at $20.00 bid for 100 shares, spread cost is:",
        choices: [
          "$10",
          "$0",
          "$2,010",
          "$100",
        ],
        correctIndex: 0,
        explanation: "100 \u00d7 $0.10 = $10 of spread cost.",
      },
      {
        id: "m4-q5",
        prompt: "Portal 4\u2019s mission is to:",
        choices: [
          "Execute the first simulated transaction",
          "Delete your mandate",
          "Ignore transaction costs",
          "Only use leverage",
        ],
        correctIndex: 0,
        explanation: "Practice a careful first fill.",
      },
    ],
  },
  {
    id: "m5",
    number: 5,
    title: "Reading the Market",
    mapLabel: "Reading Markets",
    x: 32,
    y: 68,
    summary: "Charts, market cap, indices, volume, volatility and sentiment before deciding.",
    concepts: [
      "price charts",
      "market capitalization",
      "indices",
      "volume",
      "volatility",
      "sentiment",
    ],
    outcome: "Interpret basic market information before making a decision.",
    lesson: "Charts summarize historical prices \u2014 they do not prove fundamental value. Market capitalization \u2248 share price \u00d7 shares outstanding (equity value, not full enterprise value). Indices are benchmarks/barometers for groups of securities. Volume measures activity; volatility measures how large moves have been; sentiment reflects optimism/pessimism. Always separate market reaction from fundamental evidence.",
    scenario: "Before acting on a price move, complete a market-reading worksheet: price range, market cap, benchmark, volume, volatility, and one fundamental vs sentiment explanation.",
    questions: [
      {
        id: "m5-q1",
        prompt: "Market capitalization is approximately:",
        choices: [
          "Share price \u00d7 shares outstanding",
          "Revenue \u00d7 P/E",
          "Assets \u2212 cash only",
          "Bid \u2212 ask",
        ],
        correctIndex: 0,
        explanation: "Market cap values equity shares, not necessarily the whole enterprise.",
      },
      {
        id: "m5-q2",
        prompt: "A price chart alone:",
        choices: [
          "Shows historical behavior but does not establish fundamental value",
          "Guarantees future returns",
          "Removes volatility",
          "Replaces financial statements",
        ],
        correctIndex: 0,
        explanation: "Charts are evidence of price history, not intrinsic value.",
      },
      {
        id: "m5-q3",
        prompt: "An index such as the S&P 500 is useful as:",
        choices: [
          "A market barometer or performance benchmark",
          "A risk-free savings account",
          "Proof a single stock cannot fall",
          "A type of limit order",
        ],
        correctIndex: 0,
        explanation: "Choose a benchmark that matches the risk you take.",
      },
      {
        id: "m5-q4",
        prompt: "High trading volume during a price jump mainly signals:",
        choices: [
          "Unusually strong participation \u2014 not automatic fundamental value",
          "That the stock is risk-free",
          "That inflation is zero",
          "That you should always use market orders",
        ],
        correctIndex: 0,
        explanation: "Volume shows activity; research still decides value.",
      },
      {
        id: "m5-q5",
        prompt: "Portal 5\u2019s mission is to:",
        choices: [
          "Interpret basic market information before deciding",
          "Ignore benchmarks",
          "Trade only on sentiment",
          "Avoid looking at prices",
        ],
        correctIndex: 0,
        explanation: "Read the tape thoughtfully, then decide.",
      },
    ],
  },
  {
    id: "m6",
    number: 6,
    title: "Research Fundamentals",
    mapLabel: "Research Desk",
    x: 40,
    y: 72,
    summary: "Company reports, economic data, news, source credibility and research logs.",
    concepts: [
      "evidence hierarchy",
      "source credibility",
      "research log",
      "confirmation bias",
      "primary sources",
    ],
    outcome: "Research several opportunities and rank the quality of the evidence.",
    lesson: "Start with \u201cWhat would I need to know?\u201d not \u201cWhy should I buy?\u201d Prefer primary evidence (filings, audited reports, official data) over unverified commentary. Test sources for authority, evidence, timeliness, incentives, consistency and specificity. Keep a research log: date, asset, question, source, finding, decision impact. Seek disconfirming evidence to fight confirmation bias.",
    scenario: "Research two watchlist ideas. Rank which has stronger primary evidence and record both in your research log.",
    questions: [
      {
        id: "m6-q1",
        prompt: "The best first research question is:",
        choices: [
          "What would I need to know to decide if this deserves capital?",
          "How do I justify buying this tip?",
          "Which influencer likes it?",
          "How do I ignore risks?",
        ],
        correctIndex: 0,
        explanation: "Curiosity before commitment reduces confirmation bias.",
      },
      {
        id: "m6-q2",
        prompt: "Which source is generally closer to primary evidence?",
        choices: [
          "Audited company filings / official economic releases",
          "Anonymous social media claims",
          "Unverified rumor screenshots",
          "A meme about prices",
        ],
        correctIndex: 0,
        explanation: "Primary documents beat unverified commentary.",
      },
      {
        id: "m6-q3",
        prompt: "A credibility test should include:",
        choices: [
          "Authority, evidence, timeliness, incentives, consistency, specificity",
          "Only the stock\u2019s ticker length",
          "Whether the logo looks premium",
          "Ignoring conflicts of interest",
        ],
        correctIndex: 0,
        explanation: "Incentives and evidence quality matter.",
      },
      {
        id: "m6-q4",
        prompt: "A research log\u2019s purpose is to:",
        choices: [
          "Record questions, sources, findings and decision impact",
          "Hide mistakes",
          "Replace diversification",
          "Guarantee profits",
        ],
        correctIndex: 0,
        explanation: "Logs make reasoning reviewable.",
      },
      {
        id: "m6-q5",
        prompt: "Portal 6\u2019s mission is to:",
        choices: [
          "Research opportunities and rank evidence quality",
          "Buy first, research later",
          "Delete primary sources",
          "Use only sentiment polls",
        ],
        correctIndex: 0,
        explanation: "Evidence ranking precedes capital deployment.",
      },
    ],
  },
  {
    id: "m7",
    number: 7,
    title: "Build Your First Portfolio",
    mapLabel: "First Portfolio",
    x: 22,
    y: 62,
    summary: "Position sizing, portfolio weights, diversification and cash allocation.",
    concepts: [
      "position size",
      "portfolio weight",
      "diversification",
      "cash allocation",
      "$14,800 deployment",
    ],
    outcome: "Deploy part or all of the $14,800 into a defensible starting portfolio.",
    lesson: "Position size is dollars committed; portfolio weight is that position as a percent of the whole. Even a great idea can hurt you if sized too large. Diversification spreads exposure across risks that are not identical \u2014 many names in one industry can still be concentrated. Cash provides liquidity and optionality but can lose purchasing power to inflation. Re-read your mandate, set target weights, then select researched candidates.",
    scenario: "Propose target weights across asset classes for $14,800 and justify position sizes using your mandate.",
    questions: [
      {
        id: "m7-q1",
        prompt: "Portfolio weight equals:",
        choices: [
          "Position value / total portfolio value \u00d7 100%",
          "Share price \u00d7 P/E",
          "Bid + ask",
          "Only the cash balance",
        ],
        correctIndex: 0,
        explanation: "Weights show concentration risk.",
      },
      {
        id: "m7-q2",
        prompt: "Diversification fails when:",
        choices: [
          "Many holdings still share the same economic bet",
          "You own more than one ETF",
          "You hold any cash",
          "You use a research log",
        ],
        correctIndex: 0,
        explanation: "Correlation and shared drivers matter more than name count.",
      },
      {
        id: "m7-q3",
        prompt: "Position sizing is primarily a:",
        choices: [
          "Risk decision about how much capital an idea deserves",
          "Way to avoid reading statements",
          "Guarantee of higher returns",
          "Substitute for a mandate",
        ],
        correctIndex: 0,
        explanation: "Size controls damage if you are wrong.",
      },
      {
        id: "m7-q4",
        prompt: "A reason to hold some cash is:",
        choices: [
          "Liquidity and optionality for future opportunities",
          "Cash always beats equities",
          "Cash has no opportunity cost",
          "Mandates forbid cash",
        ],
        correctIndex: 0,
        explanation: "Cash is intentional dry powder with trade-offs.",
      },
      {
        id: "m7-q5",
        prompt: "Portal 7\u2019s mission is to:",
        choices: [
          "Deploy part or all of $14,800 into a defensible starting portfolio",
          "Keep 100% in one meme tip",
          "Ignore weights",
          "Skip diversification forever",
        ],
        correctIndex: 0,
        explanation: "Build an allocation you can defend.",
      },
    ],
  },
  {
    id: "m8",
    number: 8,
    title: "Investment Decisions",
    mapLabel: "Decide & Act",
    x: 30,
    y: 58,
    summary: "Buy, add, hold, trim and exit \u2014 opportunity cost and documented rationale.",
    concepts: [
      "buy",
      "add",
      "hold",
      "trim",
      "exit",
      "opportunity cost",
      "decision journal",
    ],
    outcome: "Make and document active portfolio decisions with clear rationale.",
    lesson: "Active management uses a decision language: BUY to open, ADD when evidence/valuation improves, HOLD when the thesis remains intact, TRIM to reduce risk/concentration or fund better ideas, EXIT when the thesis breaks or capital has a better use. Opportunity cost is the next-best alternative you give up. Write the reason before you trade.",
    scenario: "For each holding (or watchlist candidate), choose BUY/ADD/HOLD/TRIM/EXIT and record why \u2014 including what would change your mind.",
    questions: [
      {
        id: "m8-q1",
        prompt: "TRIM most often means:",
        choices: [
          "Reduce exposure due to valuation, concentration, risk or a better opportunity",
          "Always sell everything to cash",
          "Never take profits",
          "Ignore opportunity cost",
        ],
        correctIndex: 0,
        explanation: "Trimming is controlled risk/capital rotation.",
      },
      {
        id: "m8-q2",
        prompt: "EXIT is appropriate when:",
        choices: [
          "The thesis breaks or capital has a clearly better use",
          "A stock is up for one day",
          "You feel bored",
          "An index exists",
        ],
        correctIndex: 0,
        explanation: "Exit when the reason to own is gone.",
      },
      {
        id: "m8-q3",
        prompt: "Opportunity cost is:",
        choices: [
          "The value of the next-best alternative you forgo",
          "A type of stock exchange",
          "Always zero in cash",
          "Only relevant to forex",
        ],
        correctIndex: 0,
        explanation: "Every allocation displaces another use of capital.",
      },
      {
        id: "m8-q4",
        prompt: "Before executing a trade you should:",
        choices: [
          "Document the rationale and falsifiers",
          "Hide the reason from your journal",
          "Maximize leverage first",
          "Skip research if sentiment is hot",
        ],
        correctIndex: 0,
        explanation: "Process quality is part of assessment.",
      },
      {
        id: "m8-q5",
        prompt: "Portal 8\u2019s mission is to:",
        choices: [
          "Make and document active portfolio decisions",
          "Never update holdings",
          "Avoid stating why you acted",
          "Only use market orders",
        ],
        correctIndex: 0,
        explanation: "Decision discipline is the skill.",
      },
    ],
  },
  {
    id: "m9",
    number: 9,
    title: "Purple City Challenge",
    mapLabel: "Purple Challenge",
    x: 38,
    y: 62,
    summary: "Review foundations, holdings, allocation, evidence and weaknesses \u2014 then rebalance.",
    concepts: [
      "portfolio review",
      "evidence quality",
      "rebalancing",
      "mandate check",
      "defend decisions",
    ],
    outcome: "Defend the initial portfolio and rebalance before entering Blue City.",
    lesson: "Purple City ends with an integrated review: Does the portfolio match the mandate? Are weights intentional? Is evidence quality strong enough for each position? Where are concentrations or weak theses? Rebalance when exposures drift from targets or when evidence changes. You are judged on process and risk \u2014 not luck alone \u2014 before advancing to Blue City analysis.",
    scenario: "Present a short defence of your Purple City portfolio: objective, allocation, top holdings, risks, and one rebalance action.",
    questions: [
      {
        id: "m9-q1",
        prompt: "The Purple City Challenge mainly asks you to:",
        choices: [
          "Review foundations and defend/rebalance the starting portfolio",
          "Delete the portfolio and restart at $0",
          "Skip to Yellow City",
          "Ignore your mandate",
        ],
        correctIndex: 0,
        explanation: "Portal 9 is an integrated defence and cleanup.",
      },
      {
        id: "m9-q2",
        prompt: "A portfolio review should check:",
        choices: [
          "Mandate fit, weights, evidence quality and concentrations",
          "Only whether prices went up yesterday",
          "If the logo looks good",
          "Whether you used enough leverage",
        ],
        correctIndex: 0,
        explanation: "Process and risk matter as much as P&L.",
      },
      {
        id: "m9-q3",
        prompt: "Rebalancing is useful when:",
        choices: [
          "Exposures drift from targets or evidence changes your plan",
          "You want to trade every minute",
          "Cash must always be zero",
          "Research logs are banned",
        ],
        correctIndex: 0,
        explanation: "Rebalancing restores intentional risk.",
      },
      {
        id: "m9-q4",
        prompt: "Assessment in the simulator emphasizes:",
        choices: [
          "Research, risk management and decision quality \u2014 not luck alone",
          "Only raw returns",
          "Ignoring drawdowns",
          "Copying tips without evidence",
        ],
        correctIndex: 0,
        explanation: "Discipline beats lucky outcomes.",
      },
      {
        id: "m9-q5",
        prompt: "After Purple City you should be ready to:",
        choices: [
          "Enter Blue City analysis & asset selection with a defended base portfolio",
          "Stop using the Portfolio Lab",
          "Avoid financial statements",
          "Never update theses",
        ],
        correctIndex: 0,
        explanation: "Purple builds foundations for Blue\u2019s deeper work.",
      },
    ],
  },
];

